#!/bin/bash
# Bootstrap script to create S3 bucket and DynamoDB table for Terraform state
# Usage: ./bootstrap-backend.sh <environment> <region>
# Example: ./bootstrap-backend.sh production us-east-1

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check arguments
if [ $# -ne 2 ]; then
    echo -e "${RED}Error: Invalid number of arguments${NC}"
    echo "Usage: $0 <environment> <region>"
    echo "Example: $0 production us-east-1"
    exit 1
fi

ENVIRONMENT=$1
REGION=$2
PROJECT_NAME="vidra"

BUCKET_NAME="${PROJECT_NAME}-terraform-state-${ENVIRONMENT}"
DYNAMODB_TABLE="${PROJECT_NAME}-terraform-locks"

echo -e "${GREEN}=== Terraform Backend Bootstrap ===${NC}"
echo "Environment: $ENVIRONMENT"
echo "Region: $REGION"
echo "Bucket: $BUCKET_NAME"
echo "DynamoDB Table: $DYNAMODB_TABLE"
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo -e "${RED}Error: AWS CLI is not installed${NC}"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}Error: AWS credentials not configured${NC}"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "AWS Account ID: $ACCOUNT_ID"
echo ""

# Create S3 bucket
echo -e "${YELLOW}Creating S3 bucket: $BUCKET_NAME${NC}"
if aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
    if [ "$REGION" == "us-east-1" ]; then
        aws s3api create-bucket \
            --bucket "$BUCKET_NAME" \
            --region "$REGION"
    else
        aws s3api create-bucket \
            --bucket "$BUCKET_NAME" \
            --region "$REGION" \
            --create-bucket-configuration LocationConstraint="$REGION"
    fi
    echo -e "${GREEN}✓ S3 bucket created${NC}"
else
    echo -e "${YELLOW}S3 bucket already exists${NC}"
fi

# Enable versioning
echo -e "${YELLOW}Enabling S3 versioning${NC}"
aws s3api put-bucket-versioning \
    --bucket "$BUCKET_NAME" \
    --versioning-configuration Status=Enabled
echo -e "${GREEN}✓ Versioning enabled${NC}"

# Enable encryption
echo -e "${YELLOW}Enabling S3 encryption${NC}"
aws s3api put-bucket-encryption \
    --bucket "$BUCKET_NAME" \
    --server-side-encryption-configuration '{
        "Rules": [{
            "ApplyServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
            },
            "BucketKeyEnabled": true
        }]
    }'
echo -e "${GREEN}✓ Encryption enabled${NC}"

# Enable public access block
echo -e "${YELLOW}Enabling S3 public access block${NC}"
aws s3api put-public-access-block \
    --bucket "$BUCKET_NAME" \
    --public-access-block-configuration \
        "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
echo -e "${GREEN}✓ Public access blocked${NC}"

# Create DynamoDB table
echo -e "${YELLOW}Creating DynamoDB table: $DYNAMODB_TABLE${NC}"
if ! aws dynamodb describe-table --table-name "$DYNAMODB_TABLE" --region "$REGION" &> /dev/null; then
    aws dynamodb create-table \
        --table-name "$DYNAMODB_TABLE" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "$REGION" \
        --tags "Key=Project,Value=$PROJECT_NAME" "Key=Environment,Value=$ENVIRONMENT" "Key=ManagedBy,Value=Terraform"

    echo -e "${YELLOW}Waiting for DynamoDB table to be active...${NC}"
    aws dynamodb wait table-exists --table-name "$DYNAMODB_TABLE" --region "$REGION"
    echo -e "${GREEN}✓ DynamoDB table created${NC}"
else
    echo -e "${YELLOW}DynamoDB table already exists${NC}"
fi

# Create backend configuration file
BACKEND_CONFIG_FILE="../environments/${ENVIRONMENT}/backend.hcl"
echo -e "${YELLOW}Creating backend configuration file${NC}"
cat > "$BACKEND_CONFIG_FILE" <<EOF
# Backend configuration for Terraform state
# Generated by bootstrap-backend.sh on $(date)

bucket         = "$BUCKET_NAME"
key            = "${ENVIRONMENT}/terraform.tfstate"
region         = "$REGION"
encrypt        = true
dynamodb_table = "$DYNAMODB_TABLE"
EOF
echo -e "${GREEN}✓ Backend configuration file created: $BACKEND_CONFIG_FILE${NC}"

echo ""
echo -e "${GREEN}=== Bootstrap Complete ===${NC}"
echo ""
echo "Next steps:"
echo "1. cd environments/${ENVIRONMENT}"
echo "2. terraform init -backend-config=backend.hcl"
echo "3. terraform plan"
echo "4. terraform apply"
echo ""
