run:
  tests: false
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocyclo
    - dupl
    - misspell
    - unconvert
    - whitespace
    - goimports
    - gofmt
