# Version 1 configuration format
run:
  tests: false
linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 150
  gosec:
    severity: medium
linters:
  enable:
    - bodyclose
    - dupl
    - gocyclo
    - gosec
    - misspell
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - whitespace
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
