version: "2.4.0"

run:
  tests: false
  timeout: 10m
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocyclo
    - dupl
    - misspell
    - unconvert
    - whitespace

formatters:
  enable:
    - goimports
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
