#!/bin/bash
# OpenAPI Endpoint Audit Script
# Extracts all endpoints from routes.go and OpenAPI specs for comparison

echo "=== IMPLEMENTED ENDPOINTS (from routes.go) ==="
echo ""
echo "Authentication Endpoints:"
echo "POST /auth/register"
echo "POST /auth/login"
echo "POST /auth/refresh"
echo "POST /auth/logout"
echo ""

echo "Two-Factor Authentication:"
echo "POST /auth/2fa/setup"
echo "POST /auth/2fa/verify-setup"
echo "POST /auth/2fa/disable"
echo "POST /auth/2fa/regenerate-backup-codes"
echo "GET /auth/2fa/status"
echo ""

echo "OAuth2 Endpoints:"
echo "POST /oauth/token"
echo "GET|POST /oauth/authorize"
echo "POST /oauth/revoke"
echo "POST /oauth/introspect"
echo ""

echo "Health Endpoints:"
echo "GET /health"
echo "GET /ready"
echo ""

echo "Admin OAuth:"
echo "GET /api/v1/admin/oauth/clients"
echo "POST /api/v1/admin/oauth/clients"
echo "DELETE /api/v1/admin/oauth/clients/{clientId}"
echo "PUT /api/v1/admin/oauth/clients/{clientId}/secret"
echo ""

echo "Videos:"
echo "GET /api/v1/videos"
echo "GET /api/v1/videos/search"
echo "GET /api/v1/videos/qualities"
echo "GET /api/v1/videos/top"
echo "POST /api/v1/videos/upload (legacy)"
echo "GET /api/v1/videos/{id}"
echo "GET /api/v1/videos/{id}/stream"
echo "GET /api/v1/videos/subscriptions"
echo "POST /api/v1/videos"
echo "PUT /api/v1/videos/{id}"
echo "DELETE /api/v1/videos/{id}"
echo "POST /api/v1/videos/{id}/upload"
echo "POST /api/v1/videos/{id}/complete"
echo "POST /api/v1/videos/{id}/views"
echo "GET /api/v1/videos/{id}/analytics"
echo "GET /api/v1/videos/{id}/stats/daily"
echo ""

echo "Video Comments:"
echo "GET /api/v1/videos/{videoId}/comments"
echo "POST /api/v1/videos/{videoId}/comments"
echo ""

echo "Video Ratings:"
echo "PUT /api/v1/videos/{id}/rating"
echo "GET /api/v1/videos/{id}/rating"
echo "DELETE /api/v1/videos/{id}/rating"
echo ""

echo "Video Watch Later:"
echo "POST /api/v1/videos/{id}/watch-later"
echo ""

echo "Video Captions:"
echo "GET /api/v1/videos/{id}/captions"
echo "POST /api/v1/videos/{id}/captions"
echo "GET /api/v1/videos/{id}/captions/{captionId}/content"
echo "PUT /api/v1/videos/{id}/captions/{captionId}"
echo "DELETE /api/v1/videos/{id}/captions/{captionId}"
echo ""

echo "HLS Streaming:"
echo "GET /api/v1/hls/*"
echo ""

echo "Video Imports:"
echo "POST /api/v1/videos/imports"
echo "GET /api/v1/videos/imports"
echo "GET /api/v1/videos/imports/{id}"
echo "DELETE /api/v1/videos/imports/{id}"
echo ""

echo "Chunked Uploads:"
echo "POST /api/v1/uploads/initiate"
echo "POST /api/v1/uploads/{sessionId}/chunks"
echo "POST /api/v1/uploads/{sessionId}/complete"
echo "GET /api/v1/uploads/{sessionId}/status"
echo "GET /api/v1/uploads/{sessionId}/resume"
echo ""

echo "Encoding:"
echo "GET /api/v1/encoding/status"
echo ""

echo "Users:"
echo "POST /api/v1/users"
echo "GET /api/v1/users/me"
echo "PUT /api/v1/users/me"
echo "POST /api/v1/users/me/avatar"
echo "GET /api/v1/users/{id}/videos"
echo "POST /api/v1/users/{id}/subscribe"
echo "DELETE /api/v1/users/{id}/subscribe"
echo "GET /api/v1/users/me/subscriptions"
echo "GET /api/v1/users/me/channels"
echo "GET /api/v1/users/me/ratings"
echo "GET /api/v1/users/me/watch-later"
echo ""

echo "Messages:"
echo "POST /api/v1/messages"
echo "GET /api/v1/messages"
echo "PUT /api/v1/messages/{messageId}/read"
echo "DELETE /api/v1/messages/{messageId}"
echo ""

echo "Conversations:"
echo "GET /api/v1/conversations"
echo "GET /api/v1/conversations/unread-count"
echo ""

echo "Trending & Fingerprinting:"
echo "GET /api/v1/trending"
echo "POST /api/v1/views/fingerprint"
echo ""

echo "Channels:"
echo "GET /api/v1/channels"
echo "GET /api/v1/channels/{id}"
echo "GET /api/v1/channels/{id}/videos"
echo "GET /api/v1/channels/{id}/subscribers"
echo "POST /api/v1/channels"
echo "PUT /api/v1/channels/{id}"
echo "DELETE /api/v1/channels/{id}"
echo "POST /api/v1/channels/{id}/subscribe"
echo "DELETE /api/v1/channels/{id}/subscribe"
echo ""

echo "Live Streams:"
echo "POST /api/v1/streams"
echo "GET /api/v1/streams/active"
echo "GET /api/v1/streams/channels/{channelId}"
echo "GET /api/v1/streams/{id}"
echo "PUT /api/v1/streams/{id}"
echo "POST /api/v1/streams/{id}/end"
echo "GET /api/v1/streams/{id}/stats"
echo "POST /api/v1/streams/{id}/rotate-key"
echo "GET /api/v1/streams/{id}/hls/master.m3u8"
echo "GET /api/v1/streams/{id}/hls/{variant}/index.m3u8"
echo "GET /api/v1/streams/{id}/hls/{variant}/{segment}"
echo "GET /api/v1/streams/{id}/hls-info"
echo ""

echo "Comments (Standalone):"
echo "GET /api/v1/comments/{commentId}"
echo "PUT /api/v1/comments/{commentId}"
echo "DELETE /api/v1/comments/{commentId}"
echo "POST /api/v1/comments/{commentId}/flag"
echo "DELETE /api/v1/comments/{commentId}/flag"
echo "POST /api/v1/comments/{commentId}/moderate"
echo ""

echo "Notifications:"
echo "GET /api/v1/notifications"
echo "GET /api/v1/notifications/unread-count"
echo "GET /api/v1/notifications/stats"
echo "PUT /api/v1/notifications/{id}/read"
echo "PUT /api/v1/notifications/read-all"
echo "DELETE /api/v1/notifications/{id}"
echo ""

echo "Payments (IOTA):"
echo "POST /api/v1/payments/wallet"
echo "GET /api/v1/payments/wallet"
echo "POST /api/v1/payments/intents"
echo "GET /api/v1/payments/intents/{id}"
echo "GET /api/v1/payments/transactions"
echo ""

echo "IPFS Metrics:"
echo "GET /api/v1/ipfs/metrics"
echo "GET /api/v1/ipfs/gateways"
echo ""

echo "Federation:"
echo "GET /api/v1/federation/timeline"
echo ""

echo "Playlists:"
echo "GET /api/v1/playlists"
echo "GET /api/v1/playlists/{id}"
echo "GET /api/v1/playlists/{id}/items"
echo "POST /api/v1/playlists"
echo "PUT /api/v1/playlists/{id}"
echo "DELETE /api/v1/playlists/{id}"
echo "POST /api/v1/playlists/{id}/items"
echo "DELETE /api/v1/playlists/{id}/items/{itemId}"
echo "PUT /api/v1/playlists/{id}/items/{itemId}/reorder"
echo ""

echo "Moderation:"
echo "POST /api/v1/abuse-reports"
echo ""

echo "Admin Moderation:"
echo "GET /api/v1/admin/abuse-reports"
echo "GET /api/v1/admin/abuse-reports/{id}"
echo "PUT /api/v1/admin/abuse-reports/{id}"
echo "DELETE /api/v1/admin/abuse-reports/{id}"
echo ""

echo "Admin Blocklist:"
echo "POST /api/v1/admin/blocklist"
echo "GET /api/v1/admin/blocklist"
echo "PUT /api/v1/admin/blocklist/{id}"
echo "DELETE /api/v1/admin/blocklist/{id}"
echo ""

echo "Admin Instance Config:"
echo "GET /api/v1/admin/instance/config"
echo "GET /api/v1/admin/instance/config/{key}"
echo "PUT /api/v1/admin/instance/config/{key}"
echo ""

echo "Admin Federation Jobs:"
echo "GET /api/v1/admin/federation/jobs"
echo "GET /api/v1/admin/federation/jobs/{id}"
echo "POST /api/v1/admin/federation/jobs/{id}/retry"
echo "DELETE /api/v1/admin/federation/jobs/{id}"
echo ""

echo "Admin Federation Actors:"
echo "GET /api/v1/admin/federation/actors"
echo "POST /api/v1/admin/federation/actors"
echo "PUT /api/v1/admin/federation/actors/{actor}"
echo "DELETE /api/v1/admin/federation/actors/{actor}"
echo ""

echo "Admin Federation Hardening:"
echo "GET /api/v1/admin/federation/hardening/dashboard"
echo "GET /api/v1/admin/federation/hardening/health"
echo "GET /api/v1/admin/federation/hardening/dlq"
echo "POST /api/v1/admin/federation/hardening/dlq/{id}/retry"
echo "GET /api/v1/admin/federation/hardening/blocklist/instances"
echo "POST /api/v1/admin/federation/hardening/blocklist/instances"
echo "DELETE /api/v1/admin/federation/hardening/blocklist/instances/{domain}"
echo "POST /api/v1/admin/federation/hardening/blocklist/actors"
echo "GET /api/v1/admin/federation/hardening/blocklist/check"
echo "GET /api/v1/admin/federation/hardening/abuse/reports"
echo "POST /api/v1/admin/federation/hardening/abuse/reports/{id}/resolve"
echo "POST /api/v1/admin/federation/hardening/cleanup"
echo ""

echo "Public Instance Info:"
echo "GET /api/v1/instance/about"
echo ""

echo "OEmbed:"
echo "GET /oembed"
echo ""

echo "ATProto DID:"
echo "GET /.well-known/atproto-did"
echo ""

echo "ActivityPub (if enabled):"
echo "GET /.well-known/webfinger"
echo "GET /.well-known/nodeinfo"
echo "GET /.well-known/host-meta"
echo "GET /nodeinfo/2.0"
echo "POST /inbox"
echo "GET /users/{username}"
echo "GET /users/{username}/outbox"
echo "GET /users/{username}/inbox"
echo "POST /users/{username}/inbox"
echo "GET /users/{username}/followers"
echo "GET /users/{username}/following"
echo ""

echo "=== DOCUMENTED ENDPOINTS (from OpenAPI specs) ==="
echo ""
echo "Extracting from all OpenAPI files..."
grep -h "^  /" /Users/yosefgamble/github/athena/api/*.yaml /Users/yosefgamble/github/athena/docs/openapi_notifications.yaml 2>/dev/null | sort -u
