package video

import (
	"net/http"

	"vidra-core/internal/httpapi/shared"
)

// VideoLicences maps PeerTube licence IDs to human-readable names.
// IDs match PeerTube's /api/v1/videos/licences response.
var VideoLicences = map[string]string{
	"1": "Attribution",
	"2": "Attribution - Share Alike",
	"3": "Attribution - No Derivatives",
	"4": "Attribution - Non Commercial",
	"5": "Attribution - Non Commercial - Share Alike",
	"6": "Attribution - Non Commercial - No Derivatives",
	"7": "Public Domain Dedication",
}

// VideoLanguages maps ISO 639-1 language codes to English names.
// Subset of languages PeerTube supports.
var VideoLanguages = map[string]string{
	"aa": "Afar",
	"ab": "Abkhazian",
	"af": "Afrikaans",
	"ak": "Akan",
	"sq": "Albanian",
	"am": "Amharic",
	"ar": "Arabic",
	"an": "Aragonese",
	"hy": "Armenian",
	"as": "Assamese",
	"av": "Avaric",
	"ae": "Avestan",
	"ay": "Aymara",
	"az": "Azerbaijani",
	"ba": "Bashkir",
	"bm": "Bambara",
	"eu": "Basque",
	"be": "Belarusian",
	"bn": "Bengali",
	"bh": "Bihari",
	"bi": "Bislama",
	"bs": "Bosnian",
	"br": "Breton",
	"bg": "Bulgarian",
	"my": "Burmese",
	"ca": "Catalan",
	"ch": "Chamorro",
	"ce": "Chechen",
	"zh": "Chinese",
	"cu": "Church Slavic",
	"cv": "Chuvash",
	"kw": "Cornish",
	"co": "Corsican",
	"cr": "Cree",
	"cs": "Czech",
	"da": "Danish",
	"dv": "Divehi",
	"nl": "Dutch",
	"dz": "Dzongkha",
	"en": "English",
	"eo": "Esperanto",
	"et": "Estonian",
	"ee": "Ewe",
	"fo": "Faroese",
	"fj": "Fijian",
	"fi": "Finnish",
	"fr": "French",
	"fy": "Western Frisian",
	"ff": "Fulah",
	"ka": "Georgian",
	"de": "German",
	"gd": "Gaelic",
	"ga": "Irish",
	"gl": "Galician",
	"gv": "Manx",
	"el": "Greek",
	"gn": "Guarani",
	"gu": "Gujarati",
	"ht": "Haitian Creole",
	"ha": "Hausa",
	"he": "Hebrew",
	"hz": "Herero",
	"hi": "Hindi",
	"ho": "Hiri Motu",
	"hr": "Croatian",
	"hu": "Hungarian",
	"ig": "Igbo",
	"is": "Icelandic",
	"io": "Ido",
	"ii": "Sichuan Yi",
	"iu": "Inuktitut",
	"ie": "Interlingue",
	"ia": "Interlingua",
	"id": "Indonesian",
	"ik": "Inupiaq",
	"it": "Italian",
	"jv": "Javanese",
	"ja": "Japanese",
	"kl": "Kalaallisut",
	"kn": "Kannada",
	"ks": "Kashmiri",
	"kr": "Kanuri",
	"kk": "Kazakh",
	"km": "Central Khmer",
	"ki": "Kikuyu",
	"rw": "Kinyarwanda",
	"ky": "Kirghiz",
	"kv": "Komi",
	"kg": "Kongo",
	"ko": "Korean",
	"kj": "Kuanyama",
	"ku": "Kurdish",
	"lo": "Lao",
	"la": "Latin",
	"lv": "Latvian",
	"li": "Limburgan",
	"ln": "Lingala",
	"lt": "Lithuanian",
	"lb": "Luxembourgish",
	"lu": "Luba-Katanga",
	"lg": "Ganda",
	"mk": "Macedonian",
	"mh": "Marshallese",
	"ml": "Malayalam",
	"mi": "Maori",
	"mr": "Marathi",
	"ms": "Malay",
	"mg": "Malagasy",
	"mt": "Maltese",
	"mn": "Mongolian",
	"na": "Nauru",
	"nv": "Navajo",
	"nr": "South Ndebele",
	"nd": "North Ndebele",
	"ng": "Ndonga",
	"ne": "Nepali",
	"nn": "Norwegian Nynorsk",
	"nb": "Bokmål, Norwegian",
	"no": "Norwegian",
	"ny": "Chichewa",
	"oc": "Occitan",
	"oj": "Ojibwa",
	"or": "Oriya",
	"om": "Oromo",
	"os": "Ossetian",
	"pa": "Panjabi",
	"fa": "Persian",
	"pi": "Pali",
	"pl": "Polish",
	"pt": "Portuguese",
	"ps": "Pushto",
	"qu": "Quechua",
	"rm": "Romansh",
	"ro": "Romanian",
	"rn": "Rundi",
	"ru": "Russian",
	"sg": "Sango",
	"sa": "Sanskrit",
	"si": "Sinhala",
	"sk": "Slovak",
	"sl": "Slovenian",
	"se": "Northern Sami",
	"sm": "Samoan",
	"sn": "Shona",
	"sd": "Sindhi",
	"so": "Somali",
	"st": "Sotho, Southern",
	"es": "Spanish",
	"sc": "Sardinian",
	"sr": "Serbian",
	"ss": "Swati",
	"su": "Sundanese",
	"sw": "Swahili",
	"sv": "Swedish",
	"ty": "Tahitian",
	"ta": "Tamil",
	"tt": "Tatar",
	"te": "Telugu",
	"tg": "Tajik",
	"tl": "Tagalog",
	"th": "Thai",
	"bo": "Tibetan",
	"ti": "Tigrinya",
	"to": "Tonga",
	"tn": "Tswana",
	"ts": "Tsonga",
	"tk": "Turkmen",
	"tr": "Turkish",
	"tw": "Twi",
	"ug": "Uighur",
	"uk": "Ukrainian",
	"ur": "Urdu",
	"uz": "Uzbek",
	"ve": "Venda",
	"vi": "Vietnamese",
	"vo": "Volapük",
	"wa": "Walloon",
	"cy": "Welsh",
	"wo": "Wolof",
	"xh": "Xhosa",
	"yi": "Yiddish",
	"yo": "Yoruba",
	"za": "Zhuang",
	"zu": "Zulu",
}

// VideoPrivacies maps PeerTube privacy IDs to human-readable names.
// IDs match PeerTube's /api/v1/videos/privacies response.
var VideoPrivacies = map[string]string{
	"1": "Public",
	"2": "Unlisted",
	"3": "Private",
	"4": "Internal",
}

// GetVideoLicences returns the list of available video licences.
func GetVideoLicences(w http.ResponseWriter, r *http.Request) {
	shared.WriteJSON(w, http.StatusOK, VideoLicences)
}

// GetVideoLanguages returns the list of available video languages.
func GetVideoLanguages(w http.ResponseWriter, r *http.Request) {
	shared.WriteJSON(w, http.StatusOK, VideoLanguages)
}

// GetVideoPrivacies returns the list of available video privacies.
func GetVideoPrivacies(w http.ResponseWriter, r *http.Request) {
	shared.WriteJSON(w, http.StatusOK, VideoPrivacies)
}
