// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: captions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteCaption = `-- name: DeleteCaption :execrows
DELETE FROM captions WHERE video_id = $1 AND language = $2
`

type DeleteCaptionParams struct {
	VideoID  uuid.UUID `json:"video_id"`
	Language string    `json:"language"`
}

// Remove a video's caption track for a language (idempotent).
func (q *Queries) DeleteCaption(ctx context.Context, arg DeleteCaptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCaption, arg.VideoID, arg.Language)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCaptionByLang = `-- name: GetCaptionByLang :one
SELECT id, video_id, language, label, storage_key, created_at, updated_at
FROM captions
WHERE video_id = $1 AND language = $2
`

type GetCaptionByLangParams struct {
	VideoID  uuid.UUID `json:"video_id"`
	Language string    `json:"language"`
}

func (q *Queries) GetCaptionByLang(ctx context.Context, arg GetCaptionByLangParams) (Caption, error) {
	row := q.db.QueryRow(ctx, getCaptionByLang, arg.VideoID, arg.Language)
	var i Caption
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Label,
		&i.StorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCaptionsByVideo = `-- name: ListCaptionsByVideo :many
SELECT id, video_id, language, label, storage_key, created_at, updated_at
FROM captions
WHERE video_id = $1
ORDER BY language
`

// A video's caption tracks, ordered by language.
func (q *Queries) ListCaptionsByVideo(ctx context.Context, videoID uuid.UUID) ([]Caption, error) {
	rows, err := q.db.Query(ctx, listCaptionsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Caption
	for rows.Next() {
		var i Caption
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Language,
			&i.Label,
			&i.StorageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCaption = `-- name: UpsertCaption :one
INSERT INTO captions (video_id, language, label, storage_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT (video_id, language) DO UPDATE
    SET label = EXCLUDED.label, storage_key = EXCLUDED.storage_key, updated_at = now()
RETURNING id, video_id, language, label, storage_key, created_at, updated_at
`

type UpsertCaptionParams struct {
	VideoID    uuid.UUID `json:"video_id"`
	Language   string    `json:"language"`
	Label      string    `json:"label"`
	StorageKey string    `json:"storage_key"`
}

// Add or replace a video's caption track for a language (re-uploading a language
// updates its label + storage key).
func (q *Queries) UpsertCaption(ctx context.Context, arg UpsertCaptionParams) (Caption, error) {
	row := q.db.QueryRow(ctx, upsertCaption,
		arg.VideoID,
		arg.Language,
		arg.Label,
		arg.StorageKey,
	)
	var i Caption
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Label,
		&i.StorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
