// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countChannelsByOwner = `-- name: CountChannelsByOwner :one
SELECT count(*) FROM channels WHERE owner_id = $1
`

func (q *Queries) CountChannelsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countManagedChannels = `-- name: CountManagedChannels :one
SELECT count(*)::bigint
FROM (
    SELECT c.id, c.owner_id, c.handle, c.display_name, c.description,
           c.created_at, c.updated_at, c.activitypub_enabled, c.atproto_enabled,
           'owner'::text AS role
    FROM channels c
    WHERE c.owner_id = $1

    UNION ALL

    SELECT c.id, c.owner_id, c.handle, c.display_name, c.description,
           c.created_at, c.updated_at, c.activitypub_enabled, c.atproto_enabled,
           cm.role
    FROM channel_members cm
    JOIN channels c ON c.id = cm.channel_id
    WHERE cm.user_id = $1
) managed
`

// How many rows ListManagedChannels would return, ignoring pagination.
func (q *Queries) CountManagedChannels(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countManagedChannels, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (owner_id, handle, display_name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, handle, display_name, description, created_at, updated_at, activitypub_enabled, atproto_enabled
`

type CreateChannelParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.OwnerID,
		arg.Handle,
		arg.DisplayName,
		arg.Description,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Handle,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitypubEnabled,
		&i.AtprotoEnabled,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannelByHandle = `-- name: GetChannelByHandle :one
SELECT id, owner_id, handle, display_name, description, created_at, updated_at, activitypub_enabled, atproto_enabled
FROM channels
WHERE lower(handle) = lower($1)
`

func (q *Queries) GetChannelByHandle(ctx context.Context, lower string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByHandle, lower)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Handle,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitypubEnabled,
		&i.AtprotoEnabled,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, owner_id, handle, display_name, description, created_at, updated_at, activitypub_enabled, atproto_enabled
FROM channels
WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Handle,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitypubEnabled,
		&i.AtprotoEnabled,
	)
	return i, err
}

const listChannelsByOwner = `-- name: ListChannelsByOwner :many
SELECT id, owner_id, handle, display_name, description, created_at, updated_at, activitypub_enabled, atproto_enabled
FROM channels
WHERE owner_id = $1
ORDER BY created_at
`

func (q *Queries) ListChannelsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Handle,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivitypubEnabled,
			&i.AtprotoEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedChannels = `-- name: ListManagedChannels :many
SELECT managed.id, managed.owner_id, managed.handle, managed.display_name, managed.description, managed.created_at, managed.updated_at, managed.activitypub_enabled, managed.atproto_enabled, managed.role,
       (SELECT count(*) FROM channel_follows cf WHERE cf.channel_id = managed.id)::bigint AS follower_count
FROM (
    SELECT c.id, c.owner_id, c.handle, c.display_name, c.description,
           c.created_at, c.updated_at, c.activitypub_enabled, c.atproto_enabled,
           'owner'::text AS role
    FROM channels c
    WHERE c.owner_id = $1

    UNION ALL

    SELECT c.id, c.owner_id, c.handle, c.display_name, c.description,
           c.created_at, c.updated_at, c.activitypub_enabled, c.atproto_enabled,
           cm.role
    FROM channel_members cm
    JOIN channels c ON c.id = cm.channel_id
    WHERE cm.user_id = $1
) managed
ORDER BY (managed.role = 'owner') DESC, managed.created_at, managed.id
LIMIT $3 OFFSET $2
`

type ListManagedChannelsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListManagedChannelsRow struct {
	ID                 uuid.UUID `json:"id"`
	OwnerID            uuid.UUID `json:"owner_id"`
	Handle             string    `json:"handle"`
	DisplayName        string    `json:"display_name"`
	Description        string    `json:"description"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ActivitypubEnabled bool      `json:"activitypub_enabled"`
	AtprotoEnabled     bool      `json:"atproto_enabled"`
	Role               string    `json:"role"`
	FollowerCount      int64     `json:"follower_count"`
}

// GET /me/channels: the channels a user OWNS plus the ones shared with them as
// an editor member (migration 0097), each tagged with the caller's role, owned
// first. This replaces a Go-side merge of ListChannelsByOwner and
// ListChannelsForMember, which could not be paginated and which then issued one
// CountChannelFollowers per row — an N+1 that grew with the user's channel
// count. The follower count comes back inline as one scalar subquery per row.
func (q *Queries) ListManagedChannels(ctx context.Context, arg ListManagedChannelsParams) ([]ListManagedChannelsRow, error) {
	rows, err := q.db.Query(ctx, listManagedChannels, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagedChannelsRow
	for rows.Next() {
		var i ListManagedChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Handle,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivitypubEnabled,
			&i.AtprotoEnabled,
			&i.Role,
			&i.FollowerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET display_name        = COALESCE($1, display_name),
    description         = COALESCE($2, description),
    activitypub_enabled = COALESCE($3, activitypub_enabled),
    atproto_enabled     = COALESCE($4, atproto_enabled),
    updated_at          = now()
WHERE id = $5
RETURNING id, owner_id, handle, display_name, description, created_at, updated_at, activitypub_enabled, atproto_enabled
`

type UpdateChannelParams struct {
	DisplayName        *string   `json:"display_name"`
	Description        *string   `json:"description"`
	ActivitypubEnabled *bool     `json:"activitypub_enabled"`
	AtprotoEnabled     *bool     `json:"atproto_enabled"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.DisplayName,
		arg.Description,
		arg.ActivitypubEnabled,
		arg.AtprotoEnabled,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Handle,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitypubEnabled,
		&i.AtprotoEnabled,
	)
	return i, err
}
