// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countComments = `-- name: CountComments :one
SELECT count(*) FROM comments WHERE user_id IS NOT NULL
`

// LOCAL comments only — the "local comments" count NodeInfo advertises.
// Federated (remote-authored) comments are excluded.
func (q *Queries) CountComments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countComments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (video_id, user_id, body, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, video_id, user_id, body, created_at, updated_at, parent_id,
          remote_actor_url, remote_author_name, remote_object_url
`

type CreateCommentParams struct {
	VideoID  uuid.UUID   `json:"video_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Body     string      `json:"body"`
	ParentID pgtype.UUID `json:"parent_id"`
}

// parent_id is NULL for a top-level comment, or the id of the comment being
// replied to (the service validates it references a comment on the same video).
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.VideoID,
		arg.UserID,
		arg.Body,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.RemoteActorUrl,
		&i.RemoteAuthorName,
		&i.RemoteObjectUrl,
	)
	return i, err
}

const createRemoteComment = `-- name: CreateRemoteComment :one
INSERT INTO comments (video_id, body, parent_id, remote_actor_url, remote_author_name, remote_object_url)
VALUES ($1, $2, $3,
        $4, $5, $6)
ON CONFLICT (remote_object_url) DO UPDATE
    SET body = EXCLUDED.body, updated_at = now()
RETURNING id, video_id, user_id, body, created_at, updated_at, parent_id,
          remote_actor_url, remote_author_name, remote_object_url
`

type CreateRemoteCommentParams struct {
	VideoID          uuid.UUID   `json:"video_id"`
	Body             string      `json:"body"`
	ParentID         pgtype.UUID `json:"parent_id"`
	RemoteActorUrl   *string     `json:"remote_actor_url"`
	RemoteAuthorName *string     `json:"remote_author_name"`
	RemoteObjectUrl  *string     `json:"remote_object_url"`
}

// Store an inbound federated Note as a comment (remote-content §6): attributed
// to a remote actor (with a display-name snapshot) instead of a local user.
// Idempotent by the Note's ActivityPub object id — a re-delivered or updated
// Note refreshes the body.
func (q *Queries) CreateRemoteComment(ctx context.Context, arg CreateRemoteCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createRemoteComment,
		arg.VideoID,
		arg.Body,
		arg.ParentID,
		arg.RemoteActorUrl,
		arg.RemoteAuthorName,
		arg.RemoteObjectUrl,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.RemoteActorUrl,
		&i.RemoteAuthorName,
		&i.RemoteObjectUrl,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, video_id, user_id, body, created_at, updated_at, parent_id,
       remote_actor_url, remote_author_name, remote_object_url
FROM comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.RemoteActorUrl,
		&i.RemoteAuthorName,
		&i.RemoteObjectUrl,
	)
	return i, err
}

const getCommentByRemoteObjectURL = `-- name: GetCommentByRemoteObjectURL :one
SELECT id, video_id, user_id, body, created_at, updated_at, parent_id,
       remote_actor_url, remote_author_name, remote_object_url
FROM comments
WHERE remote_object_url = $1::text
`

// Look a federated comment up by its Note's ActivityPub object id — the key
// inbound Update{Note}/Delete use (§6/§7). Local comments never match (their
// remote_object_url is NULL).
func (q *Queries) GetCommentByRemoteObjectURL(ctx context.Context, remoteObjectUrl string) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByRemoteObjectURL, remoteObjectUrl)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.RemoteActorUrl,
		&i.RemoteAuthorName,
		&i.RemoteObjectUrl,
	)
	return i, err
}

const listAdminComments = `-- name: ListAdminComments :many
SELECT c.id, c.video_id, c.body, c.created_at,
       COALESCE(u.username, '')::text AS author_username,
       COALESCE(u.display_name, '')::text AS author_display_name,
       c.remote_actor_url,
       COALESCE(c.remote_author_name, '')::text AS remote_author_name,
       COALESCE(ra.domain, '')::text AS author_domain,
       v.title AS video_title
FROM comments c
LEFT JOIN users u ON u.id = c.user_id
LEFT JOIN remote_actors ra ON ra.actor_url = c.remote_actor_url
JOIN videos v ON v.id = c.video_id
WHERE ($1::text IS NULL OR c.body ILIKE '%' || $1 || '%')
ORDER BY c.created_at DESC, c.id DESC
LIMIT $3 OFFSET $2
`

type ListAdminCommentsParams struct {
	Query        *string `json:"query"`
	ResultOffset int32   `json:"result_offset"`
	ResultLimit  int32   `json:"result_limit"`
}

type ListAdminCommentsRow struct {
	ID                uuid.UUID `json:"id"`
	VideoID           uuid.UUID `json:"video_id"`
	Body              string    `json:"body"`
	CreatedAt         time.Time `json:"created_at"`
	AuthorUsername    string    `json:"author_username"`
	AuthorDisplayName string    `json:"author_display_name"`
	RemoteActorUrl    *string   `json:"remote_actor_url"`
	RemoteAuthorName  string    `json:"remote_author_name"`
	AuthorDomain      string    `json:"author_domain"`
	VideoTitle        string    `json:"video_title"`
}

// The admin/moderator comments overview: ALL comments newest first, with the
// author's identity (local user or remote actor + domain, §6) and the video
// they're on. An optional case-insensitive body filter (NULL = no filter).
func (q *Queries) ListAdminComments(ctx context.Context, arg ListAdminCommentsParams) ([]ListAdminCommentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminComments, arg.Query, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminCommentsRow
	for rows.Next() {
		var i ListAdminCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.RemoteActorUrl,
			&i.RemoteAuthorName,
			&i.AuthorDomain,
			&i.VideoTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByVideo = `-- name: ListCommentsByVideo :many
SELECT c.id, c.video_id, c.user_id, c.body, c.parent_id, c.created_at, c.updated_at,
       COALESCE(u.username, '')::text AS author_username,
       COALESCE(u.display_name, '')::text AS author_display_name,
       c.remote_actor_url,
       COALESCE(c.remote_author_name, '')::text AS remote_author_name,
       COALESCE(ra.domain, '')::text AS author_domain
FROM comments c
LEFT JOIN users u ON u.id = c.user_id
LEFT JOIN remote_actors ra ON ra.actor_url = c.remote_actor_url
WHERE c.video_id = $1
  AND NOT EXISTS (
      SELECT 1 FROM muted_accounts m
      WHERE m.muter_id = $2 AND m.muted_id = c.user_id
  )
  AND NOT EXISTS (
      SELECT 1 FROM user_blocks ub
      WHERE ub.blocker_id = $2 AND ub.blocked_id = c.user_id
  )
  AND NOT EXISTS (
      SELECT 1 FROM blocked_instances bi WHERE bi.domain = ra.domain
  )
  AND NOT EXISTS (
      SELECT 1 FROM muted_instances mi
      WHERE mi.muter_id = $2 AND mi.domain = ra.domain
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $4 OFFSET $3
`

type ListCommentsByVideoParams struct {
	VideoID      uuid.UUID   `json:"video_id"`
	ViewerID     pgtype.UUID `json:"viewer_id"`
	ResultOffset int32       `json:"result_offset"`
	ResultLimit  int32       `json:"result_limit"`
}

type ListCommentsByVideoRow struct {
	ID                uuid.UUID   `json:"id"`
	VideoID           uuid.UUID   `json:"video_id"`
	UserID            pgtype.UUID `json:"user_id"`
	Body              string      `json:"body"`
	ParentID          pgtype.UUID `json:"parent_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	AuthorUsername    string      `json:"author_username"`
	AuthorDisplayName string      `json:"author_display_name"`
	RemoteActorUrl    *string     `json:"remote_actor_url"`
	RemoteAuthorName  string      `json:"remote_author_name"`
	AuthorDomain      string      `json:"author_domain"`
}

// A video's comments, newest first, joined with author identity for display.
// A comment is authored by a local user OR a remote actor (§6): the users join
// is LEFT and remote rows carry remote_author_name + the origin domain. When
// viewer_id is provided (an authenticated viewer), comments authored by an
// account that viewer has muted OR blocked are hidden (§13), and remote
// comments from instances that viewer muted are hidden too (§8); when NULL
// (anonymous), only the admin instance blocklist filters (it hides for
// everyone).
func (q *Queries) ListCommentsByVideo(ctx context.Context, arg ListCommentsByVideoParams) ([]ListCommentsByVideoRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByVideo,
		arg.VideoID,
		arg.ViewerID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByVideoRow
	for rows.Next() {
		var i ListCommentsByVideoRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.UserID,
			&i.Body,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.RemoteActorUrl,
			&i.RemoteAuthorName,
			&i.AuthorDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET body = $1, updated_at = now()
WHERE id = $2
RETURNING id, video_id, user_id, body, created_at, updated_at, parent_id,
          remote_actor_url, remote_author_name, remote_object_url
`

type UpdateCommentParams struct {
	Body string    `json:"body"`
	ID   uuid.UUID `json:"id"`
}

// Edit a comment's body (author-only; enforced in the service). Bumps updated_at
// so clients can show an "edited" marker (updated_at > created_at).
func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.Body, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.RemoteActorUrl,
		&i.RemoteAuthorName,
		&i.RemoteObjectUrl,
	)
	return i, err
}
