// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: donation_addresses.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDonationAddress = `-- name: CreateDonationAddress :one
INSERT INTO donation_addresses (owner_id, channel_id, network, address, label)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, channel_id, network, address, label, verified,
    verification_nonce, verification_expires_at, created_at
`

type CreateDonationAddressParams struct {
	OwnerID   uuid.UUID   `json:"owner_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	Network   string      `json:"network"`
	Address   string      `json:"address"`
	Label     string      `json:"label"`
}

func (q *Queries) CreateDonationAddress(ctx context.Context, arg CreateDonationAddressParams) (DonationAddress, error) {
	row := q.db.QueryRow(ctx, createDonationAddress,
		arg.OwnerID,
		arg.ChannelID,
		arg.Network,
		arg.Address,
		arg.Label,
	)
	var i DonationAddress
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChannelID,
		&i.Network,
		&i.Address,
		&i.Label,
		&i.Verified,
		&i.VerificationNonce,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDonationAddress = `-- name: DeleteDonationAddress :exec
DELETE FROM donation_addresses WHERE id = $1
`

func (q *Queries) DeleteDonationAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDonationAddress, id)
	return err
}

const getDonationAddress = `-- name: GetDonationAddress :one
SELECT id, owner_id, channel_id, network, address, label, verified,
    verification_nonce, verification_expires_at, created_at
FROM donation_addresses
WHERE id = $1
`

func (q *Queries) GetDonationAddress(ctx context.Context, id uuid.UUID) (DonationAddress, error) {
	row := q.db.QueryRow(ctx, getDonationAddress, id)
	var i DonationAddress
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChannelID,
		&i.Network,
		&i.Address,
		&i.Label,
		&i.Verified,
		&i.VerificationNonce,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountDonationAddresses = `-- name: ListAccountDonationAddresses :many
SELECT id, owner_id, channel_id, network, address, label, verified,
    verification_nonce, verification_expires_at, created_at
FROM donation_addresses
WHERE owner_id = $1 AND channel_id IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListAccountDonationAddresses(ctx context.Context, ownerID uuid.UUID) ([]DonationAddress, error) {
	rows, err := q.db.Query(ctx, listAccountDonationAddresses, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DonationAddress
	for rows.Next() {
		var i DonationAddress
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ChannelID,
			&i.Network,
			&i.Address,
			&i.Label,
			&i.Verified,
			&i.VerificationNonce,
			&i.VerificationExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelDonationAddresses = `-- name: ListChannelDonationAddresses :many
SELECT id, owner_id, channel_id, network, address, label, verified,
    verification_nonce, verification_expires_at, created_at
FROM donation_addresses
WHERE channel_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListChannelDonationAddresses(ctx context.Context, channelID pgtype.UUID) ([]DonationAddress, error) {
	rows, err := q.db.Query(ctx, listChannelDonationAddresses, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DonationAddress
	for rows.Next() {
		var i DonationAddress
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ChannelID,
			&i.Network,
			&i.Address,
			&i.Label,
			&i.Verified,
			&i.VerificationNonce,
			&i.VerificationExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonationAddressesByOwner = `-- name: ListDonationAddressesByOwner :many
SELECT id, owner_id, channel_id, network, address, label, verified,
    verification_nonce, verification_expires_at, created_at
FROM donation_addresses
WHERE owner_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListDonationAddressesByOwner(ctx context.Context, ownerID uuid.UUID) ([]DonationAddress, error) {
	rows, err := q.db.Query(ctx, listDonationAddressesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DonationAddress
	for rows.Next() {
		var i DonationAddress
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ChannelID,
			&i.Network,
			&i.Address,
			&i.Label,
			&i.Verified,
			&i.VerificationNonce,
			&i.VerificationExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDonationAddressVerified = `-- name: MarkDonationAddressVerified :one
UPDATE donation_addresses
SET verified = TRUE,
    verification_nonce = NULL,
    verification_expires_at = NULL
WHERE id = $1
RETURNING id, owner_id, channel_id, network, address, label, verified,
    verification_nonce, verification_expires_at, created_at
`

func (q *Queries) MarkDonationAddressVerified(ctx context.Context, id uuid.UUID) (DonationAddress, error) {
	row := q.db.QueryRow(ctx, markDonationAddressVerified, id)
	var i DonationAddress
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChannelID,
		&i.Network,
		&i.Address,
		&i.Label,
		&i.Verified,
		&i.VerificationNonce,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const setDonationAddressChallenge = `-- name: SetDonationAddressChallenge :one
UPDATE donation_addresses
SET verification_nonce = $1,
    verification_expires_at = $2
WHERE id = $3
RETURNING id, owner_id, channel_id, network, address, label, verified,
    verification_nonce, verification_expires_at, created_at
`

type SetDonationAddressChallengeParams struct {
	VerificationNonce     *string            `json:"verification_nonce"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
	ID                    uuid.UUID          `json:"id"`
}

func (q *Queries) SetDonationAddressChallenge(ctx context.Context, arg SetDonationAddressChallengeParams) (DonationAddress, error) {
	row := q.db.QueryRow(ctx, setDonationAddressChallenge, arg.VerificationNonce, arg.VerificationExpiresAt, arg.ID)
	var i DonationAddress
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChannelID,
		&i.Network,
		&i.Address,
		&i.Label,
		&i.Verified,
		&i.VerificationNonce,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
