// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: federation_inbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countRemoteFollowers = `-- name: CountRemoteFollowers :one
SELECT count(*) FROM remote_follows WHERE channel_id = $1 AND state = 'accepted'
`

func (q *Queries) CountRemoteFollowers(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRemoteFollowers, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertRemoteFollow = `-- name: InsertRemoteFollow :exec
INSERT INTO remote_follows (channel_id, remote_actor_url, state, follow_activity_url)
VALUES ($1, $2, 'accepted', $3)
ON CONFLICT (channel_id, remote_actor_url)
DO UPDATE SET state = 'accepted', follow_activity_url = EXCLUDED.follow_activity_url
`

type InsertRemoteFollowParams struct {
	ChannelID         uuid.UUID `json:"channel_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	FollowActivityUrl string    `json:"follow_activity_url"`
}

// A remote actor follows a local channel. Channels are open → auto-accepted.
func (q *Queries) InsertRemoteFollow(ctx context.Context, arg InsertRemoteFollowParams) error {
	_, err := q.db.Exec(ctx, insertRemoteFollow, arg.ChannelID, arg.RemoteActorUrl, arg.FollowActivityUrl)
	return err
}

const isActivityProcessed = `-- name: IsActivityProcessed :one

SELECT EXISTS (SELECT 1 FROM federation_inbox_activities WHERE activity_id = $1)
`

// Inbound federation persistence (migration 0037, .ralph/specs/federation.md §6,8).
func (q *Queries) IsActivityProcessed(ctx context.Context, activityID string) (bool, error) {
	row := q.db.QueryRow(ctx, isActivityProcessed, activityID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markActivityProcessed = `-- name: MarkActivityProcessed :exec
INSERT INTO federation_inbox_activities (activity_id)
VALUES ($1)
ON CONFLICT (activity_id) DO NOTHING
`

func (q *Queries) MarkActivityProcessed(ctx context.Context, activityID string) error {
	_, err := q.db.Exec(ctx, markActivityProcessed, activityID)
	return err
}
