// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countChannelFollowers = `-- name: CountChannelFollowers :one
SELECT count(*) FROM channel_follows WHERE channel_id = $1
`

func (q *Queries) CountChannelFollowers(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelFollowers, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowersByOwner = `-- name: CountFollowersByOwner :many
SELECT c.id AS channel_id, count(cf.follower_id)::bigint AS followers
FROM channels c
LEFT JOIN channel_follows cf ON cf.channel_id = c.id
WHERE c.owner_id = $1
GROUP BY c.id
`

type CountFollowersByOwnerRow struct {
	ChannelID uuid.UUID `json:"channel_id"`
	Followers int64     `json:"followers"`
}

// Follower count for every channel a user owns, in one grouped query — the
// channel-domain half of the account stats rollup (GET /me/stats). Channels
// with no followers appear with 0 via the LEFT JOIN.
func (q *Queries) CountFollowersByOwner(ctx context.Context, ownerID uuid.UUID) ([]CountFollowersByOwnerRow, error) {
	rows, err := q.db.Query(ctx, countFollowersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFollowersByOwnerRow
	for rows.Next() {
		var i CountFollowersByOwnerRow
		if err := rows.Scan(&i.ChannelID, &i.Followers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const followChannel = `-- name: FollowChannel :execrows
INSERT INTO channel_follows (follower_id, channel_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, channel_id) DO NOTHING
`

type FollowChannelParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	ChannelID  uuid.UUID `json:"channel_id"`
}

// Idempotent follow. Returns the number of rows inserted (1 = a new follow, 0 =
// already following) so callers can fire a notification only on a new follow.
func (q *Queries) FollowChannel(ctx context.Context, arg FollowChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, followChannel, arg.FollowerID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFollowNotificationSetting = `-- name: GetFollowNotificationSetting :one
SELECT notification_setting FROM channel_follows
WHERE follower_id = $1 AND channel_id = $2
`

type GetFollowNotificationSettingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	ChannelID  uuid.UUID `json:"channel_id"`
}

// The caller's bell mode for one channel (migration 0101). NO ROW means the
// caller does not follow the channel at all — callers distinguish that from a
// muted bell ('none').
func (q *Queries) GetFollowNotificationSetting(ctx context.Context, arg GetFollowNotificationSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getFollowNotificationSetting, arg.FollowerID, arg.ChannelID)
	var notification_setting string
	err := row.Scan(&notification_setting)
	return notification_setting, err
}

const isFollowingChannel = `-- name: IsFollowingChannel :one
SELECT EXISTS (
    SELECT 1 FROM channel_follows
    WHERE follower_id = $1 AND channel_id = $2
)
`

type IsFollowingChannelParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	ChannelID  uuid.UUID `json:"channel_id"`
}

func (q *Queries) IsFollowingChannel(ctx context.Context, arg IsFollowingChannelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingChannel, arg.FollowerID, arg.ChannelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowedChannels = `-- name: ListFollowedChannels :many
SELECT
    c.id, c.owner_id, c.handle, c.display_name, c.description,
    c.created_at, c.updated_at, c.activitypub_enabled, c.atproto_enabled,
    (SELECT count(*) FROM channel_follows cf2 WHERE cf2.channel_id = c.id) AS follower_count,
    cf.created_at AS followed_at, cf.notification_setting
FROM channel_follows cf
JOIN channels c ON c.id = cf.channel_id
WHERE cf.follower_id = $1
ORDER BY cf.created_at DESC, c.id
LIMIT $2 OFFSET $3
`

type ListFollowedChannelsParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListFollowedChannelsRow struct {
	ID                  uuid.UUID `json:"id"`
	OwnerID             uuid.UUID `json:"owner_id"`
	Handle              string    `json:"handle"`
	DisplayName         string    `json:"display_name"`
	Description         string    `json:"description"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	ActivitypubEnabled  bool      `json:"activitypub_enabled"`
	AtprotoEnabled      bool      `json:"atproto_enabled"`
	FollowerCount       int64     `json:"follower_count"`
	FollowedAt          time.Time `json:"followed_at"`
	NotificationSetting string    `json:"notification_setting"`
}

// The LOCAL channels the caller follows (the "FOLLOWING" list), most recently
// followed first. follower_count is each channel's total follower count,
// followed_at is when the caller followed it, and notification_setting is the
// caller's bell for that channel (migration 0101) so the list can render its
// state without an extra request per row. Paginated via limit/offset.
func (q *Queries) ListFollowedChannels(ctx context.Context, arg ListFollowedChannelsParams) ([]ListFollowedChannelsRow, error) {
	rows, err := q.db.Query(ctx, listFollowedChannels, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowedChannelsRow
	for rows.Next() {
		var i ListFollowedChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Handle,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivitypubEnabled,
			&i.AtprotoEnabled,
			&i.FollowerCount,
			&i.FollowedAt,
			&i.NotificationSetting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFollowNotificationSetting = `-- name: SetFollowNotificationSetting :execrows
UPDATE channel_follows
SET notification_setting = $1
WHERE follower_id = $2 AND channel_id = $3
`

type SetFollowNotificationSettingParams struct {
	NotificationSetting string    `json:"notification_setting"`
	FollowerID          uuid.UUID `json:"follower_id"`
	ChannelID           uuid.UUID `json:"channel_id"`
}

// Set the bell mode on an EXISTING follow. Returns the number of rows updated so
// the caller can refuse (404) a bell set on a channel the caller does not follow
// — the bell is a property of a subscription, never a standalone preference.
func (q *Queries) SetFollowNotificationSetting(ctx context.Context, arg SetFollowNotificationSettingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFollowNotificationSetting, arg.NotificationSetting, arg.FollowerID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollowChannel = `-- name: UnfollowChannel :exec
DELETE FROM channel_follows
WHERE follower_id = $1 AND channel_id = $2
`

type UnfollowChannelParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	ChannelID  uuid.UUID `json:"channel_id"`
}

func (q *Queries) UnfollowChannel(ctx context.Context, arg UnfollowChannelParams) error {
	_, err := q.db.Exec(ctx, unfollowChannel, arg.FollowerID, arg.ChannelID)
	return err
}
