// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInstanceSetting = `-- name: DeleteInstanceSetting :execrows
DELETE FROM instance_settings WHERE key = $1
`

// Remove one instance setting override, resetting the key to its config
// default. Returns the number of rows removed (0 when the key was not overridden).
func (q *Queries) DeleteInstanceSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstanceSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstanceSetting = `-- name: GetInstanceSetting :one
SELECT key, value, updated_by, updated_at
FROM instance_settings
WHERE key = $1
`

// One stored override by key, or no rows when the key is not overridden. The
// settings service reads the whole set into its cache; this is for a writer
// OUTSIDE the request path (the PeerTube import) that has to see the row as it
// stands in the database rather than as some process cached it.
func (q *Queries) GetInstanceSetting(ctx context.Context, key string) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, getInstanceSetting, key)
	var i InstanceSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstanceSettings = `-- name: ListInstanceSettings :many
SELECT key, value, updated_by, updated_at
FROM instance_settings
ORDER BY key
`

// Every stored instance-setting override, ordered by key. The settings service
// loads these at boot and after each write to build its in-memory cache; keys
// with no row fall back to the config default.
func (q *Queries) ListInstanceSettings(ctx context.Context) ([]InstanceSetting, error) {
	rows, err := q.db.Query(ctx, listInstanceSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceSetting
	for rows.Next() {
		var i InstanceSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstanceSetting = `-- name: UpsertInstanceSetting :exec
INSERT INTO instance_settings (key, value, updated_by, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = now()
`

type UpsertInstanceSettingParams struct {
	Key       string      `json:"key"`
	Value     string      `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

// Set one instance setting override (insert or update), stamping the writing
// admin and the update time.
func (q *Queries) UpsertInstanceSetting(ctx context.Context, arg UpsertInstanceSettingParams) error {
	_, err := q.db.Exec(ctx, upsertInstanceSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
