// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ipfs_gateway.sql

package sqlcgen

import (
	"context"
)

const listPublicIPFSRootPins = `-- name: ListPublicIPFSRootPins :many
SELECT object_key, media_class, cid, car_root, byte_size, state, attempts, next_attempt_at, last_error, video_id, owner_user_id, created_at, updated_at, network, target_network FROM media_ipfs_pins
WHERE cid = $1 AND network = 'public' AND state = 'pinned'
ORDER BY object_key LIMIT 129
`

// A CID shared by several objects stays available when any current public
// reference is eligible. Return one extra row so the caller detects truncation.
func (q *Queries) ListPublicIPFSRootPins(ctx context.Context, cid string) ([]MediaIpfsPin, error) {
	rows, err := q.db.Query(ctx, listPublicIPFSRootPins, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaIpfsPin
	for rows.Next() {
		var i MediaIpfsPin
		if err := rows.Scan(
			&i.ObjectKey,
			&i.MediaClass,
			&i.Cid,
			&i.CarRoot,
			&i.ByteSize,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.VideoID,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
			&i.TargetNetwork,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
