// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ipfs_copy_cleanup.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginIPFSCopyCleanup = `-- name: BeginIPFSCopyCleanup :one
UPDATE ipfs_capacity
SET maintenance_token = $1, maintenance_until = now() + interval '12 minutes',
    maintenance_host_sequence = $2, maintenance_config_revision = $3
WHERE singleton AND active_claims = 0 AND cleanup_pending > 0 AND maintenance_token IS NULL
RETURNING singleton, reserved_bytes, active_claims, measure_after, cleanup_pending, maintenance_token, maintenance_until, maintenance_host_sequence, maintenance_config_revision
`

type BeginIPFSCopyCleanupParams struct {
	MaintenanceToken pgtype.UUID `json:"maintenance_token"`
	HostSequence     int64       `json:"host_sequence"`
	ConfigRevision   int64       `json:"config_revision"`
}

func (q *Queries) BeginIPFSCopyCleanup(ctx context.Context, arg BeginIPFSCopyCleanupParams) (IpfsCapacity, error) {
	row := q.db.QueryRow(ctx, beginIPFSCopyCleanup, arg.MaintenanceToken, arg.HostSequence, arg.ConfigRevision)
	var i IpfsCapacity
	err := row.Scan(
		&i.Singleton,
		&i.ReservedBytes,
		&i.ActiveClaims,
		&i.MeasureAfter,
		&i.CleanupPending,
		&i.MaintenanceToken,
		&i.MaintenanceUntil,
		&i.MaintenanceHostSequence,
		&i.MaintenanceConfigRevision,
	)
	return i, err
}

const finishIPFSCopyCleanup = `-- name: FinishIPFSCopyCleanup :execrows
WITH locked AS MATERIALIZED (
    SELECT singleton FROM ipfs_capacity cap WHERE cap.singleton
      AND cap.maintenance_token = $1 FOR UPDATE
), removed AS (
    DELETE FROM ipfs_copy_cleanup
    WHERE claim_token = $2 AND cid = $3
      AND EXISTS (SELECT 1 FROM locked)
    RETURNING cid
)
UPDATE ipfs_capacity b
SET cleanup_pending = b.cleanup_pending - (SELECT count(*) FROM removed),
    maintenance_token = NULL, maintenance_until = NULL, measure_after = now()
WHERE b.singleton AND b.maintenance_token = $1
  AND EXISTS (SELECT 1 FROM removed)
`

type FinishIPFSCopyCleanupParams struct {
	MaintenanceToken pgtype.UUID `json:"maintenance_token"`
	ClaimToken       uuid.UUID   `json:"claim_token"`
	Cid              string      `json:"cid"`
}

func (q *Queries) FinishIPFSCopyCleanup(ctx context.Context, arg FinishIPFSCopyCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishIPFSCopyCleanup, arg.MaintenanceToken, arg.ClaimToken, arg.Cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const iPFSReturnedRootReferenced = `-- name: IPFSReturnedRootReferenced :one
SELECT EXISTS (SELECT 1 FROM media_ipfs_pins WHERE network = 'public'
    AND (cid = $1 OR car_root = $1) AND state IN ('pending', 'pinned', 'unpinning'))::boolean
`

// A live ledger row owns withdrawal. Sharing also protects a newer claim for
// the same object; object_key inequality would mistakenly unpin that new root.
func (q *Queries) IPFSReturnedRootReferenced(ctx context.Context, cid string) (bool, error) {
	row := q.db.QueryRow(ctx, iPFSReturnedRootReferenced, cid)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const nextIPFSCopyCleanup = `-- name: NextIPFSCopyCleanup :one
SELECT claim_token, cid, object_key, created_at FROM ipfs_copy_cleanup ORDER BY created_at, claim_token, cid LIMIT 1
`

func (q *Queries) NextIPFSCopyCleanup(ctx context.Context) (IpfsCopyCleanup, error) {
	row := q.db.QueryRow(ctx, nextIPFSCopyCleanup)
	var i IpfsCopyCleanup
	err := row.Scan(
		&i.ClaimToken,
		&i.Cid,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const recordIPFSReturnedCopy = `-- name: RecordIPFSReturnedCopy :exec
WITH recorded AS (
    INSERT INTO ipfs_copy_cleanup(claim_token, cid, object_key)
    VALUES($1, $2, $3)
    ON CONFLICT DO NOTHING RETURNING cid
)
INSERT INTO ipfs_capacity(cleanup_pending)
SELECT count(*) FROM recorded HAVING count(*) > 0
ON CONFLICT (singleton) DO UPDATE
SET cleanup_pending = ipfs_capacity.cleanup_pending + EXCLUDED.cleanup_pending
`

type RecordIPFSReturnedCopyParams struct {
	ClaimToken uuid.UUID `json:"claim_token"`
	Cid        string    `json:"cid"`
	ObjectKey  string    `json:"object_key"`
}

// The counter shares admission's UPDATE lock: a cross-table NOT EXISTS alone
// can admit a copy from an older READ COMMITTED statement snapshot.
func (q *Queries) RecordIPFSReturnedCopy(ctx context.Context, arg RecordIPFSReturnedCopyParams) error {
	_, err := q.db.Exec(ctx, recordIPFSReturnedCopy, arg.ClaimToken, arg.Cid, arg.ObjectKey)
	return err
}

const recoverIPFSCopyCleanup = `-- name: RecoverIPFSCopyCleanup :execrows
UPDATE ipfs_capacity SET maintenance_token = NULL, maintenance_until = NULL, measure_after = now()
WHERE singleton AND maintenance_token = $1 AND maintenance_until <= now()
`

// Only called after a later confirmed node restart. Lease expiry by itself
// cannot prove that an interrupted unpin/GC request has stopped on the server.
func (q *Queries) RecoverIPFSCopyCleanup(ctx context.Context, maintenanceToken pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, recoverIPFSCopyCleanup, maintenanceToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
