// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ipfs_control.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureIPFSControlConfig = `-- name: EnsureIPFSControlConfig :one
INSERT INTO ipfs_control_config (config) VALUES ($1)
ON CONFLICT (singleton) DO UPDATE SET singleton = true
RETURNING singleton, revision, config, policy_active, updated_by, updated_at
`

func (q *Queries) EnsureIPFSControlConfig(ctx context.Context, config []byte) (IpfsControlConfig, error) {
	row := q.db.QueryRow(ctx, ensureIPFSControlConfig, config)
	var i IpfsControlConfig
	err := row.Scan(
		&i.Singleton,
		&i.Revision,
		&i.Config,
		&i.PolicyActive,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getIPFSControlConfig = `-- name: GetIPFSControlConfig :one
SELECT singleton, revision, config, policy_active, updated_by, updated_at FROM ipfs_control_config WHERE singleton
`

func (q *Queries) GetIPFSControlConfig(ctx context.Context) (IpfsControlConfig, error) {
	row := q.db.QueryRow(ctx, getIPFSControlConfig)
	var i IpfsControlConfig
	err := row.Scan(
		&i.Singleton,
		&i.Revision,
		&i.Config,
		&i.PolicyActive,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getIPFSControlOperation = `-- name: GetIPFSControlOperation :one
SELECT id, sequence, config_revision, action, config, state, last_error_code, attempts, next_attempt_at, requested_by, created_at, updated_at FROM ipfs_control_operations WHERE id = $1
`

func (q *Queries) GetIPFSControlOperation(ctx context.Context, id uuid.UUID) (IpfsControlOperation, error) {
	row := q.db.QueryRow(ctx, getIPFSControlOperation, id)
	var i IpfsControlOperation
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ConfigRevision,
		&i.Action,
		&i.Config,
		&i.State,
		&i.LastErrorCode,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestIPFSControlOperation = `-- name: LatestIPFSControlOperation :one
SELECT id, sequence, config_revision, action, config, state, last_error_code, attempts, next_attempt_at, requested_by, created_at, updated_at FROM ipfs_control_operations ORDER BY sequence DESC LIMIT 1
`

func (q *Queries) LatestIPFSControlOperation(ctx context.Context) (IpfsControlOperation, error) {
	row := q.db.QueryRow(ctx, latestIPFSControlOperation)
	var i IpfsControlOperation
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ConfigRevision,
		&i.Action,
		&i.Config,
		&i.State,
		&i.LastErrorCode,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextIPFSControlOperation = `-- name: NextIPFSControlOperation :one
SELECT id, sequence, config_revision, action, config, state, last_error_code, attempts, next_attempt_at, requested_by, created_at, updated_at FROM ipfs_control_operations WHERE state IN ('pending', 'running')
ORDER BY sequence LIMIT 1
`

// Never skip an older running operation and let a newer sequence race ahead.
func (q *Queries) NextIPFSControlOperation(ctx context.Context) (IpfsControlOperation, error) {
	row := q.db.QueryRow(ctx, nextIPFSControlOperation)
	var i IpfsControlOperation
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ConfigRevision,
		&i.Action,
		&i.Config,
		&i.State,
		&i.LastErrorCode,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const observeIPFSControlOperation = `-- name: ObserveIPFSControlOperation :execrows
UPDATE ipfs_control_operations
SET state = $1, last_error_code = $2,
    attempts = attempts + 1, next_attempt_at = now() + interval '5 seconds', updated_at = now()
WHERE id = $3 AND sequence = $4
  AND state IN ('pending', 'running')
`

type ObserveIPFSControlOperationParams struct {
	State     string    `json:"state"`
	ErrorCode *string   `json:"error_code"`
	ID        uuid.UUID `json:"id"`
	Sequence  int64     `json:"sequence"`
}

func (q *Queries) ObserveIPFSControlOperation(ctx context.Context, arg ObserveIPFSControlOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, observeIPFSControlOperation,
		arg.State,
		arg.ErrorCode,
		arg.ID,
		arg.Sequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestIPFSControlOperation = `-- name: RequestIPFSControlOperation :one
WITH prior AS (
    SELECT op.id, op.sequence, op.config_revision, op.action, op.config, op.state, op.last_error_code, op.attempts, op.next_attempt_at, op.requested_by, op.created_at, op.updated_at FROM ipfs_control_operations AS op WHERE op.id = $1
), created AS (
    INSERT INTO ipfs_control_operations (id, config_revision, action, config, requested_by)
    SELECT $1, saved.revision, $2, saved.config, $3
    FROM ipfs_control_config AS saved
    WHERE saved.singleton AND saved.revision = $4
      AND saved.config->>'provider' = 'internal' AND NOT EXISTS (SELECT 1 FROM prior)
    ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
    WHERE ipfs_control_operations.action = EXCLUDED.action
      AND ipfs_control_operations.config_revision = EXCLUDED.config_revision
      AND ipfs_control_operations.config = EXCLUDED.config
    RETURNING id, sequence, config_revision, action, config, state, last_error_code, attempts, next_attempt_at, requested_by, created_at, updated_at
)
SELECT id, sequence, config_revision, action, config, state, last_error_code, attempts, next_attempt_at, requested_by, created_at, updated_at FROM created
UNION ALL
SELECT id, sequence, config_revision, action, config, state, last_error_code, attempts, next_attempt_at, requested_by, created_at, updated_at FROM prior WHERE config_revision = $4 AND action = $2
`

type RequestIPFSControlOperationParams struct {
	ID               uuid.UUID   `json:"id"`
	Action           string      `json:"action"`
	Actor            pgtype.UUID `json:"actor"`
	ExpectedRevision int64       `json:"expected_revision"`
}

type RequestIPFSControlOperationRow struct {
	ID             uuid.UUID   `json:"id"`
	Sequence       int64       `json:"sequence"`
	ConfigRevision int64       `json:"config_revision"`
	Action         string      `json:"action"`
	Config         []byte      `json:"config"`
	State          string      `json:"state"`
	LastErrorCode  *string     `json:"last_error_code"`
	Attempts       int32       `json:"attempts"`
	NextAttemptAt  time.Time   `json:"next_attempt_at"`
	RequestedBy    pgtype.UUID `json:"requested_by"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

// Replaying an accepted UUID returns its original result even if the config has
// since advanced. Reusing an ID for a different request never queues anything.
func (q *Queries) RequestIPFSControlOperation(ctx context.Context, arg RequestIPFSControlOperationParams) (RequestIPFSControlOperationRow, error) {
	row := q.db.QueryRow(ctx, requestIPFSControlOperation,
		arg.ID,
		arg.Action,
		arg.Actor,
		arg.ExpectedRevision,
	)
	var i RequestIPFSControlOperationRow
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ConfigRevision,
		&i.Action,
		&i.Config,
		&i.State,
		&i.LastErrorCode,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIPFSControlConfig = `-- name: UpdateIPFSControlConfig :one
WITH changed AS (
    UPDATE ipfs_control_config AS saved
    SET config = $1, revision = saved.revision + 1, policy_active = true,
        updated_by = $2, updated_at = now()
    WHERE saved.singleton AND saved.revision = $3
      AND (saved.config <> $1 OR NOT saved.policy_active)
    RETURNING saved.singleton, saved.revision, saved.config, saved.policy_active, saved.updated_by, saved.updated_at
), queued AS (
    INSERT INTO ipfs_control_operations (id, config_revision, action, config, requested_by)
    SELECT $4, changed.revision, 'apply', changed.config, $2
    FROM changed WHERE changed.config->>'provider' = 'internal'
    RETURNING id
), current AS (
    SELECT singleton, revision, config, policy_active, updated_by, updated_at FROM changed
    UNION ALL
    SELECT singleton, revision, config, policy_active, updated_by, updated_at FROM ipfs_control_config
    WHERE singleton AND revision = $3
      AND config = $1 AND policy_active AND NOT EXISTS (SELECT 1 FROM changed)
)
SELECT current.singleton, current.revision, current.config, current.policy_active, current.updated_by, current.updated_at, COALESCE(queued.id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS operation_id
FROM current LEFT JOIN queued ON true
`

type UpdateIPFSControlConfigParams struct {
	Config           []byte      `json:"config"`
	Actor            pgtype.UUID `json:"actor"`
	ExpectedRevision int64       `json:"expected_revision"`
	OperationID      uuid.UUID   `json:"operation_id"`
}

type UpdateIPFSControlConfigRow struct {
	Singleton    bool        `json:"singleton"`
	Revision     int64       `json:"revision"`
	Config       []byte      `json:"config"`
	PolicyActive bool        `json:"policy_active"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
	UpdatedAt    time.Time   `json:"updated_at"`
	OperationID  uuid.UUID   `json:"operation_id"`
}

// UPDATE itself provides the CAS predicate recheck after a concurrent writer.
// The complete config and its apply operation commit together.
func (q *Queries) UpdateIPFSControlConfig(ctx context.Context, arg UpdateIPFSControlConfigParams) (UpdateIPFSControlConfigRow, error) {
	row := q.db.QueryRow(ctx, updateIPFSControlConfig,
		arg.Config,
		arg.Actor,
		arg.ExpectedRevision,
		arg.OperationID,
	)
	var i UpdateIPFSControlConfigRow
	err := row.Scan(
		&i.Singleton,
		&i.Revision,
		&i.Config,
		&i.PolicyActive,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.OperationID,
	)
	return i, err
}
