// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_runs.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOperationalJobEvents = `-- name: CountOperationalJobEvents :one
SELECT count(*)::bigint
FROM job_events
WHERE job_id = $1
  AND cursor <= $2
`

type CountOperationalJobEventsParams struct {
	JobID         uuid.UUID `json:"job_id"`
	ThroughCursor int64     `json:"through_cursor"`
}

func (q *Queries) CountOperationalJobEvents(ctx context.Context, arg CountOperationalJobEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOperationalJobEvents, arg.JobID, arg.ThroughCursor)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOperationalJobRuns = `-- name: CountOperationalJobRuns :one
SELECT count(*)::bigint
FROM job_runs
WHERE ($1::text IS NULL OR state = $1)
  AND ($2::text IS NULL OR type = $2)
  AND ($3::text IS NULL OR queue = $3)
  AND ($4::text IS NULL OR resource_type = $4)
  AND ($5::text IS NULL OR resource_id = $5)
  AND ($6::text IS NULL OR worker_id = $6)
  AND ($7::boolean IS NULL
       OR ((state IN ('failed', 'dead_lettered')) = $7))
  AND ($8::timestamptz IS NULL OR created_at >= $8)
  AND ($9::timestamptz IS NULL OR created_at <= $9)
`

type CountOperationalJobRunsParams struct {
	State         *string            `json:"state"`
	Type          *string            `json:"type"`
	Queue         *string            `json:"queue"`
	ResourceType  *string            `json:"resource_type"`
	ResourceID    *string            `json:"resource_id"`
	WorkerID      *string            `json:"worker_id"`
	Failure       *bool              `json:"failure"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
}

func (q *Queries) CountOperationalJobRuns(ctx context.Context, arg CountOperationalJobRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOperationalJobRuns,
		arg.State,
		arg.Type,
		arg.Queue,
		arg.ResourceType,
		arg.ResourceID,
		arg.WorkerID,
		arg.Failure,
		arg.CreatedAfter,
		arg.CreatedBefore,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getOperationalJobRun = `-- name: GetOperationalJobRun :one
SELECT id, pipeline_run_id, parent_job_id, type, queue, source_id, state, stage, progress_percent, priority, attempt, max_attempts, idempotency_key, actor_id, resource_type, resource_id, request_id, correlation_id, trace_id, worker_id, lease_token, lease_expires_at, heartbeat_at, cancel_requested_at, input_metadata, output_metadata, error_class, error_code, error_detail, error_retryable, created_at, claimed_at, started_at, updated_at, finished_at FROM job_runs WHERE id = $1
`

func (q *Queries) GetOperationalJobRun(ctx context.Context, id uuid.UUID) (JobRun, error) {
	row := q.db.QueryRow(ctx, getOperationalJobRun, id)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.PipelineRunID,
		&i.ParentJobID,
		&i.Type,
		&i.Queue,
		&i.SourceID,
		&i.State,
		&i.Stage,
		&i.ProgressPercent,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.IdempotencyKey,
		&i.ActorID,
		&i.ResourceType,
		&i.ResourceID,
		&i.RequestID,
		&i.CorrelationID,
		&i.TraceID,
		&i.WorkerID,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.CancelRequestedAt,
		&i.InputMetadata,
		&i.OutputMetadata,
		&i.ErrorClass,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.ErrorRetryable,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listOperationalJobEvents = `-- name: ListOperationalJobEvents :many
SELECT cursor, id, schema_version, job_id, pipeline_run_id, kind, state, stage, progress_percent, attempt, worker_id, message, metadata, request_id, correlation_id, trace_id, occurred_at
FROM job_events
WHERE job_id = $1
  AND cursor <= $2
ORDER BY cursor DESC
LIMIT $4 OFFSET $3
`

type ListOperationalJobEventsParams struct {
	JobID         uuid.UUID `json:"job_id"`
	ThroughCursor int64     `json:"through_cursor"`
	ResultOffset  int32     `json:"result_offset"`
	ResultLimit   int32     `json:"result_limit"`
}

func (q *Queries) ListOperationalJobEvents(ctx context.Context, arg ListOperationalJobEventsParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listOperationalJobEvents,
		arg.JobID,
		arg.ThroughCursor,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEvent
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.Cursor,
			&i.ID,
			&i.SchemaVersion,
			&i.JobID,
			&i.PipelineRunID,
			&i.Kind,
			&i.State,
			&i.Stage,
			&i.ProgressPercent,
			&i.Attempt,
			&i.WorkerID,
			&i.Message,
			&i.Metadata,
			&i.RequestID,
			&i.CorrelationID,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationalJobEventsAfter = `-- name: ListOperationalJobEventsAfter :many
SELECT e.cursor, e.id, e.schema_version, e.job_id, e.pipeline_run_id, e.kind, e.state, e.stage, e.progress_percent, e.attempt, e.worker_id, e.message, e.metadata, e.request_id, e.correlation_id, e.trace_id, e.occurred_at
FROM job_events e
JOIN job_runs j ON j.id = e.job_id
WHERE e.cursor > $1
  AND ($2::uuid IS NULL OR e.job_id = $2)
  AND ($3::text IS NULL OR j.state = $3)
  AND ($4::text IS NULL OR j.type = $4)
  AND ($5::text IS NULL OR j.queue = $5)
  AND ($6::text IS NULL OR j.resource_type = $6)
  AND ($7::text IS NULL OR j.resource_id = $7)
  AND ($8::text IS NULL OR j.worker_id = $8)
  AND ($9::boolean IS NULL
       OR ((j.state IN ('failed', 'dead_lettered')) = $9))
  AND ($10::timestamptz IS NULL OR j.created_at >= $10)
  AND ($11::timestamptz IS NULL OR j.created_at <= $11)
ORDER BY e.cursor
LIMIT $12
`

type ListOperationalJobEventsAfterParams struct {
	AfterCursor   int64              `json:"after_cursor"`
	JobID         pgtype.UUID        `json:"job_id"`
	State         *string            `json:"state"`
	Type          *string            `json:"type"`
	Queue         *string            `json:"queue"`
	ResourceType  *string            `json:"resource_type"`
	ResourceID    *string            `json:"resource_id"`
	WorkerID      *string            `json:"worker_id"`
	Failure       *bool              `json:"failure"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	ResultLimit   int32              `json:"result_limit"`
}

func (q *Queries) ListOperationalJobEventsAfter(ctx context.Context, arg ListOperationalJobEventsAfterParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listOperationalJobEventsAfter,
		arg.AfterCursor,
		arg.JobID,
		arg.State,
		arg.Type,
		arg.Queue,
		arg.ResourceType,
		arg.ResourceID,
		arg.WorkerID,
		arg.Failure,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEvent
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.Cursor,
			&i.ID,
			&i.SchemaVersion,
			&i.JobID,
			&i.PipelineRunID,
			&i.Kind,
			&i.State,
			&i.Stage,
			&i.ProgressPercent,
			&i.Attempt,
			&i.WorkerID,
			&i.Message,
			&i.Metadata,
			&i.RequestID,
			&i.CorrelationID,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationalJobRuns = `-- name: ListOperationalJobRuns :many

SELECT id, pipeline_run_id, parent_job_id, type, queue, source_id, state, stage, progress_percent, priority, attempt, max_attempts, idempotency_key, actor_id, resource_type, resource_id, request_id, correlation_id, trace_id, worker_id, lease_token, lease_expires_at, heartbeat_at, cancel_requested_at, input_metadata, output_metadata, error_class, error_code, error_detail, error_retryable, created_at, claimed_at, started_at, updated_at, finished_at
FROM job_runs
WHERE ($1::text IS NULL OR state = $1)
  AND ($2::text IS NULL OR type = $2)
  AND ($3::text IS NULL OR queue = $3)
  AND ($4::text IS NULL OR resource_type = $4)
  AND ($5::text IS NULL OR resource_id = $5)
  AND ($6::text IS NULL OR worker_id = $6)
  AND ($7::boolean IS NULL
       OR ((state IN ('failed', 'dead_lettered')) = $7))
  AND ($8::timestamptz IS NULL OR created_at >= $8)
  AND ($9::timestamptz IS NULL OR created_at <= $9)
ORDER BY created_at DESC, id DESC
LIMIT $11 OFFSET $10
`

type ListOperationalJobRunsParams struct {
	State         *string            `json:"state"`
	Type          *string            `json:"type"`
	Queue         *string            `json:"queue"`
	ResourceType  *string            `json:"resource_type"`
	ResourceID    *string            `json:"resource_id"`
	WorkerID      *string            `json:"worker_id"`
	Failure       *bool              `json:"failure"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	ResultOffset  int32              `json:"result_offset"`
	ResultLimit   int32              `json:"result_limit"`
}

// Unified operational job-run read side (migration 0083). The source queue
// tables remain authoritative for execution; these queries expose only the
// sanitized projection maintained transactionally by database triggers.
func (q *Queries) ListOperationalJobRuns(ctx context.Context, arg ListOperationalJobRunsParams) ([]JobRun, error) {
	rows, err := q.db.Query(ctx, listOperationalJobRuns,
		arg.State,
		arg.Type,
		arg.Queue,
		arg.ResourceType,
		arg.ResourceID,
		arg.WorkerID,
		arg.Failure,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobRun
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.ParentJobID,
			&i.Type,
			&i.Queue,
			&i.SourceID,
			&i.State,
			&i.Stage,
			&i.ProgressPercent,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.IdempotencyKey,
			&i.ActorID,
			&i.ResourceType,
			&i.ResourceID,
			&i.RequestID,
			&i.CorrelationID,
			&i.TraceID,
			&i.WorkerID,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.CancelRequestedAt,
			&i.InputMetadata,
			&i.OutputMetadata,
			&i.ErrorClass,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.ErrorRetryable,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxOperationalJobEventCursor = `-- name: MaxOperationalJobEventCursor :one
SELECT COALESCE(max(cursor), 0)::bigint FROM job_events
`

func (q *Queries) MaxOperationalJobEventCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxOperationalJobEventCursor)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const minOperationalJobEventCursor = `-- name: MinOperationalJobEventCursor :one
SELECT COALESCE(min(cursor), 0)::bigint FROM job_events
`

func (q *Queries) MinOperationalJobEventCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, minOperationalJobEventCursor)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const operationalJobQueueMetrics = `-- name: OperationalJobQueueMetrics :many
SELECT
    queue,
    COALESCE(EXTRACT(EPOCH FROM (now() - min(created_at)
        FILTER (WHERE state IN ('queued', 'retry_scheduled'))))::bigint, 0)::bigint
        AS oldest_queued_age_seconds,
    count(*) FILTER (
        WHERE state IN ('claimed', 'running')
          AND ((lease_expires_at IS NOT NULL AND lease_expires_at < now())
               OR (lease_expires_at IS NULL
                   AND updated_at < now() - ($1::int * interval '1 second')))
    )::bigint AS stale_running
FROM job_runs
GROUP BY queue
ORDER BY queue
`

type OperationalJobQueueMetricsRow struct {
	Queue                  string `json:"queue"`
	OldestQueuedAgeSeconds int64  `json:"oldest_queued_age_seconds"`
	StaleRunning           int64  `json:"stale_running"`
}

func (q *Queries) OperationalJobQueueMetrics(ctx context.Context, staleSeconds int32) ([]OperationalJobQueueMetricsRow, error) {
	rows, err := q.db.Query(ctx, operationalJobQueueMetrics, staleSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationalJobQueueMetricsRow
	for rows.Next() {
		var i OperationalJobQueueMetricsRow
		if err := rows.Scan(&i.Queue, &i.OldestQueuedAgeSeconds, &i.StaleRunning); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOperationalJobEvents = `-- name: PruneOperationalJobEvents :execrows
DELETE FROM job_events
WHERE cursor IN (
    SELECT e.cursor
    FROM job_events e
    JOIN job_runs j ON j.id = e.job_id
    WHERE e.occurred_at < $1
      AND j.state IN ('succeeded', 'failed', 'dead_lettered', 'cancelled')
    ORDER BY e.cursor
    LIMIT $2
)
`

type PruneOperationalJobEventsParams struct {
	Cutoff    time.Time `json:"cutoff"`
	BatchSize int32     `json:"batch_size"`
}

func (q *Queries) PruneOperationalJobEvents(ctx context.Context, arg PruneOperationalJobEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneOperationalJobEvents, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneTerminalOperationalJobRuns = `-- name: PruneTerminalOperationalJobRuns :execrows
DELETE FROM job_runs target
WHERE target.id IN (
    SELECT candidate.id FROM job_runs candidate
    WHERE candidate.state IN ('succeeded', 'failed', 'dead_lettered', 'cancelled')
      AND candidate.finished_at IS NOT NULL
      AND candidate.finished_at < $1
    ORDER BY candidate.finished_at, candidate.id
    LIMIT $2
)
`

type PruneTerminalOperationalJobRunsParams struct {
	Cutoff    pgtype.Timestamptz `json:"cutoff"`
	BatchSize int32              `json:"batch_size"`
}

func (q *Queries) PruneTerminalOperationalJobRuns(ctx context.Context, arg PruneTerminalOperationalJobRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneTerminalOperationalJobRuns, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneTerminalPipelineRuns = `-- name: PruneTerminalPipelineRuns :execrows
DELETE FROM pipeline_runs p
WHERE p.id IN (
    SELECT candidate.id FROM pipeline_runs candidate
    WHERE candidate.state IN ('succeeded', 'failed', 'cancelled', 'partial')
      AND candidate.finished_at IS NOT NULL
      AND candidate.finished_at < $1
      AND NOT EXISTS (SELECT 1 FROM job_runs j WHERE j.pipeline_run_id = candidate.id)
    ORDER BY candidate.finished_at, candidate.id
    LIMIT $2
)
`

type PruneTerminalPipelineRunsParams struct {
	Cutoff    pgtype.Timestamptz `json:"cutoff"`
	BatchSize int32              `json:"batch_size"`
}

func (q *Queries) PruneTerminalPipelineRuns(ctx context.Context, arg PruneTerminalPipelineRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneTerminalPipelineRuns, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
