// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_streams.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveStreamsLive = `-- name: CountLiveStreamsLive :one
SELECT count(*) FROM live_streams WHERE state = 'live'
`

// How many sessions are currently live across the instance (the
// live_max_instance_lives publish-callback cap, config-parity W11).
func (q *Queries) CountLiveStreamsLive(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveStreamsLive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveStreamsLiveByOwner = `-- name: CountLiveStreamsLiveByOwner :one
SELECT count(*)
FROM live_streams ls
JOIN channels ch ON ch.id = ls.channel_id
WHERE ls.state = 'live' AND ch.owner_id = $1
`

// How many sessions the given user currently has live across all their
// channels (the live_max_user_lives publish-callback cap, config-parity W11).
func (q *Queries) CountLiveStreamsLiveByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveStreamsLiveByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLiveStream = `-- name: CreateLiveStream :one
INSERT INTO live_streams (channel_id, title, description, privacy, permanent, replay_enabled, stream_key_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, channel_id, title, description, privacy, state, permanent, replay_enabled, started_at, created_at, updated_at
`

type CreateLiveStreamParams struct {
	ChannelID     uuid.UUID `json:"channel_id"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Privacy       string    `json:"privacy"`
	Permanent     bool      `json:"permanent"`
	ReplayEnabled bool      `json:"replay_enabled"`
	StreamKeyHash string    `json:"stream_key_hash"`
}

type CreateLiveStreamRow struct {
	ID            uuid.UUID          `json:"id"`
	ChannelID     uuid.UUID          `json:"channel_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Privacy       string             `json:"privacy"`
	State         string             `json:"state"`
	Permanent     bool               `json:"permanent"`
	ReplayEnabled bool               `json:"replay_enabled"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// Create a live stream for a channel with a pre-hashed stream key. The raw key is
// returned to the caller once by the service; only the hash is stored here.
func (q *Queries) CreateLiveStream(ctx context.Context, arg CreateLiveStreamParams) (CreateLiveStreamRow, error) {
	row := q.db.QueryRow(ctx, createLiveStream,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.Privacy,
		arg.Permanent,
		arg.ReplayEnabled,
		arg.StreamKeyHash,
	)
	var i CreateLiveStreamRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Privacy,
		&i.State,
		&i.Permanent,
		&i.ReplayEnabled,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLiveStream = `-- name: DeleteLiveStream :execrows
DELETE FROM live_streams WHERE id = $1
`

func (q *Queries) DeleteLiveStream(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLiveStream, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveStreamByID = `-- name: GetLiveStreamByID :one
SELECT ls.id, ls.channel_id, ls.title, ls.description, ls.privacy, ls.state, ls.permanent,
       ls.replay_enabled, ls.started_at, ls.created_at, ls.updated_at,
       ch.owner_id, ch.handle AS channel_handle, ch.display_name AS channel_display_name
FROM live_streams ls
JOIN channels ch ON ch.id = ls.channel_id
WHERE ls.id = $1
`

type GetLiveStreamByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	ChannelID          uuid.UUID          `json:"channel_id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Privacy            string             `json:"privacy"`
	State              string             `json:"state"`
	Permanent          bool               `json:"permanent"`
	ReplayEnabled      bool               `json:"replay_enabled"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	OwnerID            uuid.UUID          `json:"owner_id"`
	ChannelHandle      string             `json:"channel_handle"`
	ChannelDisplayName string             `json:"channel_display_name"`
}

// One live stream joined with its owning channel (owner_id for authz, handle +
// display name for display). Never returns the stream key hash.
func (q *Queries) GetLiveStreamByID(ctx context.Context, id uuid.UUID) (GetLiveStreamByIDRow, error) {
	row := q.db.QueryRow(ctx, getLiveStreamByID, id)
	var i GetLiveStreamByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Privacy,
		&i.State,
		&i.Permanent,
		&i.ReplayEnabled,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.ChannelHandle,
		&i.ChannelDisplayName,
	)
	return i, err
}

const getLiveStreamByKeyHash = `-- name: GetLiveStreamByKeyHash :one
SELECT ls.id, ls.channel_id, ls.permanent, ls.state, ch.owner_id
FROM live_streams ls
JOIN channels ch ON ch.id = ls.channel_id
WHERE ls.stream_key_hash = $1
`

type GetLiveStreamByKeyHashRow struct {
	ID        uuid.UUID `json:"id"`
	ChannelID uuid.UUID `json:"channel_id"`
	Permanent bool      `json:"permanent"`
	State     string    `json:"state"`
	OwnerID   uuid.UUID `json:"owner_id"`
}

// Look up a stream by its key hash — the RTMP ingest boundary authenticates a
// publisher by hashing the presented stream key. Returns id, channel + owner
// (the per-user simultaneous-lives cap counts by owner, config-parity W11),
// permanent (so stop can decide ended vs offline), and current state.
func (q *Queries) GetLiveStreamByKeyHash(ctx context.Context, streamKeyHash string) (GetLiveStreamByKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getLiveStreamByKeyHash, streamKeyHash)
	var i GetLiveStreamByKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Permanent,
		&i.State,
		&i.OwnerID,
	)
	return i, err
}

const listLivePublicStreams = `-- name: ListLivePublicStreams :many
SELECT ls.id, ls.title, ls.description, ls.started_at,
       ch.handle AS channel_handle, ch.display_name AS channel_display_name
FROM live_streams ls
JOIN channels ch ON ch.id = ls.channel_id
WHERE ls.state = 'live' AND ls.privacy = 'public'
ORDER BY ls.started_at DESC NULLS LAST, ls.id
LIMIT $1 OFFSET $2
`

type ListLivePublicStreamsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListLivePublicStreamsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	ChannelHandle      string             `json:"channel_handle"`
	ChannelDisplayName string             `json:"channel_display_name"`
}

// Public "Live now" listing: currently-live PUBLIC streams across all channels,
// most-recently-started first. Unlisted/private streams and offline/ended streams
// never appear. Joined with the owning channel for display; never the key hash.
func (q *Queries) ListLivePublicStreams(ctx context.Context, arg ListLivePublicStreamsParams) ([]ListLivePublicStreamsRow, error) {
	rows, err := q.db.Query(ctx, listLivePublicStreams, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLivePublicStreamsRow
	for rows.Next() {
		var i ListLivePublicStreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartedAt,
			&i.ChannelHandle,
			&i.ChannelDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveStreamsByChannel = `-- name: ListLiveStreamsByChannel :many
SELECT id, channel_id, title, description, privacy, state, permanent, replay_enabled, started_at, created_at, updated_at
FROM live_streams
WHERE channel_id = $1
ORDER BY created_at DESC, id
`

type ListLiveStreamsByChannelRow struct {
	ID            uuid.UUID          `json:"id"`
	ChannelID     uuid.UUID          `json:"channel_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Privacy       string             `json:"privacy"`
	State         string             `json:"state"`
	Permanent     bool               `json:"permanent"`
	ReplayEnabled bool               `json:"replay_enabled"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// A channel's live streams, newest first (owner management list). No key hash.
func (q *Queries) ListLiveStreamsByChannel(ctx context.Context, channelID uuid.UUID) ([]ListLiveStreamsByChannelRow, error) {
	rows, err := q.db.Query(ctx, listLiveStreamsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveStreamsByChannelRow
	for rows.Next() {
		var i ListLiveStreamsByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Privacy,
			&i.State,
			&i.Permanent,
			&i.ReplayEnabled,
			&i.StartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueLiveStreams = `-- name: ListOverdueLiveStreams :many
SELECT id, permanent, started_at
FROM live_streams
WHERE state = 'live' AND started_at IS NOT NULL AND started_at < $1
ORDER BY started_at, id
`

type ListOverdueLiveStreamsRow struct {
	ID        uuid.UUID          `json:"id"`
	Permanent bool               `json:"permanent"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

// Currently-live sessions that started before the cutoff — the
// live_max_duration_secs watchdog force-closes these (config-parity W11).
// started_at IS NOT NULL guards streams that went live before started_at
// tracking existed (migration 0076): with no session start there is nothing
// truthful to measure, so they are never force-closed.
func (q *Queries) ListOverdueLiveStreams(ctx context.Context, startedAt pgtype.Timestamptz) ([]ListOverdueLiveStreamsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueLiveStreams, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueLiveStreamsRow
	for rows.Next() {
		var i ListOverdueLiveStreamsRow
		if err := rows.Scan(&i.ID, &i.Permanent, &i.StartedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLiveStreamState = `-- name: SetLiveStreamState :exec
UPDATE live_streams
SET state = $2,
    started_at = CASE
        WHEN $2 = 'live' AND state <> 'live' THEN now()
        WHEN $2 = 'live' THEN started_at
        ELSE NULL
    END,
    updated_at = now()
WHERE id = $1
`

type SetLiveStreamStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

// Flip a stream's live state (offline/live/ended), set by the ingest boundary.
// Entering 'live' from a non-live state stamps started_at (the current session's
// start, surfaced by the public "Live now" listing); an idempotent re-assert of
// 'live' (e.g. the post-rename re-invocation) preserves the original start;
// leaving live (offline/ended) clears it.
func (q *Queries) SetLiveStreamState(ctx context.Context, arg SetLiveStreamStateParams) error {
	_, err := q.db.Exec(ctx, setLiveStreamState, arg.ID, arg.State)
	return err
}

const updateLiveStream = `-- name: UpdateLiveStream :one
UPDATE live_streams
SET title = $2, description = $3, privacy = $4, permanent = $5, replay_enabled = $6, updated_at = now()
WHERE id = $1
RETURNING id, channel_id, title, description, privacy, state, permanent, replay_enabled, started_at, created_at, updated_at
`

type UpdateLiveStreamParams struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Privacy       string    `json:"privacy"`
	Permanent     bool      `json:"permanent"`
	ReplayEnabled bool      `json:"replay_enabled"`
}

type UpdateLiveStreamRow struct {
	ID            uuid.UUID          `json:"id"`
	ChannelID     uuid.UUID          `json:"channel_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Privacy       string             `json:"privacy"`
	State         string             `json:"state"`
	Permanent     bool               `json:"permanent"`
	ReplayEnabled bool               `json:"replay_enabled"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// Edit a stream's mutable metadata (title/description/privacy/permanent/
// replay_enabled). The caller has already authorised ownership. Never touches the
// stream key or live state.
func (q *Queries) UpdateLiveStream(ctx context.Context, arg UpdateLiveStreamParams) (UpdateLiveStreamRow, error) {
	row := q.db.QueryRow(ctx, updateLiveStream,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Privacy,
		arg.Permanent,
		arg.ReplayEnabled,
	)
	var i UpdateLiveStreamRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Privacy,
		&i.State,
		&i.Permanent,
		&i.ReplayEnabled,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLiveStreamKey = `-- name: UpdateLiveStreamKey :exec
UPDATE live_streams SET stream_key_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateLiveStreamKeyParams struct {
	ID            uuid.UUID `json:"id"`
	StreamKeyHash string    `json:"stream_key_hash"`
}

// Rotate a stream's key (store the new hash).
func (q *Queries) UpdateLiveStreamKey(ctx context.Context, arg UpdateLiveStreamKeyParams) error {
	_, err := q.db.Exec(ctx, updateLiveStreamKey, arg.ID, arg.StreamKeyHash)
	return err
}
