// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_ipfs_pins.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backfillIPFSPinIntent = `-- name: BackfillIPFSPinIntent :execrows
INSERT INTO media_ipfs_pins (object_key, media_class, video_id, owner_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (object_key) DO NOTHING
`

type BackfillIPFSPinIntentParams struct {
	ObjectKey   string      `json:"object_key"`
	MediaClass  string      `json:"media_class"`
	VideoID     pgtype.UUID `json:"video_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

// One-shot catalog backfill (P19.6 admin reconcile): seed a pin intent for a
// pre-existing eligible object that has NO ledger row yet. Unlike
// UpsertIPFSPinIntent (which re-arms a terminal row) this NEVER touches an existing
// row in any state — the periodic reconcile re-arms failures; the backfill's sole
// job is to seed rows for objects that predate the mirror (or were missed during an
// outage). ON CONFLICT DO NOTHING makes it idempotent, and :execrows returns 1 when
// a row was inserted, 0 when one already existed, so the caller tallies the
// newly-enqueued objects per class and a second run provably enqueues zero. The
// eligibility gate is enforced by the caller BEFORE this runs (the privacy fence);
// only already-public objects ever reach here.
func (q *Queries) BackfillIPFSPinIntent(ctx context.Context, arg BackfillIPFSPinIntentParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillIPFSPinIntent,
		arg.ObjectKey,
		arg.MediaClass,
		arg.VideoID,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueIPFSPins = `-- name: ClaimDueIPFSPins :many
UPDATE media_ipfs_pins
SET next_attempt_at = now() + ($1::int * interval '1 second'),
    updated_at = now()
WHERE object_key IN (
    SELECT p.object_key FROM media_ipfs_pins p
    WHERE p.network = $2 AND p.state IN ('pending', 'unpinning') AND p.next_attempt_at <= now()
    ORDER BY p.next_attempt_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING object_key, media_class, cid, car_root, state, attempts, network, video_id, owner_user_id
`

type ClaimDueIPFSPinsParams struct {
	LeaseSeconds int32  `json:"lease_seconds"`
	Network      string `json:"network"`
	BatchSize    int32  `json:"batch_size"`
}

type ClaimDueIPFSPinsRow struct {
	ObjectKey   string      `json:"object_key"`
	MediaClass  string      `json:"media_class"`
	Cid         string      `json:"cid"`
	CarRoot     string      `json:"car_root"`
	State       string      `json:"state"`
	Attempts    int32       `json:"attempts"`
	Network     string      `json:"network"`
	VideoID     pgtype.UUID `json:"video_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

// Atomically leases due pin/unpin work for ONE network (P19.P1). FOR UPDATE SKIP
// LOCKED lets IPFS_PIN_CONCURRENCY workers claim disjoint rows without blocking each
// other; pushing next_attempt_at forward by the lease seconds is the visibility
// timeout (a crashed worker's row is retried after the lease; a concurrent claimer
// skips it meanwhile). state is PRESERVED — pending ⇒ add+pin, unpinning ⇒ unpin —
// and the worker sets the terminal state via MarkPinned / MarkFailed / MarkUnpinned
// (pinning and unpinning are idempotent, so an over-long lease is safe). The @network
// filter is the fail-closed routing boundary: the worker drains each network with its
// OWN node client, so the private client only ever sees private rows and the public
// client only public rows — the public client is never even in scope for a private
// pin (spec §1/§8). network is RETURNED for the worker's log/route assertion.
func (q *Queries) ClaimDueIPFSPins(ctx context.Context, arg ClaimDueIPFSPinsParams) ([]ClaimDueIPFSPinsRow, error) {
	rows, err := q.db.Query(ctx, claimDueIPFSPins, arg.LeaseSeconds, arg.Network, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueIPFSPinsRow
	for rows.Next() {
		var i ClaimDueIPFSPinsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.MediaClass,
			&i.Cid,
			&i.CarRoot,
			&i.State,
			&i.Attempts,
			&i.Network,
			&i.VideoID,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countIPFSPinsByNetworkStateClass = `-- name: CountIPFSPinsByNetworkStateClass :many
SELECT network, state, media_class, count(*)::bigint AS count
FROM media_ipfs_pins
GROUP BY network, state, media_class
ORDER BY network, state, media_class
`

type CountIPFSPinsByNetworkStateClassRow struct {
	Network    string `json:"network"`
	State      string `json:"state"`
	MediaClass string `json:"media_class"`
	Count      int64  `json:"count"`
}

// Admin status aggregation (P19.2 /ipfs/status), now sliced by network (P19.P1):
// pin counts per (network, state, media_class), cheap off the network_state and
// state_class indexes. The public-tier admin response folds across networks (all
// rows are public until P19.P2 routes private media); the P19.P2 admin split reads
// the network dimension directly to render the second column.
func (q *Queries) CountIPFSPinsByNetworkStateClass(ctx context.Context) ([]CountIPFSPinsByNetworkStateClassRow, error) {
	rows, err := q.db.Query(ctx, countIPFSPinsByNetworkStateClass)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountIPFSPinsByNetworkStateClassRow
	for rows.Next() {
		var i CountIPFSPinsByNetworkStateClassRow
		if err := rows.Scan(
			&i.Network,
			&i.State,
			&i.MediaClass,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countIPFSPinsSharingCID = `-- name: CountIPFSPinsSharingCID :one
SELECT count(*)::bigint
FROM media_ipfs_pins
WHERE cid = $1 AND cid <> '' AND object_key <> $2 AND state IN ('pinned', 'pending')
`

type CountIPFSPinsSharingCIDParams struct {
	Cid       string `json:"cid"`
	ObjectKey string `json:"object_key"`
}

// Reference count for content-address dedupe (P19.3 "never unpin without
// reference checking"): how many OTHER live rows (pinned/pending) share this CID.
// The worker only issues the network unpin when this is zero.
func (q *Queries) CountIPFSPinsSharingCID(ctx context.Context, arg CountIPFSPinsSharingCIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIPFSPinsSharingCID, arg.Cid, arg.ObjectKey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const enqueueIPFSUnpin = `-- name: EnqueueIPFSUnpin :exec
UPDATE media_ipfs_pins
SET state = 'unpinning', attempts = 0, next_attempt_at = now(), last_error = '', updated_at = now()
WHERE object_key = $1 AND state IN ('pinned', 'pending')
`

// Flip a live pin toward removal: the delete/GC path (P19.3+) sets an existing
// row to 'unpinning' so ClaimDue leases it to the worker. Only pinned/pending rows
// transition (a terminal or already-unpinning row is left alone).
func (q *Queries) EnqueueIPFSUnpin(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, enqueueIPFSUnpin, objectKey)
	return err
}

const getIPFSPinByObjectKey = `-- name: GetIPFSPinByObjectKey :one
SELECT object_key, media_class, cid, car_root, byte_size, state, attempts, next_attempt_at, last_error, video_id, owner_user_id, created_at, updated_at, network FROM media_ipfs_pins WHERE object_key = $1
`

func (q *Queries) GetIPFSPinByObjectKey(ctx context.Context, objectKey string) (MediaIpfsPin, error) {
	row := q.db.QueryRow(ctx, getIPFSPinByObjectKey, objectKey)
	var i MediaIpfsPin
	err := row.Scan(
		&i.ObjectKey,
		&i.MediaClass,
		&i.Cid,
		&i.CarRoot,
		&i.ByteSize,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.VideoID,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}

const listIPFSPinsByVideo = `-- name: ListIPFSPinsByVideo :many
SELECT object_key, media_class, cid, car_root, byte_size, state, attempts, next_attempt_at, last_error, video_id, owner_user_id, created_at, updated_at, network FROM media_ipfs_pins WHERE video_id = $1 ORDER BY media_class, object_key
`

// Every ledger row for a video (privacy re-evaluation + cascade unpin, P19.3),
// off media_ipfs_pins_video_idx.
func (q *Queries) ListIPFSPinsByVideo(ctx context.Context, videoID pgtype.UUID) ([]MediaIpfsPin, error) {
	rows, err := q.db.Query(ctx, listIPFSPinsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaIpfsPin
	for rows.Next() {
		var i MediaIpfsPin
		if err := rows.Scan(
			&i.ObjectKey,
			&i.MediaClass,
			&i.Cid,
			&i.CarRoot,
			&i.ByteSize,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.VideoID,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedVideoIDs = `-- name: ListPinnedVideoIDs :many
SELECT DISTINCT video_id
FROM media_ipfs_pins
WHERE state = 'pinned'
  AND network = 'public'
  AND video_id IS NOT NULL
  AND video_id = ANY($1::uuid[])
`

// Feed/card badge batch lookup (P19.3): of the given video ids, which have at
// least one currently-pinned ledger row. One indexed scan for a whole page (the
// ipfs_pinned boolean), off media_ipfs_pins_video_idx, so the badge never costs
// a per-card query. Only 'pinned' rows count — a video whose media was unpinned
// (went private) is correctly reported as not pinned. PRIVACY FENCE (P19.P1): only
// network='public' rows count — ipfs_pinned is a PUBLIC-network signal, so a
// private/unlisted video whose bytes are replicated on the private swarm is NEVER
// reported pinned in any API payload (no private CID or gateway URL ever leaks).
func (q *Queries) ListPinnedVideoIDs(ctx context.Context, videoIds []uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPinnedVideoIDs, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var video_id pgtype.UUID
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIPFSPinFailed = `-- name: MarkIPFSPinFailed :exec
UPDATE media_ipfs_pins
SET state = 'failed', attempts = attempts + 1, last_error = $2, updated_at = now()
WHERE object_key = $1 AND state = $3
`

type MarkIPFSPinFailedParams struct {
	ObjectKey     string `json:"object_key"`
	LastError     string `json:"last_error"`
	ExpectedState string `json:"expected_state"`
}

// Dead-letter a pin/unpin after max attempts: no further automatic retries (the
// reconciliation scan can re-arm it later). last_error is a SAFE, client-invisible
// reason — never the raw node error verbatim. STATE-GUARDED (P19 audit): the
// dead-letter only lands when the row is STILL in the actionable state the worker
// claimed (sqlc.arg(expected_state) — 'pending' for a pin, 'unpinning' for an
// unpin). If a concurrent privacy flip re-directed the row (pending↔unpinning), the
// newer intent is preserved rather than clobbered to 'failed' — which the reconcile
// scan would otherwise re-arm in the WRONG direction (a failed-pin cid=” re-pins,
// so a clobbered unpin would re-pin a now-non-public object: a privacy regression).
func (q *Queries) MarkIPFSPinFailed(ctx context.Context, arg MarkIPFSPinFailedParams) error {
	_, err := q.db.Exec(ctx, markIPFSPinFailed, arg.ObjectKey, arg.LastError, arg.ExpectedState)
	return err
}

const markIPFSPinUnpinned = `-- name: MarkIPFSPinUnpinned :exec
UPDATE media_ipfs_pins
SET state = 'unpinned', last_error = '', updated_at = now()
WHERE object_key = $1 AND state = 'unpinning'
`

// Terminal success for an unpin (the delete/GC path). The row is kept (not
// deleted) as an audit trail; content-address dedupe (P19.3) reads it. STATE-GUARDED
// (P19 audit): only completes the unpin when the row is STILL 'unpinning'. If a
// concurrent private→public flip re-armed it to 'pending' (UpsertIPFSPinIntent)
// while the node unpin was in flight, that newer pin intent is preserved (the worker
// re-pins the now-public object) rather than clobbered to 'unpinned' — the
// double-flip converges to the latest visibility fact.
func (q *Queries) MarkIPFSPinUnpinned(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, markIPFSPinUnpinned, objectKey)
	return err
}

const markIPFSPinned = `-- name: MarkIPFSPinned :one
UPDATE media_ipfs_pins
SET cid = $2,
    car_root = $3,
    byte_size = $4,
    state = CASE
        WHEN state IN ('pending', 'pinned') THEN 'pinned'
        WHEN state = 'unpinned' THEN 'unpinning'
        ELSE state
    END,
    last_error = '',
    updated_at = now()
WHERE object_key = $1
RETURNING state
`

type MarkIPFSPinnedParams struct {
	ObjectKey string `json:"object_key"`
	Cid       string `json:"cid"`
	CarRoot   string `json:"car_root"`
	ByteSize  int64  `json:"byte_size"`
}

// Terminal success for a pin: record the CID (and wrap-directory root for HLS
// trees) and the pinned byte size. STATE-GUARDED against a lost-update race with a
// concurrent privacy flip (P19 audit BLOCKER): the CID/car_root/byte_size are
// ALWAYS persisted — the bytes ARE on the node now, so a subsequent unpin needs the
// CID to target them — but state advances to 'pinned' ONLY when the row is still
// pinnable (pending, or idempotently pinned). If a concurrent EnqueueIPFSUnpin
// flipped the leased row to 'unpinning' (the object went non-public mid-Add), the
// CASE KEEPS 'unpinning' so the unpin worker removes the now-non-public bytes: the
// stale pin worker NEVER clobbers the newer visibility fact back to 'pinned'.
//
// ROUND-2 AUDIT (raced-to-terminal-'unpinned' durability): a SECOND worker can
// claim the concurrently-flipped 'unpinning' row (cid=” at that instant) and
// complete the empty-cid unpin → terminal 'unpinned' BEFORE this pin's Add returns.
// When this MarkIPFSPinned then records the freshly-added CID onto that 'unpinned'
// row, the bytes are on the public node but the ledger reads a TERMINAL state
// ClaimDue never re-selects (and the failed-only reconcile never re-arms) — a
// permanent leak. So the CASE also flips 'unpinned' → 'unpinning' HERE, atomically
// with recording the CID: the removal is re-armed at the source (no crash window,
// no in-memory/DB divergence), and the worker's pinRacedUnpin drives the durable
// reference-checked node removal. MarkIPFSPinned only ever runs right after adding
// bytes to the node, so a CID landing on an 'unpinned' row ALWAYS means those bytes
// need removal — never a genuinely-clean terminal row.
// RETURNING state lets the worker learn which outcome happened (pinned vs raced)
// and, on a loss, execute the unpin immediately instead of leaking until the next
// reconcile.
func (q *Queries) MarkIPFSPinned(ctx context.Context, arg MarkIPFSPinnedParams) (string, error) {
	row := q.db.QueryRow(ctx, markIPFSPinned,
		arg.ObjectKey,
		arg.Cid,
		arg.CarRoot,
		arg.ByteSize,
	)
	var state string
	err := row.Scan(&state)
	return state, err
}

const rearmFailedIPFSPins = `-- name: RearmFailedIPFSPins :execrows
UPDATE media_ipfs_pins
SET state = CASE WHEN cid = '' THEN 'pending' ELSE 'unpinning' END,
    attempts = 0, next_attempt_at = now(), last_error = '', updated_at = now()
WHERE object_key IN (
    SELECT object_key FROM media_ipfs_pins
    WHERE state = 'failed'
    ORDER BY updated_at
    LIMIT $1
)
`

// Reconciliation re-arm (P19.2): move dead-lettered rows back to an actionable
// state so the worker retries them, bounded per scan. The discriminator is the
// CID: a failed PIN never recorded a CID (cid = ”) so it re-arms to 'pending'
// (add+pin again); a failed UNPIN was previously pinned (cid <> ”) so it re-arms
// to 'unpinning' (retry the removal — dropping an unpin would be a privacy
// regression). next_attempt_at = now() makes them immediately claimable.
func (q *Queries) RearmFailedIPFSPins(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, rearmFailedIPFSPins, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const repinIPFSObject = `-- name: RepinIPFSObject :exec
INSERT INTO media_ipfs_pins (object_key, media_class, video_id)
VALUES ($1, $2, $3)
ON CONFLICT (object_key) DO UPDATE
SET media_class     = EXCLUDED.media_class,
    video_id        = EXCLUDED.video_id,
    state           = 'pending',
    attempts        = 0,
    next_attempt_at = now(),
    last_error      = '',
    updated_at      = now()
`

type RepinIPFSObjectParams struct {
	ObjectKey  string      `json:"object_key"`
	MediaClass string      `json:"media_class"`
	VideoID    pgtype.UUID `json:"video_id"`
}

// Force-(re)arm a pin intent for a wholesale-replaced transcode output (P19.4).
// The HLS tree (object_key streaming-playlists/<id>/, trailing slash = directory
// intent) and the VP9/WebM alternate keep a STABLE object_key across re-transcodes
// while their content — and therefore their CID — is replaced in full ('0039'
// wholesale-replace). Unlike UpsertIPFSPinIntent (which leaves a live 'pinned' row
// untouched, correct for stable content), this ALWAYS moves the row back to
// 'pending' so the worker re-adds the new tree and swaps the CID. The existing
// cid/car_root is PRESERVED (not reset) so the worker can reference-check and unpin
// the superseded root after the new add succeeds. A brand-new object_key is
// inserted 'pending'. Called ONLY from the transcode-completion hook for an
// ELIGIBLE (public+published) video — the privacy gate is re-checked there, so a
// private/deleted video never reaches this and no non-public tree is ever armed.
func (q *Queries) RepinIPFSObject(ctx context.Context, arg RepinIPFSObjectParams) error {
	_, err := q.db.Exec(ctx, repinIPFSObject, arg.ObjectKey, arg.MediaClass, arg.VideoID)
	return err
}

const rescheduleIPFSPin = `-- name: RescheduleIPFSPin :exec
UPDATE media_ipfs_pins
SET attempts = attempts + 1, next_attempt_at = $2, last_error = $3, updated_at = now()
WHERE object_key = $1
`

type RescheduleIPFSPinParams struct {
	ObjectKey     string    `json:"object_key"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
}

// Transient retry with backoff: leave the row in WHATEVER actionable state it is
// currently in (pending or unpinning) and push next_attempt_at out so a later drain
// retries it. Deliberately state-agnostic — it never advances to a terminal state,
// so a concurrent privacy flip that re-directed the row (pending↔unpinning) is
// preserved and simply retried in the newer direction; a failed pin never recorded
// a CID, so a re-directed unpin of it is a harmless node no-op.
func (q *Queries) RescheduleIPFSPin(ctx context.Context, arg RescheduleIPFSPinParams) error {
	_, err := q.db.Exec(ctx, rescheduleIPFSPin, arg.ObjectKey, arg.NextAttemptAt, arg.LastError)
	return err
}

const sweepIneligibleIPFSPins = `-- name: SweepIneligibleIPFSPins :execrows
WITH ineligible AS (
    SELECT p.object_key
    FROM media_ipfs_pins p
    JOIN videos v ON v.id = p.video_id
    JOIN channels c ON c.id = v.channel_id
    JOIN users u ON u.id = c.owner_id
    WHERE p.video_id IS NOT NULL
      AND p.state IN ('pinned', 'pending')
      AND (v.privacy <> 'public' OR v.state <> 'published' OR u.unlisted)

    UNION

    SELECT p.object_key
    FROM media_ipfs_pins p
    JOIN users u ON u.id = p.owner_user_id
    WHERE p.owner_user_id IS NOT NULL
      AND p.video_id IS NULL
      AND p.state IN ('pinned', 'pending')
      AND (NOT u.is_active OR u.deleted_at IS NOT NULL OR u.unlisted)

    LIMIT $1
)
UPDATE media_ipfs_pins
SET state = 'unpinning', attempts = 0, next_attempt_at = now(), last_error = '', updated_at = now()
WHERE object_key IN (SELECT object_key FROM ineligible)
`

// Periodic eligibility BACKSTOP (P19 round-2 audit, MAJOR): flip to 'unpinning'
// every live (pinned/pending) mirror row whose CURRENT committed visibility facts
// make it INELIGIBLE — the set-based safety net that converges the mirror on ANY
// missed enqueue (a crashed re-eval job, a toggle that raced a worker, or a future
// eligibility-rule change), mirroring the backfill catalog join (ipfs_backfill.sql)
// in reverse. This closes the whole class rather than any single trigger.
//   - video-derived rows (video_id set): ineligible when the parent video is not
//     public+published OR its owner is unlisted (unlisted is private for mirroring,
//     spec §7). A deleted video/owner FK-nulls video_id (handled by the delete path).
//   - identity-image rows (owner_user_id set, video_id NULL): ineligible when the
//     owner is inactive (deactivated/soft-deleted) OR unlisted.
//
// The worker's reference-checked node removal still runs when it drains the flipped
// 'unpinning' row; this only re-arms the ledger. Playlist-cover rows carry no
// provenance columns and are re-evaluated by their own EnqueuePlaylistCover hook, so
// they are deliberately out of this sweep's scope. Bounded per scan.
func (q *Queries) SweepIneligibleIPFSPins(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, sweepIneligibleIPFSPins, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIPFSPinIntent = `-- name: UpsertIPFSPinIntent :one

INSERT INTO media_ipfs_pins (object_key, media_class, video_id, owner_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (object_key) DO UPDATE
SET media_class   = EXCLUDED.media_class,
    video_id      = EXCLUDED.video_id,
    owner_user_id = EXCLUDED.owner_user_id,
    state = CASE
        WHEN media_ipfs_pins.state IN ('failed', 'unpinned', 'unpinning') THEN 'pending'
        ELSE media_ipfs_pins.state
    END,
    attempts = CASE
        WHEN media_ipfs_pins.state IN ('failed', 'unpinned', 'unpinning') THEN 0
        ELSE media_ipfs_pins.attempts
    END,
    next_attempt_at = CASE
        WHEN media_ipfs_pins.state IN ('failed', 'unpinned', 'unpinning') THEN now()
        ELSE media_ipfs_pins.next_attempt_at
    END,
    last_error = CASE
        WHEN media_ipfs_pins.state IN ('failed', 'unpinned', 'unpinning') THEN ''
        ELSE media_ipfs_pins.last_error
    END,
    updated_at = now()
RETURNING object_key, media_class, cid, car_root, byte_size, state, attempts, next_attempt_at, last_error, video_id, owner_user_id, created_at, updated_at, network
`

type UpsertIPFSPinIntentParams struct {
	ObjectKey   string      `json:"object_key"`
	MediaClass  string      `json:"media_class"`
	VideoID     pgtype.UUID `json:"video_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

// IPFS mirror pin ledger + durable pin/unpin queue (migration 0071, fix_plan
// P19.1, .ralph/specs/ipfs-media.md). The mirror is a SIDECAR: these queries only
// ever touch already-public objects (the eligibility gate lives in the enqueue
// helper, P19.2). states: pending → pinned | failed, and unpinning → unpinned for
// the delete/GC path. Keyed by object_key (the authoritative storage.Backend key).
// Enqueue (or re-arm) a pin intent for one storage object. Keyed on object_key so
// a class that changes its key (e.g. re-uploaded avatar with a new extension)
// lands as a new row and the old key is unpinned separately. A previously-terminal
// row (failed / unpinned / mid-unpin) is re-armed to pending; a live pinned/pending
// row is left as-is (idempotent: re-enqueue of an unchanged live pin is a no-op).
func (q *Queries) UpsertIPFSPinIntent(ctx context.Context, arg UpsertIPFSPinIntentParams) (MediaIpfsPin, error) {
	row := q.db.QueryRow(ctx, upsertIPFSPinIntent,
		arg.ObjectKey,
		arg.MediaClass,
		arg.VideoID,
		arg.OwnerUserID,
	)
	var i MediaIpfsPin
	err := row.Scan(
		&i.ObjectKey,
		&i.MediaClass,
		&i.Cid,
		&i.CarRoot,
		&i.ByteSize,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.VideoID,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}
