// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_gc.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listAllCaptionKeys = `-- name: ListAllCaptionKeys :many
SELECT storage_key FROM captions
`

func (q *Queries) ListAllCaptionKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllCaptionKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVideoFileKeys = `-- name: ListAllVideoFileKeys :many

SELECT storage_key FROM video_files
`

// Media garbage-collection reference queries. The GC sweep lists stored object
// keys per known prefix and deletes only those with NO database reference. These
// queries return the full set of keys/ids the database currently references, so
// an object not in the set is an orphan (see internal/mediagc).
// Every stored video-file key (originals, thumbnails, storyboards, webm
// alternates). Renditions store a key_prefix, not exact keys, so HLS trees are
// GC'd at the video-id level (ListAllVideoIDs) instead.
func (q *Queries) ListAllVideoFileKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllVideoFileKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVideoIDs = `-- name: ListAllVideoIDs :many
SELECT id FROM videos
`

// Every live video id, used to keep the HLS tree (streaming-playlists/<id>/...)
// of any existing video: a whole tree is orphan only when its video is gone.
func (q *Queries) ListAllVideoIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAllVideoIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistThumbnailRefs = `-- name: ListPlaylistThumbnailRefs :many
SELECT id, thumbnail_ext FROM playlists WHERE thumbnail_ext IS NOT NULL
`

type ListPlaylistThumbnailRefsRow struct {
	ID           uuid.UUID `json:"id"`
	ThumbnailExt *string   `json:"thumbnail_ext"`
}

// id + extension of every playlist that has an uploaded cover, so its
// playlist-thumbnails/<id>.<ext> key can be reconstructed as a live reference.
func (q *Queries) ListPlaylistThumbnailRefs(ctx context.Context) ([]ListPlaylistThumbnailRefsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistThumbnailRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistThumbnailRefsRow
	for rows.Next() {
		var i ListPlaylistThumbnailRefsRow
		if err := rows.Scan(&i.ID, &i.ThumbnailExt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamingPlaylistRefs = `-- name: ListStreamingPlaylistRefs :many
SELECT video_id, master_key FROM streaming_playlists
`

type ListStreamingPlaylistRefsRow struct {
	VideoID   uuid.UUID `json:"video_id"`
	MasterKey string    `json:"master_key"`
}

// video id + master key of every recorded streaming playlist, so the GC can
// tell which HLS GENERATION (streaming-playlists/<id>/rN/ vs the legacy
// in-place layout) is the live one after a source replacement (config-parity
// W14). Failed playlists carry master_key ” and yield no live generation.
func (q *Queries) ListStreamingPlaylistRefs(ctx context.Context) ([]ListStreamingPlaylistRefsRow, error) {
	rows, err := q.db.Query(ctx, listStreamingPlaylistRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamingPlaylistRefsRow
	for rows.Next() {
		var i ListStreamingPlaylistRefsRow
		if err := rows.Scan(&i.VideoID, &i.MasterKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
