// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountActorKey struct {
	UserID        uuid.UUID `json:"user_id"`
	PublicKeyPem  string    `json:"public_key_pem"`
	PrivateKeyPem string    `json:"private_key_pem"`
	CreatedAt     time.Time `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID   `json:"id"`
	Action     string      `json:"action"`
	Result     string      `json:"result"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Reason     string      `json:"reason"`
	RequestID  string      `json:"request_id"`
	OccurredAt time.Time   `json:"occurred_at"`
}

type BlockedInstance struct {
	Domain    string      `json:"domain"`
	Reason    string      `json:"reason"`
	BlockedBy pgtype.UUID `json:"blocked_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type Caption struct {
	ID         uuid.UUID `json:"id"`
	VideoID    uuid.UUID `json:"video_id"`
	Language   string    `json:"language"`
	Label      string    `json:"label"`
	StorageKey string    `json:"storage_key"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Channel struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ChannelActorKey struct {
	ChannelID     uuid.UUID `json:"channel_id"`
	PublicKeyPem  string    `json:"public_key_pem"`
	PrivateKeyPem string    `json:"private_key_pem"`
	CreatedAt     time.Time `json:"created_at"`
}

type ChannelFollow struct {
	FollowerID uuid.UUID `json:"follower_id"`
	ChannelID  uuid.UUID `json:"channel_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type ChannelImage struct {
	ChannelID   uuid.UUID `json:"channel_id"`
	Kind        string    `json:"kind"`
	StorageKey  string    `json:"storage_key"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Comment struct {
	ID        uuid.UUID   `json:"id"`
	VideoID   uuid.UUID   `json:"video_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Body      string      `json:"body"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	ParentID  pgtype.UUID `json:"parent_id"`
}

type Conversation struct {
	ID        uuid.UUID `json:"id"`
	DmKey     *string   `json:"dm_key"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ConversationParticipant struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type FederationDelivery struct {
	ID                   uuid.UUID   `json:"id"`
	InboxUrl             string      `json:"inbox_url"`
	Payload              []byte      `json:"payload"`
	SigningChannelID     pgtype.UUID `json:"signing_channel_id"`
	SigningChannelHandle string      `json:"signing_channel_handle"`
	State                string      `json:"state"`
	Attempts             int32       `json:"attempts"`
	NextAttemptAt        time.Time   `json:"next_attempt_at"`
	LastError            string      `json:"last_error"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	SigningUserID        pgtype.UUID `json:"signing_user_id"`
	SigningUsername      string      `json:"signing_username"`
}

type FederationInboxActivity struct {
	ActivityID string    `json:"activity_id"`
	ReceivedAt time.Time `json:"received_at"`
}

type LiveStream struct {
	ID            uuid.UUID `json:"id"`
	ChannelID     uuid.UUID `json:"channel_id"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Privacy       string    `json:"privacy"`
	State         string    `json:"state"`
	Permanent     bool      `json:"permanent"`
	StreamKeyHash string    `json:"stream_key_hash"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Message struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Body           string    `json:"body"`
	CreatedAt      time.Time `json:"created_at"`
}

type MutedAccount struct {
	MuterID   uuid.UUID `json:"muter_id"`
	MutedID   uuid.UUID `json:"muted_id"`
	CreatedAt time.Time `json:"created_at"`
}

type MutedInstance struct {
	MuterID   uuid.UUID `json:"muter_id"`
	Domain    string    `json:"domain"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Type           string             `json:"type"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	CommentID      pgtype.UUID        `json:"comment_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	CreatedAt      time.Time          `json:"created_at"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	ReportID       pgtype.UUID        `json:"report_id"`
}

type NotificationPref struct {
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	Enabled   bool      `json:"enabled"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Playlist struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Visibility  string    `json:"visibility"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PlaylistItem struct {
	ID         uuid.UUID `json:"id"`
	PlaylistID uuid.UUID `json:"playlist_id"`
	VideoID    uuid.UUID `json:"video_id"`
	Position   int32     `json:"position"`
	AddedAt    time.Time `json:"added_at"`
}

type RegistrationRequest struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Note          string             `json:"note"`
	Status        string             `json:"status"`
	ModeratorNote string             `json:"moderator_note"`
	ReviewedBy    pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type RemoteActor struct {
	ActorUrl          string    `json:"actor_url"`
	ActorType         string    `json:"actor_type"`
	PreferredUsername string    `json:"preferred_username"`
	Domain            string    `json:"domain"`
	InboxUrl          string    `json:"inbox_url"`
	SharedInboxUrl    *string   `json:"shared_inbox_url"`
	PublicKeyPem      string    `json:"public_key_pem"`
	FollowersUrl      string    `json:"followers_url"`
	FetchedAt         time.Time `json:"fetched_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type RemoteChannelFollow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	State             string    `json:"state"`
	FollowActivityUrl string    `json:"follow_activity_url"`
	CreatedAt         time.Time `json:"created_at"`
}

type RemoteFollow struct {
	ChannelID         uuid.UUID `json:"channel_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	State             string    `json:"state"`
	FollowActivityUrl string    `json:"follow_activity_url"`
	CreatedAt         time.Time `json:"created_at"`
}

type RemoteVideo struct {
	ID              uuid.UUID          `json:"id"`
	ObjectUrl       string             `json:"object_url"`
	RemoteActorUrl  string             `json:"remote_actor_url"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	DurationSeconds *int32             `json:"duration_seconds"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	WatchUrl        string             `json:"watch_url"`
	StreamUrl       *string            `json:"stream_url"`
	ThumbnailKey    *string            `json:"thumbnail_key"`
	FetchedAt       time.Time          `json:"fetched_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type Report struct {
	ID             uuid.UUID          `json:"id"`
	ReporterID     uuid.UUID          `json:"reporter_id"`
	TargetType     string             `json:"target_type"`
	VideoID        pgtype.UUID        `json:"video_id"`
	CommentID      pgtype.UUID        `json:"comment_id"`
	Reason         string             `json:"reason"`
	Status         string             `json:"status"`
	ModeratorNote  string             `json:"moderator_note"`
	ResolvedBy     pgtype.UUID        `json:"resolved_by"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	ReportedUserID pgtype.UUID        `json:"reported_user_id"`
}

type SavedVideo struct {
	UserID    uuid.UUID `json:"user_id"`
	VideoID   uuid.UUID `json:"video_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt   time.Time          `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type StreamingPlaylist struct {
	VideoID   uuid.UUID `json:"video_id"`
	MasterKey string    `json:"master_key"`
	State     string    `json:"state"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TranscodeJob struct {
	ID            uuid.UUID `json:"id"`
	VideoID       uuid.UUID `json:"video_id"`
	SourceKey     string    `json:"source_key"`
	State         string    `json:"state"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	PasswordHash      string    `json:"password_hash"`
	Role              string    `json:"role"`
	EmailVerified     bool      `json:"email_verified"`
	IsActive          bool      `json:"is_active"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	DisplayName       string    `json:"display_name"`
	Bio               string    `json:"bio"`
	StorageQuotaBytes *int64    `json:"storage_quota_bytes"`
	Unlisted          bool      `json:"unlisted"`
	BypassQuarantine  bool      `json:"bypass_quarantine"`
}

type UserBlock struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserImage struct {
	UserID      uuid.UUID `json:"user_id"`
	Kind        string    `json:"kind"`
	StorageKey  string    `json:"storage_key"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Video struct {
	ID          uuid.UUID          `json:"id"`
	ChannelID   uuid.UUID          `json:"channel_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Privacy     string             `json:"privacy"`
	State       string             `json:"state"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	Category    *string            `json:"category"`
	Language    *string            `json:"language"`
	License     *string            `json:"license"`
	PublishAt   pgtype.Timestamptz `json:"publish_at"`
}

type VideoBlock struct {
	VideoID   uuid.UUID   `json:"video_id"`
	Reason    string      `json:"reason"`
	BlockedBy pgtype.UUID `json:"blocked_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type VideoFile struct {
	ID           uuid.UUID `json:"id"`
	VideoID      uuid.UUID `json:"video_id"`
	Kind         string    `json:"kind"`
	StorageKey   string    `json:"storage_key"`
	ContentType  string    `json:"content_type"`
	OriginalName string    `json:"original_name"`
	SizeBytes    int64     `json:"size_bytes"`
	CreatedAt    time.Time `json:"created_at"`
}

type VideoMetadatum struct {
	VideoID         uuid.UUID `json:"video_id"`
	DurationSeconds *int32    `json:"duration_seconds"`
	Width           *int32    `json:"width"`
	Height          *int32    `json:"height"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type VideoRating struct {
	VideoID   uuid.UUID `json:"video_id"`
	UserID    uuid.UUID `json:"user_id"`
	Rating    string    `json:"rating"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type VideoRendition struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	Height    int32     `json:"height"`
	Width     int32     `json:"width"`
	KeyPrefix string    `json:"key_prefix"`
	CreatedAt time.Time `json:"created_at"`
}

type VideoTag struct {
	VideoID   uuid.UUID `json:"video_id"`
	Tag       string    `json:"tag"`
	CreatedAt time.Time `json:"created_at"`
}

type VideoViewCount struct {
	VideoID   uuid.UUID `json:"video_id"`
	Views     int64     `json:"views"`
	UpdatedAt time.Time `json:"updated_at"`
}

type VideoViewDay struct {
	VideoID uuid.UUID   `json:"video_id"`
	Day     pgtype.Date `json:"day"`
	Views   int64       `json:"views"`
}

type WatchHistory struct {
	UserID          uuid.UUID `json:"user_id"`
	VideoID         uuid.UUID `json:"video_id"`
	PositionSeconds int32     `json:"position_seconds"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type WatchedWord struct {
	ID        uuid.UUID   `json:"id"`
	Word      string      `json:"word"`
	CreatedBy pgtype.UUID `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type WatchedWordMatch struct {
	ID            uuid.UUID   `json:"id"`
	WatchedWordID uuid.UUID   `json:"watched_word_id"`
	CommentID     pgtype.UUID `json:"comment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	VideoID       pgtype.UUID `json:"video_id"`
}
