// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountActorKey struct {
	UserID        uuid.UUID `json:"user_id"`
	PublicKeyPem  string    `json:"public_key_pem"`
	PrivateKeyPem string    `json:"private_key_pem"`
	CreatedAt     time.Time `json:"created_at"`
}

type AccountExport struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	State         string             `json:"state"`
	StorageKey    string             `json:"storage_key"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt time.Time          `json:"next_attempt_at"`
	LastError     string             `json:"last_error"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type AtprotoAccount struct {
	UserID            uuid.UUID          `json:"user_id"`
	Handle            string             `json:"handle"`
	Did               string             `json:"did"`
	PdsUrl            string             `json:"pds_url"`
	AppPasswordSealed string             `json:"app_password_sealed"`
	AutoPost          bool               `json:"auto_post"`
	CreatedAt         time.Time          `json:"created_at"`
	LastPostedAt      pgtype.Timestamptz `json:"last_posted_at"`
}

type AtprotoPost struct {
	ID            uuid.UUID `json:"id"`
	VideoID       uuid.UUID `json:"video_id"`
	State         string    `json:"state"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	Error         string    `json:"error"`
	PostUri       string    `json:"post_uri"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Low-volume security audit ledger. Do not store routine content activity, raw payloads, secrets, free-form content, signed URLs, or process output.
type AuditLog struct {
	ID            uuid.UUID   `json:"id"`
	Action        string      `json:"action"`
	Result        string      `json:"result"`
	ActorID       pgtype.UUID `json:"actor_id"`
	Reason        string      `json:"reason"`
	RequestID     string      `json:"request_id"`
	OccurredAt    time.Time   `json:"occurred_at"`
	SchemaVersion int16       `json:"schema_version"`
	Domain        string      `json:"domain"`
	ActorKind     string      `json:"actor_kind"`
	ActorRole     string      `json:"actor_role"`
	ResourceType  string      `json:"resource_type"`
	ResourceID    string      `json:"resource_id"`
	CorrelationID string      `json:"correlation_id"`
	TraceID       string      `json:"trace_id"`
	PipelineRunID pgtype.UUID `json:"pipeline_run_id"`
	JobID         pgtype.UUID `json:"job_id"`
	// Allowlisted, bounded scalar metadata only (application-enforced; 8 KiB DB backstop).
	Metadata []byte `json:"metadata"`
	// Allowlisted safe before/after scalar changes only (application-enforced; 8 KiB DB backstop).
	Changes []byte `json:"changes"`
}

type BlockedInstance struct {
	Domain    string      `json:"domain"`
	Reason    string      `json:"reason"`
	BlockedBy pgtype.UUID `json:"blocked_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type Caption struct {
	ID         uuid.UUID `json:"id"`
	VideoID    uuid.UUID `json:"video_id"`
	Language   string    `json:"language"`
	Label      string    `json:"label"`
	StorageKey string    `json:"storage_key"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CaptionJob struct {
	ID              uuid.UUID `json:"id"`
	VideoID         uuid.UUID `json:"video_id"`
	Language        string    `json:"language"`
	State           string    `json:"state"`
	Error           string    `json:"error"`
	Attempts        int32     `json:"attempts"`
	NextAttemptAt   time.Time `json:"next_attempt_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Stage           string    `json:"stage"`
	ProgressPercent int16     `json:"progress_percent"`
}

type Channel struct {
	ID                 uuid.UUID `json:"id"`
	OwnerID            uuid.UUID `json:"owner_id"`
	Handle             string    `json:"handle"`
	DisplayName        string    `json:"display_name"`
	Description        string    `json:"description"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ActivitypubEnabled bool      `json:"activitypub_enabled"`
	AtprotoEnabled     bool      `json:"atproto_enabled"`
}

type ChannelActorKey struct {
	ChannelID     uuid.UUID `json:"channel_id"`
	PublicKeyPem  string    `json:"public_key_pem"`
	PrivateKeyPem string    `json:"private_key_pem"`
	CreatedAt     time.Time `json:"created_at"`
}

type ChannelFollow struct {
	FollowerID          uuid.UUID `json:"follower_id"`
	ChannelID           uuid.UUID `json:"channel_id"`
	CreatedAt           time.Time `json:"created_at"`
	NotificationSetting string    `json:"notification_setting"`
}

type ChannelFollowBack struct {
	ChannelID         uuid.UUID `json:"channel_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	FollowActivityUrl string    `json:"follow_activity_url"`
	State             string    `json:"state"`
	CreatedAt         time.Time `json:"created_at"`
}

type ChannelImage struct {
	ChannelID   uuid.UUID `json:"channel_id"`
	Kind        string    `json:"kind"`
	StorageKey  string    `json:"storage_key"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ChannelMember struct {
	ChannelID uuid.UUID   `json:"channel_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type ChannelSync struct {
	ID                 uuid.UUID          `json:"id"`
	ChannelID          uuid.UUID          `json:"channel_id"`
	UserID             uuid.UUID          `json:"user_id"`
	ExternalChannelUrl string             `json:"external_channel_url"`
	State              string             `json:"state"`
	LastSyncAt         pgtype.Timestamptz `json:"last_sync_at"`
	LastError          string             `json:"last_error"`
	NextRunAt          time.Time          `json:"next_run_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type ChannelSyncSeen struct {
	SyncID     uuid.UUID `json:"sync_id"`
	ExternalID string    `json:"external_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Comment struct {
	ID               uuid.UUID          `json:"id"`
	VideoID          uuid.UUID          `json:"video_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Body             string             `json:"body"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ParentID         pgtype.UUID        `json:"parent_id"`
	RemoteActorUrl   *string            `json:"remote_actor_url"`
	RemoteAuthorName *string            `json:"remote_author_name"`
	RemoteObjectUrl  *string            `json:"remote_object_url"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Hearted          bool               `json:"hearted"`
}

type Conversation struct {
	ID        uuid.UUID `json:"id"`
	DmKey     *string   `json:"dm_key"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Encrypted bool      `json:"encrypted"`
}

type ConversationParticipant struct {
	ConversationID    uuid.UUID   `json:"conversation_id"`
	UserID            uuid.UUID   `json:"user_id"`
	LastReadMessageID pgtype.UUID `json:"last_read_message_id"`
}

type DonationAddress struct {
	ID                    uuid.UUID          `json:"id"`
	OwnerID               uuid.UUID          `json:"owner_id"`
	ChannelID             pgtype.UUID        `json:"channel_id"`
	Network               string             `json:"network"`
	Address               string             `json:"address"`
	Label                 string             `json:"label"`
	Verified              bool               `json:"verified"`
	VerificationNonce     *string            `json:"verification_nonce"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
	CreatedAt             time.Time          `json:"created_at"`
}

type E2eeDevice struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	DeviceName  string    `json:"device_name"`
	IdentityKey string    `json:"identity_key"`
	SigningKey  string    `json:"signing_key"`
	CreatedAt   time.Time `json:"created_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}

type E2eeMessage struct {
	ID                uuid.UUID          `json:"id"`
	ConversationID    uuid.UUID          `json:"conversation_id"`
	SenderDeviceID    uuid.UUID          `json:"sender_device_id"`
	RecipientDeviceID uuid.UUID          `json:"recipient_device_id"`
	MessageType       int32              `json:"message_type"`
	Ciphertext        string             `json:"ciphertext"`
	CreatedAt         time.Time          `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

type E2eeOneTimeKey struct {
	ID        uuid.UUID          `json:"id"`
	DeviceID  uuid.UUID          `json:"device_id"`
	KeyID     string             `json:"key_id"`
	Key       string             `json:"key"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type FederationDelivery struct {
	ID                   uuid.UUID   `json:"id"`
	InboxUrl             string      `json:"inbox_url"`
	Payload              []byte      `json:"payload"`
	SigningChannelID     pgtype.UUID `json:"signing_channel_id"`
	SigningChannelHandle string      `json:"signing_channel_handle"`
	State                string      `json:"state"`
	Attempts             int32       `json:"attempts"`
	NextAttemptAt        time.Time   `json:"next_attempt_at"`
	LastError            string      `json:"last_error"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	SigningUserID        pgtype.UUID `json:"signing_user_id"`
	SigningUsername      string      `json:"signing_username"`
}

type FederationInboxActivity struct {
	ActivityID string    `json:"activity_id"`
	ReceivedAt time.Time `json:"received_at"`
}

type ImportJob struct {
	ID            uuid.UUID `json:"id"`
	VideoID       uuid.UUID `json:"video_id"`
	Url           string    `json:"url"`
	State         string    `json:"state"`
	Error         string    `json:"error"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Resolver      string    `json:"resolver"`
	Stage         string    `json:"stage"`
}

type InstanceDocument struct {
	Name      string      `json:"name"`
	Body      string      `json:"body"`
	Sha256    string      `json:"sha256"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type InstanceIdentity struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

type InstanceImage struct {
	Kind        string    `json:"kind"`
	StorageKey  string    `json:"storage_key"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type InstanceSetting struct {
	Key       string      `json:"key"`
	Value     string      `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type JobEvent struct {
	Cursor          int64       `json:"cursor"`
	ID              uuid.UUID   `json:"id"`
	SchemaVersion   int16       `json:"schema_version"`
	JobID           uuid.UUID   `json:"job_id"`
	PipelineRunID   pgtype.UUID `json:"pipeline_run_id"`
	Kind            string      `json:"kind"`
	State           string      `json:"state"`
	Stage           string      `json:"stage"`
	ProgressPercent *int16      `json:"progress_percent"`
	Attempt         int32       `json:"attempt"`
	WorkerID        string      `json:"worker_id"`
	Message         string      `json:"message"`
	Metadata        []byte      `json:"metadata"`
	RequestID       string      `json:"request_id"`
	CorrelationID   string      `json:"correlation_id"`
	TraceID         string      `json:"trace_id"`
	OccurredAt      time.Time   `json:"occurred_at"`
}

type JobRun struct {
	ID                uuid.UUID          `json:"id"`
	PipelineRunID     pgtype.UUID        `json:"pipeline_run_id"`
	ParentJobID       pgtype.UUID        `json:"parent_job_id"`
	Type              string             `json:"type"`
	Queue             string             `json:"queue"`
	SourceID          string             `json:"source_id"`
	State             string             `json:"state"`
	Stage             string             `json:"stage"`
	ProgressPercent   *int16             `json:"progress_percent"`
	Priority          int32              `json:"priority"`
	Attempt           int32              `json:"attempt"`
	MaxAttempts       *int32             `json:"max_attempts"`
	IdempotencyKey    string             `json:"idempotency_key"`
	ActorID           pgtype.UUID        `json:"actor_id"`
	ResourceType      string             `json:"resource_type"`
	ResourceID        string             `json:"resource_id"`
	RequestID         string             `json:"request_id"`
	CorrelationID     string             `json:"correlation_id"`
	TraceID           string             `json:"trace_id"`
	WorkerID          string             `json:"worker_id"`
	LeaseToken        pgtype.UUID        `json:"lease_token"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
	HeartbeatAt       pgtype.Timestamptz `json:"heartbeat_at"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
	InputMetadata     []byte             `json:"input_metadata"`
	OutputMetadata    []byte             `json:"output_metadata"`
	ErrorClass        string             `json:"error_class"`
	ErrorCode         string             `json:"error_code"`
	ErrorDetail       string             `json:"error_detail"`
	ErrorRetryable    *bool              `json:"error_retryable"`
	CreatedAt         time.Time          `json:"created_at"`
	ClaimedAt         pgtype.Timestamptz `json:"claimed_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
}

type LinkPreview struct {
	UrlHash     string             `json:"url_hash"`
	Url         string             `json:"url"`
	State       string             `json:"state"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	ImageUrl    string             `json:"image_url"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type LiveStream struct {
	ID            uuid.UUID          `json:"id"`
	ChannelID     uuid.UUID          `json:"channel_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Privacy       string             `json:"privacy"`
	State         string             `json:"state"`
	Permanent     bool               `json:"permanent"`
	StreamKeyHash string             `json:"stream_key_hash"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	ReplayEnabled bool               `json:"replay_enabled"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
}

type MediaIpfsPin struct {
	ObjectKey     string      `json:"object_key"`
	MediaClass    string      `json:"media_class"`
	Cid           string      `json:"cid"`
	CarRoot       string      `json:"car_root"`
	ByteSize      int64       `json:"byte_size"`
	State         string      `json:"state"`
	Attempts      int32       `json:"attempts"`
	NextAttemptAt time.Time   `json:"next_attempt_at"`
	LastError     string      `json:"last_error"`
	VideoID       pgtype.UUID `json:"video_id"`
	OwnerUserID   pgtype.UUID `json:"owner_user_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	Network       string      `json:"network"`
	TargetNetwork *string     `json:"target_network"`
}

type MediaIpfsUserReeval struct {
	UserID        uuid.UUID `json:"user_id"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Message struct {
	ID                 uuid.UUID          `json:"id"`
	ConversationID     uuid.UUID          `json:"conversation_id"`
	SenderID           uuid.UUID          `json:"sender_id"`
	Body               string             `json:"body"`
	CreatedAt          time.Time          `json:"created_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	LinkPreviewUrlHash *string            `json:"link_preview_url_hash"`
}

type MessageAttachment struct {
	ID             uuid.UUID   `json:"id"`
	ConversationID uuid.UUID   `json:"conversation_id"`
	UploaderID     uuid.UUID   `json:"uploader_id"`
	MessageID      pgtype.UUID `json:"message_id"`
	Kind           string      `json:"kind"`
	ContentType    string      `json:"content_type"`
	Filename       string      `json:"filename"`
	SizeBytes      int64       `json:"size_bytes"`
	StorageKey     string      `json:"storage_key"`
	CreatedAt      time.Time   `json:"created_at"`
	Width          *int32      `json:"width"`
	Height         *int32      `json:"height"`
}

type MfaRecoveryCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type MutedAccount struct {
	MuterID   uuid.UUID `json:"muter_id"`
	MutedID   uuid.UUID `json:"muted_id"`
	CreatedAt time.Time `json:"created_at"`
}

type MutedInstance struct {
	MuterID   uuid.UUID `json:"muter_id"`
	Domain    string    `json:"domain"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Type           string             `json:"type"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	CommentID      pgtype.UUID        `json:"comment_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	CreatedAt      time.Time          `json:"created_at"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	ReportID       pgtype.UUID        `json:"report_id"`
}

type NotificationPref struct {
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	Enabled   bool      `json:"enabled"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OauthIdentity struct {
	ID        uuid.UUID `json:"id"`
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	UserID    uuid.UUID `json:"user_id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	Handle    *string   `json:"handle"`
}

type OwnerClaimToken struct {
	ID        bool               `json:"id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt time.Time          `json:"created_at"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type PeertubeImportLedger struct {
	ID           uuid.UUID   `json:"id"`
	EntityKind   string      `json:"entity_kind"`
	SourceID     string      `json:"source_id"`
	VidraID      pgtype.UUID `json:"vidra_id"`
	Status       string      `json:"status"`
	Note         string      `json:"note"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	SourceValue  int64       `json:"source_value"`
	AppliedValue string      `json:"applied_value"`
}

type PeertubeImportRun struct {
	ID                        uuid.UUID          `json:"id"`
	Mode                      string             `json:"mode"`
	State                     string             `json:"state"`
	ConflictPolicy            string             `json:"conflict_policy"`
	SourceVersion             *int32             `json:"source_version"`
	Progress                  []byte             `json:"progress"`
	Error                     string             `json:"error"`
	StartedBy                 pgtype.UUID        `json:"started_by"`
	Attempts                  int32              `json:"attempts"`
	NextAttemptAt             time.Time          `json:"next_attempt_at"`
	CreatedAt                 time.Time          `json:"created_at"`
	UpdatedAt                 time.Time          `json:"updated_at"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	FinishedAt                pgtype.Timestamptz `json:"finished_at"`
	AcknowledgedSchemaVersion *int32             `json:"acknowledged_schema_version"`
	ErrorCode                 string             `json:"error_code"`
	SourceAuthoritative       bool               `json:"source_authoritative"`
}

type PipelineRun struct {
	ID             uuid.UUID          `json:"id"`
	SchemaVersion  int16              `json:"schema_version"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     string             `json:"resource_id"`
	RequestID      string             `json:"request_id"`
	CorrelationID  string             `json:"correlation_id"`
	TraceID        string             `json:"trace_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	InputMetadata  []byte             `json:"input_metadata"`
	OutputMetadata []byte             `json:"output_metadata"`
	CreatedAt      time.Time          `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Playlist struct {
	ID           uuid.UUID `json:"id"`
	OwnerID      uuid.UUID `json:"owner_id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Visibility   string    `json:"visibility"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ThumbnailExt *string   `json:"thumbnail_ext"`
}

type PlaylistItem struct {
	ID         uuid.UUID `json:"id"`
	PlaylistID uuid.UUID `json:"playlist_id"`
	VideoID    uuid.UUID `json:"video_id"`
	Position   int32     `json:"position"`
	AddedAt    time.Time `json:"added_at"`
}

type QoeEvent struct {
	ID              uuid.UUID   `json:"id"`
	ReceivedAt      time.Time   `json:"received_at"`
	EventType       string      `json:"event_type"`
	DeliverySource  string      `json:"delivery_source"`
	Engine          string      `json:"engine"`
	PackagingFormat string      `json:"packaging_format"`
	VideoID         pgtype.UUID `json:"video_id"`
	LiveStreamID    pgtype.UUID `json:"live_stream_id"`
	SessionID       pgtype.UUID `json:"session_id"`
	SessionVerified bool        `json:"session_verified"`
	ViewerDigest    string      `json:"viewer_digest"`
	TtffMs          *int32      `json:"ttff_ms"`
	RebufferMs      *int32      `json:"rebuffer_ms"`
	RenditionHeight *int32      `json:"rendition_height"`
	ErrorClass      *string     `json:"error_class"`
	Metadata        []byte      `json:"metadata"`
}

type QoeRollup struct {
	HourBucket         time.Time `json:"hour_bucket"`
	DeliverySource     string    `json:"delivery_source"`
	Engine             string    `json:"engine"`
	PackagingFormat    string    `json:"packaging_format"`
	EventCount         int64     `json:"event_count"`
	StartCount         int64     `json:"start_count"`
	RebufferCount      int64     `json:"rebuffer_count"`
	BitrateSwitchCount int64     `json:"bitrate_switch_count"`
	ErrorCount         int64     `json:"error_count"`
	VerifiedCount      int64     `json:"verified_count"`
	TtffP50Ms          *int32    `json:"ttff_p50_ms"`
	TtffP95Ms          *int32    `json:"ttff_p95_ms"`
	TtffP99Ms          *int32    `json:"ttff_p99_ms"`
	RebufferP50Ms      *int32    `json:"rebuffer_p50_ms"`
	RebufferP95Ms      *int32    `json:"rebuffer_p95_ms"`
	RebufferP99Ms      *int32    `json:"rebuffer_p99_ms"`
	RebufferTotalMs    int64     `json:"rebuffer_total_ms"`
	HistogramVersion   int16     `json:"histogram_version"`
	TtffHistogram      []int64   `json:"ttff_histogram"`
	RebufferHistogram  []int64   `json:"rebuffer_histogram"`
	ErrorCounts        []byte    `json:"error_counts"`
	ComputedAt         time.Time `json:"computed_at"`
}

type RegistrationRequest struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Note          string             `json:"note"`
	Status        string             `json:"status"`
	ModeratorNote string             `json:"moderator_note"`
	ReviewedBy    pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type RemoteActor struct {
	ActorUrl          string    `json:"actor_url"`
	ActorType         string    `json:"actor_type"`
	PreferredUsername string    `json:"preferred_username"`
	Domain            string    `json:"domain"`
	InboxUrl          string    `json:"inbox_url"`
	SharedInboxUrl    *string   `json:"shared_inbox_url"`
	PublicKeyPem      string    `json:"public_key_pem"`
	FollowersUrl      string    `json:"followers_url"`
	FetchedAt         time.Time `json:"fetched_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type RemoteChannelFollow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	State             string    `json:"state"`
	FollowActivityUrl string    `json:"follow_activity_url"`
	CreatedAt         time.Time `json:"created_at"`
}

type RemoteFollow struct {
	ChannelID         uuid.UUID `json:"channel_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	State             string    `json:"state"`
	FollowActivityUrl string    `json:"follow_activity_url"`
	CreatedAt         time.Time `json:"created_at"`
	ID                uuid.UUID `json:"id"`
}

type RemoteVideo struct {
	ID              uuid.UUID          `json:"id"`
	ObjectUrl       string             `json:"object_url"`
	RemoteActorUrl  string             `json:"remote_actor_url"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	DurationSeconds *int32             `json:"duration_seconds"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	WatchUrl        string             `json:"watch_url"`
	StreamUrl       *string            `json:"stream_url"`
	ThumbnailKey    *string            `json:"thumbnail_key"`
	FetchedAt       time.Time          `json:"fetched_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type RemoteVideoBlock struct {
	RemoteVideoID uuid.UUID   `json:"remote_video_id"`
	Reason        string      `json:"reason"`
	BlockedBy     pgtype.UUID `json:"blocked_by"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Report struct {
	ID                  uuid.UUID          `json:"id"`
	ReporterID          uuid.UUID          `json:"reporter_id"`
	TargetType          string             `json:"target_type"`
	VideoID             pgtype.UUID        `json:"video_id"`
	CommentID           pgtype.UUID        `json:"comment_id"`
	Reason              string             `json:"reason"`
	Status              string             `json:"status"`
	ModeratorNote       string             `json:"moderator_note"`
	ResolvedBy          pgtype.UUID        `json:"resolved_by"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	ReportedUserID      pgtype.UUID        `json:"reported_user_id"`
	RemoteVideoID       pgtype.UUID        `json:"remote_video_id"`
	MessageID           pgtype.UUID        `json:"message_id"`
	MessageBodySnapshot string             `json:"message_body_snapshot"`
}

type SavedVideo struct {
	UserID    uuid.UUID `json:"user_id"`
	VideoID   uuid.UUID `json:"video_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SearchOutbox struct {
	ID            int64     `json:"id"`
	EventID       uuid.UUID `json:"event_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	State         string    `json:"state"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
}

type Session struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt   time.Time          `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type StorageMigration struct {
	ID                uuid.UUID          `json:"id"`
	SourceDesc        string             `json:"source_desc"`
	TargetDesc        string             `json:"target_desc"`
	State             string             `json:"state"`
	ObjectsTotal      int64              `json:"objects_total"`
	ObjectsDone       int64              `json:"objects_done"`
	ObjectsFailed     int64              `json:"objects_failed"`
	LastError         string             `json:"last_error"`
	ObservedCutoverAt pgtype.Timestamptz `json:"observed_cutover_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type StorageMigrationObject struct {
	ObjectKey     string    `json:"object_key"`
	CampaignID    uuid.UUID `json:"campaign_id"`
	State         string    `json:"state"`
	Sha256        string    `json:"sha256"`
	ByteSize      int64     `json:"byte_size"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type StreamingPlaylist struct {
	VideoID   uuid.UUID `json:"video_id"`
	MasterKey string    `json:"master_key"`
	State     string    `json:"state"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Format    string    `json:"format"`
}

type TranscodeJob struct {
	ID            uuid.UUID `json:"id"`
	VideoID       uuid.UUID `json:"video_id"`
	SourceKey     string    `json:"source_key"`
	State         string    `json:"state"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	TranscodeType string    `json:"transcode_type"`
}

type TranscodeStep struct {
	ID              uuid.UUID          `json:"id"`
	TranscodeJobID  uuid.UUID          `json:"transcode_job_id"`
	VideoID         uuid.UUID          `json:"video_id"`
	Format          string             `json:"format"`
	Height          int32              `json:"height"`
	Width           int32              `json:"width"`
	State           string             `json:"state"`
	Stage           string             `json:"stage"`
	ProgressPercent int16              `json:"progress_percent"`
	CreatedAt       time.Time          `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}

type UploadChunk struct {
	UploadID  uuid.UUID `json:"upload_id"`
	N         int32     `json:"n"`
	SizeBytes int64     `json:"size_bytes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UploadSession struct {
	ID              uuid.UUID `json:"id"`
	VideoID         uuid.UUID `json:"video_id"`
	UserID          uuid.UUID `json:"user_id"`
	Filename        string    `json:"filename"`
	TotalSize       int64     `json:"total_size"`
	ChunkSize       int32     `json:"chunk_size"`
	State           string    `json:"state"`
	ExpiresAt       time.Time `json:"expires_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	FileFingerprint string    `json:"file_fingerprint"`
	Purpose         string    `json:"purpose"`
}

type UploadUsageEvent struct {
	ID        int64     `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Bytes     int64     `json:"bytes"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                                 uuid.UUID          `json:"id"`
	Username                           string             `json:"username"`
	Email                              string             `json:"email"`
	PasswordHash                       string             `json:"password_hash"`
	Role                               string             `json:"role"`
	EmailVerified                      bool               `json:"email_verified"`
	IsActive                           bool               `json:"is_active"`
	CreatedAt                          time.Time          `json:"created_at"`
	UpdatedAt                          time.Time          `json:"updated_at"`
	DisplayName                        string             `json:"display_name"`
	Bio                                string             `json:"bio"`
	StorageQuotaBytes                  *int64             `json:"storage_quota_bytes"`
	Unlisted                           bool               `json:"unlisted"`
	BypassQuarantine                   bool               `json:"bypass_quarantine"`
	DeletedAt                          pgtype.Timestamptz `json:"deleted_at"`
	PendingEmailVerification           bool               `json:"pending_email_verification"`
	HistoryEnabled                     bool               `json:"history_enabled"`
	ProfilePublic                      bool               `json:"profile_public"`
	SearchHistoryEnabled               bool               `json:"search_history_enabled"`
	PersonalizedSearchEnabled          bool               `json:"personalized_search_enabled"`
	PersonalizedRecommendationsEnabled bool               `json:"personalized_recommendations_enabled"`
	SensitiveContentPolicy             *string            `json:"sensitive_content_policy"`
	ShowBluesky                        bool               `json:"show_bluesky"`
}

type UserBlock struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserImage struct {
	UserID      uuid.UUID `json:"user_id"`
	Kind        string    `json:"kind"`
	StorageKey  string    `json:"storage_key"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UserMfa struct {
	UserID           uuid.UUID `json:"user_id"`
	TotpSecretSealed string    `json:"totp_secret_sealed"`
	Enabled          bool      `json:"enabled"`
	CreatedAt        time.Time `json:"created_at"`
}

type UserPlayerSetting struct {
	UserID                   uuid.UUID      `json:"user_id"`
	AutoplayNext             bool           `json:"autoplay_next"`
	DefaultSpeed             pgtype.Numeric `json:"default_speed"`
	DefaultQuality           string         `json:"default_quality"`
	CaptionsDefault          bool           `json:"captions_default"`
	TheaterDefault           bool           `json:"theater_default"`
	UpdatedAt                time.Time      `json:"updated_at"`
	VideoCardPreviewsEnabled *bool          `json:"video_card_previews_enabled"`
}

type Video struct {
	ID                    uuid.UUID          `json:"id"`
	ChannelID             uuid.UUID          `json:"channel_id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	Privacy               string             `json:"privacy"`
	State                 string             `json:"state"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	Category              *string            `json:"category"`
	Language              *string            `json:"language"`
	License               *string            `json:"license"`
	PublishAt             pgtype.Timestamptz `json:"publish_at"`
	EmbedPrivacy          string             `json:"embed_privacy"`
	EmbedAllowedDomains   []string           `json:"embed_allowed_domains"`
	IsSensitive           bool               `json:"is_sensitive"`
	CommentsPolicy        string             `json:"comments_policy"`
	DownloadEnabled       bool               `json:"download_enabled"`
	PublishAfterTranscode bool               `json:"publish_after_transcode"`
	PinnedCommentID       pgtype.UUID        `json:"pinned_comment_id"`
	SensitiveReason       string             `json:"sensitive_reason"`
	OriginallyPublishedAt pgtype.Timestamptz `json:"originally_published_at"`
}

type VideoBlock struct {
	VideoID   uuid.UUID   `json:"video_id"`
	Reason    string      `json:"reason"`
	BlockedBy pgtype.UUID `json:"blocked_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type VideoChapter struct {
	VideoID      uuid.UUID `json:"video_id"`
	StartSeconds int32     `json:"start_seconds"`
	Title        string    `json:"title"`
}

// CENC content keys, sealed under DRM_KEY_KEK (internal/secretbox). The plaintext key exists only in process memory; it is never stored in, and never returned from, any queryable column.
type VideoDrmKey struct {
	VideoID uuid.UUID `json:"video_id"`
	// Public CENC key id (KID). Travels in manifests and license requests; names a key rather than being one.
	KeyID uuid.UUID `json:"key_id"`
	// SECRET. secretbox-sealed 16-byte AES content key ("enc:" + base64(nonce||ciphertext)). Never logged, never returned by any API.
	ContentKeySealed string    `json:"content_key_sealed"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type VideoFile struct {
	ID           uuid.UUID `json:"id"`
	VideoID      uuid.UUID `json:"video_id"`
	Kind         string    `json:"kind"`
	StorageKey   string    `json:"storage_key"`
	ContentType  string    `json:"content_type"`
	OriginalName string    `json:"original_name"`
	SizeBytes    int64     `json:"size_bytes"`
	CreatedAt    time.Time `json:"created_at"`
	Sha256       string    `json:"sha256"`
}

type VideoMetadatum struct {
	VideoID         uuid.UUID `json:"video_id"`
	DurationSeconds *int32    `json:"duration_seconds"`
	Width           *int32    `json:"width"`
	Height          *int32    `json:"height"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type VideoPassword struct {
	ID           uuid.UUID `json:"id"`
	VideoID      uuid.UUID `json:"video_id"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type VideoRating struct {
	VideoID   uuid.UUID `json:"video_id"`
	UserID    uuid.UUID `json:"user_id"`
	Rating    string    `json:"rating"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type VideoRendition struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	Height    int32     `json:"height"`
	Width     int32     `json:"width"`
	KeyPrefix string    `json:"key_prefix"`
	CreatedAt time.Time `json:"created_at"`
	SizeBytes int64     `json:"size_bytes"`
}

type VideoStoryboardAttempt struct {
	VideoID       uuid.UUID `json:"video_id"`
	Attempts      int32     `json:"attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	GivenUp       bool      `json:"given_up"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type VideoTag struct {
	VideoID   uuid.UUID `json:"video_id"`
	Tag       string    `json:"tag"`
	CreatedAt time.Time `json:"created_at"`
}

type VideoViewCount struct {
	VideoID   uuid.UUID `json:"video_id"`
	Views     int64     `json:"views"`
	UpdatedAt time.Time `json:"updated_at"`
}

type VideoViewDay struct {
	VideoID uuid.UUID   `json:"video_id"`
	Day     pgtype.Date `json:"day"`
	Views   int64       `json:"views"`
}

type WatchHistory struct {
	UserID          uuid.UUID `json:"user_id"`
	VideoID         uuid.UUID `json:"video_id"`
	PositionSeconds int32     `json:"position_seconds"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type WatchedWord struct {
	ID        uuid.UUID   `json:"id"`
	Word      string      `json:"word"`
	CreatedBy pgtype.UUID `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type WatchedWordMatch struct {
	ID            uuid.UUID   `json:"id"`
	WatchedWordID uuid.UUID   `json:"watched_word_id"`
	CommentID     pgtype.UUID `json:"comment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	VideoID       pgtype.UUID `json:"video_id"`
}
