// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, actor_id, channel_id, video_id, comment_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, actor_id, channel_id, video_id, comment_id, read_at, created_at
`

type CreateNotificationParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Type      string      `json:"type"`
	ActorID   pgtype.UUID `json:"actor_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	VideoID   pgtype.UUID `json:"video_id"`
	CommentID pgtype.UUID `json:"comment_id"`
}

// Record a notification for a recipient (user_id). Context columns are optional
// and depend on the type.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.ActorID,
		arg.ChannelID,
		arg.VideoID,
		arg.CommentID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.ActorID,
		&i.ChannelID,
		&i.VideoID,
		&i.CommentID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.type, n.actor_id, n.channel_id, n.video_id, n.comment_id,
       n.read_at, n.created_at,
       a.username AS actor_username, a.display_name AS actor_display_name,
       c.handle AS channel_handle, c.display_name AS channel_display_name,
       v.title AS video_title
FROM notifications n
LEFT JOIN users a ON a.id = n.actor_id
LEFT JOIN channels c ON c.id = n.channel_id
LEFT JOIN videos v ON v.id = n.video_id
WHERE n.user_id = $1
  AND (NOT $2::bool OR n.read_at IS NULL)
ORDER BY n.created_at DESC, n.id DESC
LIMIT $4 OFFSET $3
`

type ListNotificationsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	UnreadOnly   bool      `json:"unread_only"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListNotificationsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Type               string             `json:"type"`
	ActorID            pgtype.UUID        `json:"actor_id"`
	ChannelID          pgtype.UUID        `json:"channel_id"`
	VideoID            pgtype.UUID        `json:"video_id"`
	CommentID          pgtype.UUID        `json:"comment_id"`
	ReadAt             pgtype.Timestamptz `json:"read_at"`
	CreatedAt          time.Time          `json:"created_at"`
	ActorUsername      *string            `json:"actor_username"`
	ActorDisplayName   *string            `json:"actor_display_name"`
	ChannelHandle      *string            `json:"channel_handle"`
	ChannelDisplayName *string            `json:"channel_display_name"`
	VideoTitle         *string            `json:"video_title"`
}

// A user's notifications, newest first, joined with the actor's identity and the
// context (channel handle/name for follows, video title for comments). The
// joined columns are nullable because the context depends on the type. When
// unread_only is true, only unread (read_at IS NULL) rows are returned.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ActorID,
			&i.ChannelID,
			&i.VideoID,
			&i.CommentID,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ActorUsername,
			&i.ActorDisplayName,
			&i.ChannelHandle,
			&i.ChannelDisplayName,
			&i.VideoTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = COALESCE(read_at, now())
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Mark one of the user's notifications read (idempotent: already-read stays read).
// Returns the number of rows matched so the caller can distinguish 404 (0 rows,
// not found / not theirs) from success.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
