// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_identities.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countOAuthIdentitiesByUser = `-- name: CountOAuthIdentitiesByUser :one
SELECT count(*) FROM oauth_identities WHERE user_id = $1
`

func (q *Queries) CountOAuthIdentitiesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOAuthIdentitiesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (provider, subject, user_id, email, handle)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider, subject, user_id, email, created_at, handle
`

type CreateOAuthIdentityParams struct {
	Provider string    `json:"provider"`
	Subject  string    `json:"subject"`
	UserID   uuid.UUID `json:"user_id"`
	Email    string    `json:"email"`
	Handle   *string   `json:"handle"`
}

// handle is the display-only remote handle (ATProto sign-in); NULL for OIDC.
func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.Provider,
		arg.Subject,
		arg.UserID,
		arg.Email,
		arg.Handle,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.Handle,
	)
	return i, err
}

const deleteOAuthIdentity = `-- name: DeleteOAuthIdentity :execrows
DELETE FROM oauth_identities
WHERE user_id = $1 AND provider = $2
`

type DeleteOAuthIdentityParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

// Unlink a provider from an account. execrows so the service can distinguish
// "unlinked" from "was never linked".
func (q *Queries) DeleteOAuthIdentity(ctx context.Context, arg DeleteOAuthIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthIdentity, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, provider, subject, user_id, email, created_at, handle
FROM oauth_identities
WHERE provider = $1 AND subject = $2
`

type GetOAuthIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

// Resolves an external identity to its local account link. The (provider,
// subject) pair is the stable OIDC identity key.
func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.Subject)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.Handle,
	)
	return i, err
}

const listOAuthIdentitiesByUser = `-- name: ListOAuthIdentitiesByUser :many
SELECT id, provider, subject, user_id, email, created_at, handle
FROM oauth_identities
WHERE user_id = $1
ORDER BY created_at ASC, id ASC
`

// The caller's linked identities, oldest link first (stable settings list).
func (q *Queries) ListOAuthIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]OauthIdentity, error) {
	rows, err := q.db.Query(ctx, listOAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthIdentity
	for rows.Next() {
		var i OauthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Subject,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthIdentityHandle = `-- name: UpdateOAuthIdentityHandle :exec
UPDATE oauth_identities
SET handle = $3
WHERE provider = $1 AND subject = $2
`

type UpdateOAuthIdentityHandleParams struct {
	Provider string  `json:"provider"`
	Subject  string  `json:"subject"`
	Handle   *string `json:"handle"`
}

// Refresh the stored display handle for a link. Remote handles are mutable, so
// an ATProto re-login re-resolves and rewrites it. Keyed by the stable
// (provider, subject) identity; a no-op if the link is absent.
func (q *Queries) UpdateOAuthIdentityHandle(ctx context.Context, arg UpdateOAuthIdentityHandleParams) error {
	_, err := q.db.Exec(ctx, updateOAuthIdentityHandle, arg.Provider, arg.Subject, arg.Handle)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE lower(username) = lower($1)
) AS taken
`

// Case-insensitive username existence probe, used to derive a unique username
// for accounts created via OAuth login (the unique index remains the backstop).
func (q *Queries) UsernameExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, lower)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}
