// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peertube_import.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueImportRuns = `-- name: ClaimDueImportRuns :many
UPDATE peertube_import_runs
SET next_attempt_at = now() + interval '30 minutes',
    state = 'running',
    attempts = attempts + 1,
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id IN (
    SELECT id FROM peertube_import_runs
    WHERE state = 'pending' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, mode, conflict_policy, started_by
`

type ClaimDueImportRunsRow struct {
	ID             uuid.UUID   `json:"id"`
	Mode           string      `json:"mode"`
	ConflictPolicy string      `json:"conflict_policy"`
	StartedBy      pgtype.UUID `json:"started_by"`
}

// The worker claims due, still-pending runs (oldest first), flipping them to
// 'running' and stamping started_at on first claim.
//
// FOR UPDATE SKIP LOCKED is what makes this safe with more than one instance:
// concurrent claimers take disjoint rows instead of blocking on each other and
// then racing to re-evaluate the subquery. Without it, `UPDATE ... WHERE id IN
// (SELECT ...)` is the classic queue anti-pattern -- the ids are chosen before
// the lock is taken, so two claimers can select the same row.
func (q *Queries) ClaimDueImportRuns(ctx context.Context, limit int32) ([]ClaimDueImportRunsRow, error) {
	rows, err := q.db.Query(ctx, claimDueImportRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueImportRunsRow
	for rows.Next() {
		var i ClaimDueImportRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.ConflictPolicy,
			&i.StartedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeImportRun = `-- name: CompleteImportRun :exec
UPDATE peertube_import_runs
SET state = 'done', progress = $2, error = '', finished_at = now(), updated_at = now()
WHERE id = $1
`

type CompleteImportRunParams struct {
	ID       uuid.UUID `json:"id"`
	Progress []byte    `json:"progress"`
}

func (q *Queries) CompleteImportRun(ctx context.Context, arg CompleteImportRunParams) error {
	_, err := q.db.Exec(ctx, completeImportRun, arg.ID, arg.Progress)
	return err
}

const countImportLedgerByKindStatus = `-- name: CountImportLedgerByKindStatus :many
SELECT entity_kind, status, count(*) AS n
FROM peertube_import_ledger
GROUP BY entity_kind, status
ORDER BY entity_kind, status
`

type CountImportLedgerByKindStatusRow struct {
	EntityKind string `json:"entity_kind"`
	Status     string `json:"status"`
	N          int64  `json:"n"`
}

// Per-entity outcome tally for run progress + post-import verification.
func (q *Queries) CountImportLedgerByKindStatus(ctx context.Context) ([]CountImportLedgerByKindStatusRow, error) {
	rows, err := q.db.Query(ctx, countImportLedgerByKindStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountImportLedgerByKindStatusRow
	for rows.Next() {
		var i CountImportLedgerByKindStatusRow
		if err := rows.Scan(&i.EntityKind, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createImportRun = `-- name: CreateImportRun :one

INSERT INTO peertube_import_runs (mode, conflict_policy, started_by)
VALUES ($1, $2, $3)
RETURNING id, mode, state, conflict_policy, source_version, progress, error, started_by, attempts, next_attempt_at, created_at, updated_at, started_at, finished_at
`

type CreateImportRunParams struct {
	Mode           string      `json:"mode"`
	ConflictPolicy string      `json:"conflict_policy"`
	StartedBy      pgtype.UUID `json:"started_by"`
}

// ─────────────────────────── runs ───────────────────────────
// Launch a run. The single-active partial unique index makes this fail with a
// unique violation when a run is already pending/running — the caller maps that
// to a 409 "an import is already in progress".
func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) (PeertubeImportRun, error) {
	row := q.db.QueryRow(ctx, createImportRun, arg.Mode, arg.ConflictPolicy, arg.StartedBy)
	var i PeertubeImportRun
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.State,
		&i.ConflictPolicy,
		&i.SourceVersion,
		&i.Progress,
		&i.Error,
		&i.StartedBy,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failImportRun = `-- name: FailImportRun :exec
UPDATE peertube_import_runs
SET state = 'failed', error = $2, finished_at = now(), updated_at = now()
WHERE id = $1
`

type FailImportRunParams struct {
	ID    uuid.UUID `json:"id"`
	Error string    `json:"error"`
}

func (q *Queries) FailImportRun(ctx context.Context, arg FailImportRunParams) error {
	_, err := q.db.Exec(ctx, failImportRun, arg.ID, arg.Error)
	return err
}

const getImportLedgerEntry = `-- name: GetImportLedgerEntry :one


SELECT id, entity_kind, source_id, vidra_id, status, note, created_at, updated_at, source_value, applied_value FROM peertube_import_ledger
WHERE entity_kind = $1 AND source_id = $2
`

type GetImportLedgerEntryParams struct {
	EntityKind string `json:"entity_kind"`
	SourceID   string `json:"source_id"`
}

// PeerTube import bookkeeping (migration 0067, fix_plan P18). Two concerns:
// the durable idempotency/resume LEDGER (peertube_import_ledger) and the
// admin-facing RUNS queue (peertube_import_runs). No source credential is ever
// stored here — the source connection comes from server config / CLI flags.
// ─────────────────────────── ledger ───────────────────────────
// Idempotency lookup: the mapping for one source entity, if it exists. A 'done'
// row means "already imported, skip"; vidra_id lets children resolve parents.
func (q *Queries) GetImportLedgerEntry(ctx context.Context, arg GetImportLedgerEntryParams) (PeertubeImportLedger, error) {
	row := q.db.QueryRow(ctx, getImportLedgerEntry, arg.EntityKind, arg.SourceID)
	var i PeertubeImportLedger
	err := row.Scan(
		&i.ID,
		&i.EntityKind,
		&i.SourceID,
		&i.VidraID,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceValue,
		&i.AppliedValue,
	)
	return i, err
}

const getImportLedgerLastWriteForTarget = `-- name: GetImportLedgerLastWriteForTarget :one
SELECT applied_value, updated_at
FROM peertube_import_ledger
WHERE entity_kind = $1 AND vidra_id = $2 AND status = 'done'
ORDER BY updated_at DESC, source_id DESC
LIMIT 1
`

type GetImportLedgerLastWriteForTargetParams struct {
	EntityKind string      `json:"entity_kind"`
	VidraID    pgtype.UUID `json:"vidra_id"`
}

type GetImportLedgerLastWriteForTargetRow struct {
	AppliedValue string    `json:"applied_value"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// The import's most recent COMPLETED write onto one Vidra row, within one entity
// kind — "did I put the avatar that is in this slot there, and what was it?".
//
// The ledger is keyed by SOURCE id, which is the wrong key for that question:
// PeerTube keeps several actorImage rows per avatar and writes a new one every
// time the picture changes, so the row that describes the slot's current
// occupant is a DIFFERENT source id from the one a later run is looking at.
// Keying the lookup on vidra_id instead follows the slot rather than the file.
//
// applied_value (0113) is the fingerprint of what was written; it is empty for
// rows written before that memory existed, and updated_at is then the evidence
// available — the ledger row lands AFTER the image write, so a slot whose image
// is newer than this row was filled by somebody else.
func (q *Queries) GetImportLedgerLastWriteForTarget(ctx context.Context, arg GetImportLedgerLastWriteForTargetParams) (GetImportLedgerLastWriteForTargetRow, error) {
	row := q.db.QueryRow(ctx, getImportLedgerLastWriteForTarget, arg.EntityKind, arg.VidraID)
	var i GetImportLedgerLastWriteForTargetRow
	err := row.Scan(&i.AppliedValue, &i.UpdatedAt)
	return i, err
}

const getImportRun = `-- name: GetImportRun :one
SELECT id, mode, state, conflict_policy, source_version, progress, error, started_by, attempts, next_attempt_at, created_at, updated_at, started_at, finished_at FROM peertube_import_runs WHERE id = $1
`

func (q *Queries) GetImportRun(ctx context.Context, id uuid.UUID) (PeertubeImportRun, error) {
	row := q.db.QueryRow(ctx, getImportRun, id)
	var i PeertubeImportRun
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.State,
		&i.ConflictPolicy,
		&i.SourceVersion,
		&i.Progress,
		&i.Error,
		&i.StartedBy,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestImportRun = `-- name: GetLatestImportRun :one
SELECT id, mode, state, conflict_policy, source_version, progress, error, started_by, attempts, next_attempt_at, created_at, updated_at, started_at, finished_at FROM peertube_import_runs ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLatestImportRun(ctx context.Context) (PeertubeImportRun, error) {
	row := q.db.QueryRow(ctx, getLatestImportRun)
	var i PeertubeImportRun
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.State,
		&i.ConflictPolicy,
		&i.SourceVersion,
		&i.Progress,
		&i.Error,
		&i.StartedBy,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const importApplyVideoViewDelta = `-- name: ImportApplyVideoViewDelta :exec

INSERT INTO video_view_counts (video_id, views, updated_at)
VALUES ($1, GREATEST($2::bigint, 0), now())
ON CONFLICT (video_id) DO UPDATE
SET views = GREATEST(video_view_counts.views + $2::bigint, 0),
    updated_at = now()
`

type ImportApplyVideoViewDeltaParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Delta   int64     `json:"delta"`
}

// ───────────── per-video data carried after the video itself ─────────────
// Views, chapters, ratings and renditions are per-video data that hangs off an
// already-imported video rather than being part of its insert. They are carried
// by their own passes, keyed by their own ledger rows, so a re-run of the
// importer BACKFILLS them onto videos an earlier release already imported —
// a pass folded into the video insert would be skipped for every one of them.
//
// The rule they all share: the import never overwrites a row Vidra already has.
// ON CONFLICT DO NOTHING everywhere, so an operator-edited chapter set, a rating
// cast on the new instance, or a rendition row a Vidra re-transcode wrote all
// survive an import running on a schedule. Views are the one exception, and they
// are not an overwrite either — see ImportApplyVideoViewDelta.
// Apply the CHANGE in a source video's lifetime view total to Vidra's counter.
//
// This is a delta, never an assignment, and that is the whole design. Vidra's
// counter is live: it has been incremented by every view served since the last
// import. Assigning the source total would erase those; adding the source total
// again would double the history. Adding only what the source gained since the
// last run does neither, and a run against an unchanged source passes a delta of
// zero. The caller stores the total it applied in peertube_import_ledger
// .source_value; the delta is (new source total - that).
//
// GREATEST(..., 0) floors the result: a source whose total went DOWN (a purge, a
// re-count) can walk Vidra's counter back but never below zero.
func (q *Queries) ImportApplyVideoViewDelta(ctx context.Context, arg ImportApplyVideoViewDeltaParams) error {
	_, err := q.db.Exec(ctx, importApplyVideoViewDelta, arg.VideoID, arg.Delta)
	return err
}

const importFindChannelByHandle = `-- name: ImportFindChannelByHandle :one
SELECT id FROM channels WHERE lower(handle) = lower($1) LIMIT 1
`

func (q *Queries) ImportFindChannelByHandle(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importFindChannelByHandle, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importFindUserByEmail = `-- name: ImportFindUserByEmail :one
SELECT id FROM users WHERE lower(email) = lower($1) LIMIT 1
`

// Conflict lookup for the 'merge' policy: the existing user with this email.
func (q *Queries) ImportFindUserByEmail(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importFindUserByEmail, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importFindUserByUsername = `-- name: ImportFindUserByUsername :one
SELECT id FROM users WHERE lower(username) = lower($1) LIMIT 1
`

func (q *Queries) ImportFindUserByUsername(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importFindUserByUsername, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importFollowChannel = `-- name: ImportFollowChannel :exec
INSERT INTO channel_follows (follower_id, channel_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, channel_id) DO NOTHING
`

type ImportFollowChannelParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	ChannelID  uuid.UUID `json:"channel_id"`
}

func (q *Queries) ImportFollowChannel(ctx context.Context, arg ImportFollowChannelParams) error {
	_, err := q.db.Exec(ctx, importFollowChannel, arg.FollowerID, arg.ChannelID)
	return err
}

const importInsertChannel = `-- name: ImportInsertChannel :one
INSERT INTO channels (owner_id, handle, display_name, description, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type ImportInsertChannelParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ImportInsertChannel(ctx context.Context, arg ImportInsertChannelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importInsertChannel,
		arg.OwnerID,
		arg.Handle,
		arg.DisplayName,
		arg.Description,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importInsertComment = `-- name: ImportInsertComment :one
INSERT INTO comments (video_id, user_id, body, parent_id, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type ImportInsertCommentParams struct {
	VideoID   uuid.UUID   `json:"video_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Body      string      `json:"body"`
	ParentID  pgtype.UUID `json:"parent_id"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) ImportInsertComment(ctx context.Context, arg ImportInsertCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importInsertComment,
		arg.VideoID,
		arg.UserID,
		arg.Body,
		arg.ParentID,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importInsertPlaylist = `-- name: ImportInsertPlaylist :one
INSERT INTO playlists (owner_id, title, description, visibility, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type ImportInsertPlaylistParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Visibility  string    `json:"visibility"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ImportInsertPlaylist(ctx context.Context, arg ImportInsertPlaylistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importInsertPlaylist,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importInsertPlaylistItem = `-- name: ImportInsertPlaylistItem :exec
INSERT INTO playlist_items (playlist_id, video_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (playlist_id, video_id) DO NOTHING
`

type ImportInsertPlaylistItemParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	VideoID    uuid.UUID `json:"video_id"`
	Position   int32     `json:"position"`
}

func (q *Queries) ImportInsertPlaylistItem(ctx context.Context, arg ImportInsertPlaylistItemParams) error {
	_, err := q.db.Exec(ctx, importInsertPlaylistItem, arg.PlaylistID, arg.VideoID, arg.Position)
	return err
}

const importInsertUser = `-- name: ImportInsertUser :one

INSERT INTO users (username, email, password_hash, role, email_verified, is_active, display_name, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type ImportInsertUserParams struct {
	Username      string    `json:"username"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	Role          string    `json:"role"`
	EmailVerified bool      `json:"email_verified"`
	IsActive      bool      `json:"is_active"`
	DisplayName   string    `json:"display_name"`
	CreatedAt     time.Time `json:"created_at"`
}

// ─────────────────── idempotent entity inserts ───────────────────
// These write the mapped Vidra rows during an import. They preserve the source
// created_at (a migration should keep original timestamps) and RETURN only the
// new id, so they add no coupling to the shared sqlc row models. Each is called
// in the same transaction as its ledger upsert. Conflict detection (username/
// handle/email/slug) happens in the service BEFORE these run; ON CONFLICT guards
// only protect the natural-key child tables against a resumed partial import.
func (q *Queries) ImportInsertUser(ctx context.Context, arg ImportInsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importInsertUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.EmailVerified,
		arg.IsActive,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importInsertVideo = `-- name: ImportInsertVideo :one
INSERT INTO videos (channel_id, title, description, privacy, state, category, language, license, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type ImportInsertVideoParams struct {
	ChannelID   uuid.UUID `json:"channel_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Privacy     string    `json:"privacy"`
	State       string    `json:"state"`
	Category    *string   `json:"category"`
	Language    *string   `json:"language"`
	License     *string   `json:"license"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ImportInsertVideo(ctx context.Context, arg ImportInsertVideoParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importInsertVideo,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.Privacy,
		arg.State,
		arg.Category,
		arg.Language,
		arg.License,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importInsertVideoChapter = `-- name: ImportInsertVideoChapter :exec
INSERT INTO video_chapters (video_id, start_seconds, title)
VALUES ($1, $2, $3)
ON CONFLICT (video_id, start_seconds) DO NOTHING
`

type ImportInsertVideoChapterParams struct {
	VideoID      uuid.UUID `json:"video_id"`
	StartSeconds int32     `json:"start_seconds"`
	Title        string    `json:"title"`
}

// One seek-bar chapter mark. (video_id, start_seconds) is the table's primary
// key, so DO NOTHING is what makes a repeated import a no-op — and it is also
// what stops a scheduled import from stamping on a chapter set the operator
// edited on the new instance.
func (q *Queries) ImportInsertVideoChapter(ctx context.Context, arg ImportInsertVideoChapterParams) error {
	_, err := q.db.Exec(ctx, importInsertVideoChapter, arg.VideoID, arg.StartSeconds, arg.Title)
	return err
}

const importInsertVideoFile = `-- name: ImportInsertVideoFile :one
INSERT INTO video_files (video_id, kind, storage_key, content_type, original_name, size_bytes, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type ImportInsertVideoFileParams struct {
	VideoID      uuid.UUID `json:"video_id"`
	Kind         string    `json:"kind"`
	StorageKey   string    `json:"storage_key"`
	ContentType  string    `json:"content_type"`
	OriginalName string    `json:"original_name"`
	SizeBytes    int64     `json:"size_bytes"`
	Sha256       string    `json:"sha256"`
}

// sha256 is the digest the media copy already computed while streaming the
// object across; it is empty in reference mode, where no bytes were copied and
// the backfill worker hashes the referenced object instead.
func (q *Queries) ImportInsertVideoFile(ctx context.Context, arg ImportInsertVideoFileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importInsertVideoFile,
		arg.VideoID,
		arg.Kind,
		arg.StorageKey,
		arg.ContentType,
		arg.OriginalName,
		arg.SizeBytes,
		arg.Sha256,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importInsertVideoRating = `-- name: ImportInsertVideoRating :exec
INSERT INTO video_ratings (video_id, user_id, rating, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (user_id, video_id) DO NOTHING
`

type ImportInsertVideoRatingParams struct {
	VideoID   uuid.UUID `json:"video_id"`
	UserID    uuid.UUID `json:"user_id"`
	Rating    string    `json:"rating"`
	CreatedAt time.Time `json:"created_at"`
}

// One user's like/dislike, with the source's timestamps preserved. DO NOTHING on
// the (user_id, video_id) key: if this pair already has a rating it was either
// cast on Vidra or written by an earlier import, and neither is ours to replace.
func (q *Queries) ImportInsertVideoRating(ctx context.Context, arg ImportInsertVideoRatingParams) error {
	_, err := q.db.Exec(ctx, importInsertVideoRating,
		arg.VideoID,
		arg.UserID,
		arg.Rating,
		arg.CreatedAt,
	)
	return err
}

const importInsertVideoRendition = `-- name: ImportInsertVideoRendition :exec
INSERT INTO video_renditions (video_id, height, width, key_prefix, size_bytes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (video_id, height) DO NOTHING
`

type ImportInsertVideoRenditionParams struct {
	VideoID   uuid.UUID `json:"video_id"`
	Height    int32     `json:"height"`
	Width     int32     `json:"width"`
	KeyPrefix string    `json:"key_prefix"`
	SizeBytes int64     `json:"size_bytes"`
}

// One rung of an imported HLS ladder, so the quality selector has something to
// render for a video whose manifest Vidra did not write. key_prefix points at
// the source tree's directory: there are no progressive per-rung download assets
// under it, and the download endpoint already skips a rung whose asset is
// missing, so the row advertises the rung without promising a file.
//
// DO NOTHING on (video_id, height): a Vidra re-transcode owns its own rendition
// rows, and overwriting one of those with a source key_prefix would break the
// per-rung download it does have.
func (q *Queries) ImportInsertVideoRendition(ctx context.Context, arg ImportInsertVideoRenditionParams) error {
	_, err := q.db.Exec(ctx, importInsertVideoRendition,
		arg.VideoID,
		arg.Height,
		arg.Width,
		arg.KeyPrefix,
		arg.SizeBytes,
	)
	return err
}

const importInsertVideoTag = `-- name: ImportInsertVideoTag :exec
INSERT INTO video_tags (video_id, tag)
VALUES ($1, $2)
ON CONFLICT (video_id, tag) DO NOTHING
`

type ImportInsertVideoTagParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Tag     string    `json:"tag"`
}

func (q *Queries) ImportInsertVideoTag(ctx context.Context, arg ImportInsertVideoTagParams) error {
	_, err := q.db.Exec(ctx, importInsertVideoTag, arg.VideoID, arg.Tag)
	return err
}

const importUpsertAccountActorKey = `-- name: ImportUpsertAccountActorKey :exec
INSERT INTO account_actor_keys (user_id, public_key_pem, private_key_pem)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type ImportUpsertAccountActorKeyParams struct {
	UserID        uuid.UUID `json:"user_id"`
	PublicKeyPem  string    `json:"public_key_pem"`
	PrivateKeyPem string    `json:"private_key_pem"`
}

// Federation-continuity: carry the source account's ActivityPub keypair so the
// migrated instance keeps signing as the same actor. private_key_pem is a SECRET
// (sealed under the KEK, or raw in dev) — never logged. ON CONFLICT keeps a
// resumed import a no-op.
func (q *Queries) ImportUpsertAccountActorKey(ctx context.Context, arg ImportUpsertAccountActorKeyParams) error {
	_, err := q.db.Exec(ctx, importUpsertAccountActorKey, arg.UserID, arg.PublicKeyPem, arg.PrivateKeyPem)
	return err
}

const importUpsertCaption = `-- name: ImportUpsertCaption :one
INSERT INTO captions (video_id, language, label, storage_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT (video_id, language) DO UPDATE SET
    label = EXCLUDED.label,
    storage_key = EXCLUDED.storage_key,
    updated_at = now()
RETURNING id
`

type ImportUpsertCaptionParams struct {
	VideoID    uuid.UUID `json:"video_id"`
	Language   string    `json:"language"`
	Label      string    `json:"label"`
	StorageKey string    `json:"storage_key"`
}

func (q *Queries) ImportUpsertCaption(ctx context.Context, arg ImportUpsertCaptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importUpsertCaption,
		arg.VideoID,
		arg.Language,
		arg.Label,
		arg.StorageKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importUpsertChannelActorKey = `-- name: ImportUpsertChannelActorKey :exec
INSERT INTO channel_actor_keys (channel_id, public_key_pem, private_key_pem)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id) DO NOTHING
`

type ImportUpsertChannelActorKeyParams struct {
	ChannelID     uuid.UUID `json:"channel_id"`
	PublicKeyPem  string    `json:"public_key_pem"`
	PrivateKeyPem string    `json:"private_key_pem"`
}

func (q *Queries) ImportUpsertChannelActorKey(ctx context.Context, arg ImportUpsertChannelActorKeyParams) error {
	_, err := q.db.Exec(ctx, importUpsertChannelActorKey, arg.ChannelID, arg.PublicKeyPem, arg.PrivateKeyPem)
	return err
}

const importUpsertVideoMetadata = `-- name: ImportUpsertVideoMetadata :exec
INSERT INTO video_metadata (video_id, duration_seconds, width, height)
VALUES ($1, $2, $3, $4)
ON CONFLICT (video_id) DO UPDATE SET
    duration_seconds = EXCLUDED.duration_seconds,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    updated_at = now()
`

type ImportUpsertVideoMetadataParams struct {
	VideoID         uuid.UUID `json:"video_id"`
	DurationSeconds *int32    `json:"duration_seconds"`
	Width           *int32    `json:"width"`
	Height          *int32    `json:"height"`
}

func (q *Queries) ImportUpsertVideoMetadata(ctx context.Context, arg ImportUpsertVideoMetadataParams) error {
	_, err := q.db.Exec(ctx, importUpsertVideoMetadata,
		arg.VideoID,
		arg.DurationSeconds,
		arg.Width,
		arg.Height,
	)
	return err
}

const importVideoHasReadyPlaylist = `-- name: ImportVideoHasReadyPlaylist :one
SELECT EXISTS (
    SELECT 1 FROM streaming_playlists
    WHERE video_id = $1 AND state = 'ready' AND master_key <> ''
)
`

// Whether a video has a ready HLS tree recorded. Rendition rows are only
// meaningful alongside one: a video whose media was copied (and will be
// transcoded by Vidra) gets its ladder from that transcode instead.
func (q *Queries) ImportVideoHasReadyPlaylist(ctx context.Context, videoID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, importVideoHasReadyPlaylist, videoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listImportLedgerConflicts = `-- name: ListImportLedgerConflicts :many
SELECT id, entity_kind, source_id, vidra_id, status, note, created_at, updated_at, source_value, applied_value FROM peertube_import_ledger
WHERE status IN ('skipped', 'failed', 'unsupported') OR note <> ''
ORDER BY entity_kind, source_id
LIMIT $1
`

// The rows the conflict policy touched (renamed/merged/skipped/failed) — the
// dry-run "conflicts" report and the operator's post-import audit.
func (q *Queries) ListImportLedgerConflicts(ctx context.Context, limit int32) ([]PeertubeImportLedger, error) {
	rows, err := q.db.Query(ctx, listImportLedgerConflicts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeertubeImportLedger
	for rows.Next() {
		var i PeertubeImportLedger
		if err := rows.Scan(
			&i.ID,
			&i.EntityKind,
			&i.SourceID,
			&i.VidraID,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceValue,
			&i.AppliedValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRuns = `-- name: ListImportRuns :many
SELECT id, mode, state, conflict_policy, source_version, progress, error, started_by, attempts, next_attempt_at, created_at, updated_at, started_at, finished_at FROM peertube_import_runs
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListImportRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListImportRuns(ctx context.Context, arg ListImportRunsParams) ([]PeertubeImportRun, error) {
	rows, err := q.db.Query(ctx, listImportRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeertubeImportRun
	for rows.Next() {
		var i PeertubeImportRun
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.State,
			&i.ConflictPolicy,
			&i.SourceVersion,
			&i.Progress,
			&i.Error,
			&i.StartedBy,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewImportRunLease = `-- name: RenewImportRunLease :exec
UPDATE peertube_import_runs
SET next_attempt_at = now() + interval '30 minutes', updated_at = now()
WHERE id = $1 AND state = 'running'
`

// Push a running job's lease forward. The worker calls this on a ticker while the
// job runs, so a job that legitimately outlives one lease is not swept out from
// under itself. Guarded on state so a completed or failed job cannot be revived.
//
// updated_at is bumped with the lease so the operational projection can tell a
// live job from an abandoned one — see RenewTranscodeJobLease for why that bump
// is the whole of the `stale_running` signal.
func (q *Queries) RenewImportRunLease(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, renewImportRunLease, id)
	return err
}

const setImportRunVersion = `-- name: SetImportRunVersion :exec
UPDATE peertube_import_runs
SET source_version = $2, updated_at = now()
WHERE id = $1
`

type SetImportRunVersionParams struct {
	ID            uuid.UUID `json:"id"`
	SourceVersion *int32    `json:"source_version"`
}

func (q *Queries) SetImportRunVersion(ctx context.Context, arg SetImportRunVersionParams) error {
	_, err := q.db.Exec(ctx, setImportRunVersion, arg.ID, arg.SourceVersion)
	return err
}

const sweepExpiredImportRuns = `-- name: SweepExpiredImportRuns :execrows
UPDATE peertube_import_runs
SET state = 'pending', attempts = attempts + 1, started_at = NULL, updated_at = now()
WHERE id IN (
    SELECT id FROM peertube_import_runs
    WHERE state = 'running' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT 1000
    FOR UPDATE SKIP LOCKED
)
`

// Return jobs whose lease elapsed while they were 'running' to the queue.
//
// This REPLACES the boot-time blanket requeue of every running row, which was
// safe only because the process doing it was the deployment's only worker. A
// second instance booting would have requeued jobs the first was actively
// running. A lease sweep needs no such assumption: it only touches rows whose
// owner has demonstrably stopped renewing, so it is correct with any number of
// instances and can run periodically rather than only at start-up.
//
// attempts is incremented so a job that crashes its worker every time walks its
// counter up and dead-letters through the normal path instead of looping forever.
//
// Bounded FOR UPDATE SKIP LOCKED for the same reason the claim uses it: without
// it, concurrent sweepers take their row locks in table order and serialise on
// each other; with it they take disjoint rows. LIMIT bounds one tick's work
// (see SweepExpiredTranscodeJobs for the full rationale). At most one run is
// ever active here, so the bound is a formality — but a queue that is swept the
// same way as every other queue is one fewer shape to reason about.
func (q *Queries) SweepExpiredImportRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredImportRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateImportRunProgress = `-- name: UpdateImportRunProgress :exec
UPDATE peertube_import_runs
SET progress = $2, updated_at = now()
WHERE id = $1
`

type UpdateImportRunProgressParams struct {
	ID       uuid.UUID `json:"id"`
	Progress []byte    `json:"progress"`
}

func (q *Queries) UpdateImportRunProgress(ctx context.Context, arg UpdateImportRunProgressParams) error {
	_, err := q.db.Exec(ctx, updateImportRunProgress, arg.ID, arg.Progress)
	return err
}

const upsertImportLedgerApplied = `-- name: UpsertImportLedgerApplied :exec

INSERT INTO peertube_import_ledger (entity_kind, source_id, vidra_id, status, note, applied_value)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (entity_kind, source_id)
DO UPDATE SET vidra_id      = EXCLUDED.vidra_id,
              status        = EXCLUDED.status,
              note          = EXCLUDED.note,
              applied_value = EXCLUDED.applied_value,
              updated_at    = now()
`

type UpsertImportLedgerAppliedParams struct {
	EntityKind   string      `json:"entity_kind"`
	SourceID     string      `json:"source_id"`
	VidraID      pgtype.UUID `json:"vidra_id"`
	Status       string      `json:"status"`
	Note         string      `json:"note"`
	AppliedValue string      `json:"applied_value"`
}

// ───────────── the instance's own category taxonomy ─────────────
// A PeerTube instance can replace the stock 1–18 category list wholesale
// (peertube-plugin-categories does exactly that), and the import already carries
// each video's category id across. Carried ids with no taxonomy behind them
// validate against nothing, so the taxonomy is carried too — into the
// instance_custom_categories setting, which REPLACES the built-in list.
//
// It is one SETTING, not a set of rows, and one an operator may also edit by
// hand. So the ledger remembers the exact value the import applied (0113) and
// the pass compares before writing: its own earlier value may be updated when
// the source moves, anything else is a human's and is left alone.
// The ledger upsert for a SINGLE-VALUE kind: same idempotency key as
// UpsertImportLedgerEntry, but it also records the value that was applied so the
// next run can tell its own write apart from an operator's edit. A pass that
// decided NOT to write passes the value it read back, so a skip never erases the
// memory of an earlier write.
func (q *Queries) UpsertImportLedgerApplied(ctx context.Context, arg UpsertImportLedgerAppliedParams) error {
	_, err := q.db.Exec(ctx, upsertImportLedgerApplied,
		arg.EntityKind,
		arg.SourceID,
		arg.VidraID,
		arg.Status,
		arg.Note,
		arg.AppliedValue,
	)
	return err
}

const upsertImportLedgerCounter = `-- name: UpsertImportLedgerCounter :exec
INSERT INTO peertube_import_ledger (entity_kind, source_id, vidra_id, status, note, source_value)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (entity_kind, source_id)
DO UPDATE SET vidra_id     = EXCLUDED.vidra_id,
              status       = EXCLUDED.status,
              note         = EXCLUDED.note,
              source_value = EXCLUDED.source_value,
              updated_at   = now()
`

type UpsertImportLedgerCounterParams struct {
	EntityKind  string      `json:"entity_kind"`
	SourceID    string      `json:"source_id"`
	VidraID     pgtype.UUID `json:"vidra_id"`
	Status      string      `json:"status"`
	Note        string      `json:"note"`
	SourceValue int64       `json:"source_value"`
}

// The ledger upsert for a COUNTER kind: same idempotency key as
// UpsertImportLedgerEntry, but it also records the source total that was applied
// so the next run can compute a delta instead of re-applying the whole number.
func (q *Queries) UpsertImportLedgerCounter(ctx context.Context, arg UpsertImportLedgerCounterParams) error {
	_, err := q.db.Exec(ctx, upsertImportLedgerCounter,
		arg.EntityKind,
		arg.SourceID,
		arg.VidraID,
		arg.Status,
		arg.Note,
		arg.SourceValue,
	)
	return err
}

const upsertImportLedgerEntry = `-- name: UpsertImportLedgerEntry :one
INSERT INTO peertube_import_ledger (entity_kind, source_id, vidra_id, status, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (entity_kind, source_id)
DO UPDATE SET vidra_id = EXCLUDED.vidra_id,
              status   = EXCLUDED.status,
              note     = EXCLUDED.note,
              updated_at = now()
RETURNING id, entity_kind, source_id, vidra_id, status, note, created_at, updated_at, source_value, applied_value
`

type UpsertImportLedgerEntryParams struct {
	EntityKind string      `json:"entity_kind"`
	SourceID   string      `json:"source_id"`
	VidraID    pgtype.UUID `json:"vidra_id"`
	Status     string      `json:"status"`
	Note       string      `json:"note"`
}

// Record (or update) the outcome of importing one source entity. Called in the
// SAME transaction as the entity insert so the map and the row commit atomically
// (a crash between them cannot leave a dangling half-import). ON CONFLICT keeps
// the re-import a no-op-that-updates rather than a duplicate.
func (q *Queries) UpsertImportLedgerEntry(ctx context.Context, arg UpsertImportLedgerEntryParams) (PeertubeImportLedger, error) {
	row := q.db.QueryRow(ctx, upsertImportLedgerEntry,
		arg.EntityKind,
		arg.SourceID,
		arg.VidraID,
		arg.Status,
		arg.Note,
	)
	var i PeertubeImportLedger
	err := row.Scan(
		&i.ID,
		&i.EntityKind,
		&i.SourceID,
		&i.VidraID,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceValue,
		&i.AppliedValue,
	)
	return i, err
}
