// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peertube_import_mutes.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const importAccountMute = `-- name: ImportAccountMute :execrows
INSERT INTO muted_accounts (muter_id, muted_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (muter_id, muted_id) DO NOTHING
`

type ImportAccountMuteParams struct {
	MuterID   uuid.UUID `json:"muter_id"`
	MutedID   uuid.UUID `json:"muted_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ImportAccountMute(ctx context.Context, arg ImportAccountMuteParams) (int64, error) {
	result, err := q.db.Exec(ctx, importAccountMute, arg.MuterID, arg.MutedID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importInstanceMute = `-- name: ImportInstanceMute :execrows
INSERT INTO muted_instances (muter_id, domain, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (muter_id, domain) DO NOTHING
`

type ImportInstanceMuteParams struct {
	MuterID   uuid.UUID `json:"muter_id"`
	Domain    string    `json:"domain"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ImportInstanceMute(ctx context.Context, arg ImportInstanceMuteParams) (int64, error) {
	result, err := q.db.Exec(ctx, importInstanceMute, arg.MuterID, arg.Domain, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
