// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_requests.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveRegistrationRequest = `-- name: ApproveRegistrationRequest :one
WITH req AS (
    SELECT registration_requests.id, registration_requests.username,
           registration_requests.email, registration_requests.password_hash
    FROM registration_requests
    WHERE registration_requests.id = $1 AND registration_requests.status = 'pending'
),
ins AS (
    INSERT INTO users (username, email, password_hash, role)
    SELECT req.username, req.email, req.password_hash, 'user' FROM req
    RETURNING id, username, email, password_hash, role, email_verified, is_active, created_at, updated_at, display_name, bio
),
upd AS (
    UPDATE registration_requests
    SET status = 'approved', reviewed_by = $2, reviewed_at = now(), updated_at = now()
    WHERE registration_requests.id = (SELECT req.id FROM req)
    RETURNING registration_requests.id
)
SELECT ins.id, ins.username, ins.email, ins.password_hash, ins.role, ins.email_verified,
       ins.is_active, ins.created_at, ins.updated_at, ins.display_name, ins.bio
FROM ins
`

type ApproveRegistrationRequestParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

type ApproveRegistrationRequestRow struct {
	ID            uuid.UUID `json:"id"`
	Username      string    `json:"username"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	Role          string    `json:"role"`
	EmailVerified bool      `json:"email_verified"`
	IsActive      bool      `json:"is_active"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	DisplayName   string    `json:"display_name"`
	Bio           string    `json:"bio"`
}

// Atomically approve a PENDING request: create the user account from the stored
// hash and mark the request approved, in a single statement (data-modifying CTEs
// run exactly once, so this is all-or-nothing). Returns the created user. If the
// request is not pending, `req` is empty so nothing is inserted/updated and no
// row is returned (the service maps that to not-found). If the username/email is
// now taken, the users insert raises a unique violation and the whole statement
// rolls back, leaving the request pending.
func (q *Queries) ApproveRegistrationRequest(ctx context.Context, arg ApproveRegistrationRequestParams) (ApproveRegistrationRequestRow, error) {
	row := q.db.QueryRow(ctx, approveRegistrationRequest, arg.ID, arg.ReviewedBy)
	var i ApproveRegistrationRequestRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Bio,
	)
	return i, err
}

const createRegistrationRequest = `-- name: CreateRegistrationRequest :one
INSERT INTO registration_requests (username, email, password_hash, note)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, note, status, moderator_note, reviewed_at, created_at
`

type CreateRegistrationRequestParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Note         string `json:"note"`
}

type CreateRegistrationRequestRow struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	Note          string             `json:"note"`
	Status        string             `json:"status"`
	ModeratorNote string             `json:"moderator_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

// File a pending registration request. A duplicate PENDING request for the same
// email/username raises a unique violation (23505), which the service maps to a
// conflict.
func (q *Queries) CreateRegistrationRequest(ctx context.Context, arg CreateRegistrationRequestParams) (CreateRegistrationRequestRow, error) {
	row := q.db.QueryRow(ctx, createRegistrationRequest,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Note,
	)
	var i CreateRegistrationRequestRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Note,
		&i.Status,
		&i.ModeratorNote,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRegistrationRequests = `-- name: ListRegistrationRequests :many
SELECT r.id, r.username, r.email, r.note, r.status, r.moderator_note,
       r.reviewed_at, r.created_at,
       u.username AS reviewer_username
FROM registration_requests r
LEFT JOIN users u ON u.id = r.reviewed_by
WHERE (NOT $1::bool OR r.status = 'pending')
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3 OFFSET $2
`

type ListRegistrationRequestsParams struct {
	PendingOnly  bool  `json:"pending_only"`
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type ListRegistrationRequestsRow struct {
	ID               uuid.UUID          `json:"id"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	Note             string             `json:"note"`
	Status           string             `json:"status"`
	ModeratorNote    string             `json:"moderator_note"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt        time.Time          `json:"created_at"`
	ReviewerUsername *string            `json:"reviewer_username"`
}

// The approval queue, newest first, with the reviewing admin's username resolved.
// When pending_only is true, only unresolved requests are returned. The
// password hash is never selected.
func (q *Queries) ListRegistrationRequests(ctx context.Context, arg ListRegistrationRequestsParams) ([]ListRegistrationRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationRequests, arg.PendingOnly, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationRequestsRow
	for rows.Next() {
		var i ListRegistrationRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Note,
			&i.Status,
			&i.ModeratorNote,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.ReviewerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRegistrationRequest = `-- name: RejectRegistrationRequest :execrows
UPDATE registration_requests
SET status = 'rejected', moderator_note = $1,
    reviewed_by = $2, reviewed_at = now(), updated_at = now()
WHERE id = $3 AND status = 'pending'
`

type RejectRegistrationRequestParams struct {
	ModeratorNote string      `json:"moderator_note"`
	ReviewedBy    pgtype.UUID `json:"reviewed_by"`
	ID            uuid.UUID   `json:"id"`
}

// Reject a PENDING request with a moderator note. Returns rows affected so the
// caller can 404 an unknown/already-resolved id.
func (q *Queries) RejectRegistrationRequest(ctx context.Context, arg RejectRegistrationRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectRegistrationRequest, arg.ModeratorNote, arg.ReviewedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
