// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote_video_blocks.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockRemoteVideo = `-- name: BlockRemoteVideo :execrows

INSERT INTO remote_video_blocks (remote_video_id, reason, blocked_by)
VALUES ($1, $2, $3)
ON CONFLICT (remote_video_id) DO UPDATE
    SET reason = EXCLUDED.reason, blocked_by = EXCLUDED.blocked_by, created_at = now()
`

type BlockRemoteVideoParams struct {
	RemoteVideoID uuid.UUID   `json:"remote_video_id"`
	Reason        string      `json:"reason"`
	BlockedBy     pgtype.UUID `json:"blocked_by"`
}

// Remote-video blocks (migration 0054, remote-content §8): the admin per-video
// hide for federated content, mirroring video_blocks.
// Block a remote video (idempotent: re-blocking updates the reason + acting
// moderator). A non-existent remote video raises a foreign-key violation
// (SQLSTATE 23503), which the service maps to "remote video not found".
func (q *Queries) BlockRemoteVideo(ctx context.Context, arg BlockRemoteVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, blockRemoteVideo, arg.RemoteVideoID, arg.Reason, arg.BlockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBlockedRemoteVideos = `-- name: ListBlockedRemoteVideos :many
SELECT
    b.remote_video_id,
    rv.title,
    rv.object_url,
    rv.watch_url,
    (ra.preferred_username || '@' || ra.domain)::text AS channel_handle,
    ra.domain,
    b.reason,
    u.username   AS blocked_by_username,
    b.created_at AS blocked_at
FROM remote_video_blocks b
JOIN remote_videos rv ON rv.id = b.remote_video_id
JOIN remote_actors ra ON ra.actor_url = rv.remote_actor_url
LEFT JOIN users u ON u.id = b.blocked_by
ORDER BY b.created_at DESC, b.remote_video_id
LIMIT $2 OFFSET $1
`

type ListBlockedRemoteVideosParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type ListBlockedRemoteVideosRow struct {
	RemoteVideoID     uuid.UUID `json:"remote_video_id"`
	Title             string    `json:"title"`
	ObjectUrl         string    `json:"object_url"`
	WatchUrl          string    `json:"watch_url"`
	ChannelHandle     string    `json:"channel_handle"`
	Domain            string    `json:"domain"`
	Reason            string    `json:"reason"`
	BlockedByUsername *string   `json:"blocked_by_username"`
	BlockedAt         time.Time `json:"blocked_at"`
}

// Currently-blocked remote videos for the moderation block-list: newest block
// first, with the video title, origin identity, the block reason, who blocked
// it (NULL if that moderator's account was deleted), and when.
func (q *Queries) ListBlockedRemoteVideos(ctx context.Context, arg ListBlockedRemoteVideosParams) ([]ListBlockedRemoteVideosRow, error) {
	rows, err := q.db.Query(ctx, listBlockedRemoteVideos, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedRemoteVideosRow
	for rows.Next() {
		var i ListBlockedRemoteVideosRow
		if err := rows.Scan(
			&i.RemoteVideoID,
			&i.Title,
			&i.ObjectUrl,
			&i.WatchUrl,
			&i.ChannelHandle,
			&i.Domain,
			&i.Reason,
			&i.BlockedByUsername,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockRemoteVideo = `-- name: UnblockRemoteVideo :execrows
DELETE FROM remote_video_blocks WHERE remote_video_id = $1
`

// Unblock a remote video (idempotent). Returns rows deleted (0 = not blocked).
func (q *Queries) UnblockRemoteVideo(ctx context.Context, remoteVideoID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unblockRemoteVideo, remoteVideoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
