// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote_actors.sql

package sqlcgen

import (
	"context"
)

const deleteRemoteActor = `-- name: DeleteRemoteActor :execrows
DELETE FROM remote_actors WHERE actor_url = $1
`

// Inbound actor Delete (remote-content §7): drop the cached actor; its remote
// videos, remote-authored comments, and remote-channel follow edges cascade
// away via their remote_actor_url foreign keys.
func (q *Queries) DeleteRemoteActor(ctx context.Context, actorUrl string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemoteActor, actorUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRemoteActor = `-- name: GetRemoteActor :one

SELECT actor_url, actor_type, preferred_username, domain, inbox_url, shared_inbox_url,
       public_key_pem, followers_url, fetched_at, updated_at
FROM remote_actors
WHERE actor_url = $1
`

// Cached remote ActivityPub actors (migration 0036, .ralph/specs/federation.md §7).
func (q *Queries) GetRemoteActor(ctx context.Context, actorUrl string) (RemoteActor, error) {
	row := q.db.QueryRow(ctx, getRemoteActor, actorUrl)
	var i RemoteActor
	err := row.Scan(
		&i.ActorUrl,
		&i.ActorType,
		&i.PreferredUsername,
		&i.Domain,
		&i.InboxUrl,
		&i.SharedInboxUrl,
		&i.PublicKeyPem,
		&i.FollowersUrl,
		&i.FetchedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRemoteActor = `-- name: UpsertRemoteActor :exec
INSERT INTO remote_actors (
    actor_url, actor_type, preferred_username, domain, inbox_url,
    shared_inbox_url, public_key_pem, followers_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (actor_url) DO UPDATE SET
    actor_type         = EXCLUDED.actor_type,
    preferred_username = EXCLUDED.preferred_username,
    domain             = EXCLUDED.domain,
    inbox_url          = EXCLUDED.inbox_url,
    shared_inbox_url   = EXCLUDED.shared_inbox_url,
    public_key_pem     = EXCLUDED.public_key_pem,
    followers_url      = EXCLUDED.followers_url,
    updated_at         = now()
`

type UpsertRemoteActorParams struct {
	ActorUrl          string  `json:"actor_url"`
	ActorType         string  `json:"actor_type"`
	PreferredUsername string  `json:"preferred_username"`
	Domain            string  `json:"domain"`
	InboxUrl          string  `json:"inbox_url"`
	SharedInboxUrl    *string `json:"shared_inbox_url"`
	PublicKeyPem      string  `json:"public_key_pem"`
	FollowersUrl      string  `json:"followers_url"`
}

func (q *Queries) UpsertRemoteActor(ctx context.Context, arg UpsertRemoteActorParams) error {
	_, err := q.db.Exec(ctx, upsertRemoteActor,
		arg.ActorUrl,
		arg.ActorType,
		arg.PreferredUsername,
		arg.Domain,
		arg.InboxUrl,
		arg.SharedInboxUrl,
		arg.PublicKeyPem,
		arg.FollowersUrl,
	)
	return err
}
