// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote_channel_follows.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptRemoteChannelFollowByActivity = `-- name: AcceptRemoteChannelFollowByActivity :execrows
UPDATE remote_channel_follows
SET state = 'accepted'
WHERE follow_activity_url = $1 AND remote_actor_url = $2
`

type AcceptRemoteChannelFollowByActivityParams struct {
	FollowActivityUrl string `json:"follow_activity_url"`
	RemoteActorUrl    string `json:"remote_actor_url"`
}

// Inbound Accept{Follow}: flips the matching pending follow to accepted. The
// remote_actor_url predicate enforces that the Accept's signer IS the followed
// actor — an Accept signed by anyone else matches no row.
func (q *Queries) AcceptRemoteChannelFollowByActivity(ctx context.Context, arg AcceptRemoteChannelFollowByActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptRemoteChannelFollowByActivity, arg.FollowActivityUrl, arg.RemoteActorUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRemoteChannelFollows = `-- name: CountRemoteChannelFollows :one
SELECT count(*)::bigint
FROM remote_channel_follows f
JOIN remote_actors ra ON ra.actor_url = f.remote_actor_url
WHERE f.user_id = $1
`

// How many rows ListRemoteChannelFollows would return, ignoring pagination. The
// remote_actors JOIN is part of the predicate.
func (q *Queries) CountRemoteChannelFollows(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRemoteChannelFollows, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteRemoteChannelFollowByActivity = `-- name: DeleteRemoteChannelFollowByActivity :execrows
DELETE FROM remote_channel_follows
WHERE follow_activity_url = $1 AND remote_actor_url = $2
`

type DeleteRemoteChannelFollowByActivityParams struct {
	FollowActivityUrl string `json:"follow_activity_url"`
	RemoteActorUrl    string `json:"remote_actor_url"`
}

// Inbound Reject{Follow}: removes the matching follow. Same signer-is-the-
// followed-actor predicate as the Accept.
func (q *Queries) DeleteRemoteChannelFollowByActivity(ctx context.Context, arg DeleteRemoteChannelFollowByActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemoteChannelFollowByActivity, arg.FollowActivityUrl, arg.RemoteActorUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRemoteChannelFollowByID = `-- name: DeleteRemoteChannelFollowByID :execrows
DELETE FROM remote_channel_follows WHERE id = $1 AND user_id = $2
`

type DeleteRemoteChannelFollowByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Local unfollow (local intent wins: the row goes immediately; the Undo is
// queued separately). Scoped by user_id; rows report whether anything existed.
func (q *Queries) DeleteRemoteChannelFollowByID(ctx context.Context, arg DeleteRemoteChannelFollowByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemoteChannelFollowByID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRemoteChannelFollowByID = `-- name: GetRemoteChannelFollowByID :one
SELECT f.id, f.user_id, f.remote_actor_url, f.state, f.follow_activity_url, f.created_at,
       ra.preferred_username, ra.domain,
       COALESCE(ra.shared_inbox_url, ra.inbox_url)::text AS inbox_url
FROM remote_channel_follows f
JOIN remote_actors ra ON ra.actor_url = f.remote_actor_url
WHERE f.id = $1 AND f.user_id = $2
`

type GetRemoteChannelFollowByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetRemoteChannelFollowByIDRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	State             string    `json:"state"`
	FollowActivityUrl string    `json:"follow_activity_url"`
	CreatedAt         time.Time `json:"created_at"`
	PreferredUsername string    `json:"preferred_username"`
	Domain            string    `json:"domain"`
	InboxUrl          string    `json:"inbox_url"`
}

// One of the caller's follows, joined with the followed actor's identity and
// inbox (the Undo{Follow} delivery target). Scoped by user_id so one user can
// never address another's follow row.
func (q *Queries) GetRemoteChannelFollowByID(ctx context.Context, arg GetRemoteChannelFollowByIDParams) (GetRemoteChannelFollowByIDRow, error) {
	row := q.db.QueryRow(ctx, getRemoteChannelFollowByID, arg.ID, arg.UserID)
	var i GetRemoteChannelFollowByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RemoteActorUrl,
		&i.State,
		&i.FollowActivityUrl,
		&i.CreatedAt,
		&i.PreferredUsername,
		&i.Domain,
		&i.InboxUrl,
	)
	return i, err
}

const hasAcceptedRemoteChannelFollow = `-- name: HasAcceptedRemoteChannelFollow :one
SELECT EXISTS (
    SELECT 1 FROM remote_channel_follows f
    WHERE f.remote_actor_url = $1 AND f.state = 'accepted'
    UNION ALL
    SELECT 1 FROM channel_follow_backs fb
    WHERE fb.remote_actor_url = $1 AND fb.state = 'accepted'
)
`

// The remote-video ingestion gate (§2 anti-spam): does ANY local user have an
// accepted follow edge to this remote actor? An accepted channel follow-back
// (config-parity W12 federation_auto_follow_back) counts too — the instance
// asked for that actor's content by following back, so the "we only ingest
// what we asked for" invariant holds.
func (q *Queries) HasAcceptedRemoteChannelFollow(ctx context.Context, remoteActorUrl string) (bool, error) {
	row := q.db.QueryRow(ctx, hasAcceptedRemoteChannelFollow, remoteActorUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasRemoteChannelFollow = `-- name: HasRemoteChannelFollow :one
SELECT EXISTS (
    SELECT 1 FROM remote_channel_follows
    WHERE remote_actor_url = $1
)
`

// Any outbound follow edge (pending OR accepted) from a local user to this
// remote actor. The auto-follow-back loop guard (config-parity W12): when a
// local user already asked to follow the actor, the instance never adds a
// redundant channel follow-back.
func (q *Queries) HasRemoteChannelFollow(ctx context.Context, remoteActorUrl string) (bool, error) {
	row := q.db.QueryRow(ctx, hasRemoteChannelFollow, remoteActorUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRemoteChannelFollows = `-- name: ListRemoteChannelFollows :many
SELECT f.id, f.remote_actor_url, f.state, f.created_at,
       ra.preferred_username, ra.domain
FROM remote_channel_follows f
JOIN remote_actors ra ON ra.actor_url = f.remote_actor_url
WHERE f.user_id = $1
ORDER BY f.created_at DESC, f.id DESC
LIMIT $3 OFFSET $2
`

type ListRemoteChannelFollowsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListRemoteChannelFollowsRow struct {
	ID                uuid.UUID `json:"id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	State             string    `json:"state"`
	CreatedAt         time.Time `json:"created_at"`
	PreferredUsername string    `json:"preferred_username"`
	Domain            string    `json:"domain"`
}

// The caller's remote follows, newest first, with the followed actor's identity.
func (q *Queries) ListRemoteChannelFollows(ctx context.Context, arg ListRemoteChannelFollowsParams) ([]ListRemoteChannelFollowsRow, error) {
	rows, err := q.db.Query(ctx, listRemoteChannelFollows, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRemoteChannelFollowsRow
	for rows.Next() {
		var i ListRemoteChannelFollowsRow
		if err := rows.Scan(
			&i.ID,
			&i.RemoteActorUrl,
			&i.State,
			&i.CreatedAt,
			&i.PreferredUsername,
			&i.Domain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRemoteChannelFollow = `-- name: UpsertRemoteChannelFollow :one

INSERT INTO remote_channel_follows (user_id, remote_actor_url, follow_activity_url)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, remote_actor_url) DO UPDATE SET user_id = remote_channel_follows.user_id
RETURNING id, user_id, remote_actor_url, state, follow_activity_url, created_at
`

type UpsertRemoteChannelFollowParams struct {
	UserID            uuid.UUID `json:"user_id"`
	RemoteActorUrl    string    `json:"remote_actor_url"`
	FollowActivityUrl string    `json:"follow_activity_url"`
}

// Outbound remote-channel follows: a LOCAL user following a REMOTE channel
// (migration 0052, .ralph/specs/federation-remote-content.md §3).
// Records a user's follow of a remote channel. Idempotent: re-following keeps
// the existing row (state + follow_activity_url untouched — the no-op DO UPDATE
// only exists so the existing row is RETURNed). Callers detect a fresh insert
// by comparing the returned follow_activity_url with the one they minted, and
// only then enqueue the outbound Follow.
func (q *Queries) UpsertRemoteChannelFollow(ctx context.Context, arg UpsertRemoteChannelFollowParams) (RemoteChannelFollow, error) {
	row := q.db.QueryRow(ctx, upsertRemoteChannelFollow, arg.UserID, arg.RemoteActorUrl, arg.FollowActivityUrl)
	var i RemoteChannelFollow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RemoteActorUrl,
		&i.State,
		&i.FollowActivityUrl,
		&i.CreatedAt,
	)
	return i, err
}
