// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountReport = `-- name: CreateAccountReport :execrows
INSERT INTO reports (reporter_id, target_type, reported_user_id, reason)
VALUES ($1, 'account', $2, $3)
ON CONFLICT (reporter_id, reported_user_id) WHERE reported_user_id IS NOT NULL DO NOTHING
`

type CreateAccountReportParams struct {
	ReporterID     uuid.UUID   `json:"reporter_id"`
	ReportedUserID pgtype.UUID `json:"reported_user_id"`
	Reason         string      `json:"reason"`
}

// Report an account (idempotent per reporter+account). A non-existent target
// user raises a foreign-key violation, which the service maps to "invalid
// target". Self-reports are rejected in the service before insert.
func (q *Queries) CreateAccountReport(ctx context.Context, arg CreateAccountReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAccountReport, arg.ReporterID, arg.ReportedUserID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCommentReport = `-- name: CreateCommentReport :execrows
INSERT INTO reports (reporter_id, target_type, comment_id, reason)
VALUES ($1, 'comment', $2, $3)
ON CONFLICT (reporter_id, comment_id) WHERE comment_id IS NOT NULL DO NOTHING
`

type CreateCommentReportParams struct {
	ReporterID uuid.UUID   `json:"reporter_id"`
	CommentID  pgtype.UUID `json:"comment_id"`
	Reason     string      `json:"reason"`
}

// Report a comment (idempotent per reporter+comment). A non-existent comment
// raises a foreign-key violation, which the service maps to "invalid target".
func (q *Queries) CreateCommentReport(ctx context.Context, arg CreateCommentReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCommentReport, arg.ReporterID, arg.CommentID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMessageReport = `-- name: CreateMessageReport :execrows
INSERT INTO reports (reporter_id, target_type, message_id, message_body_snapshot, reason)
VALUES ($1, 'message', $2, $3, $4)
ON CONFLICT (reporter_id, message_id) WHERE message_id IS NOT NULL DO NOTHING
`

type CreateMessageReportParams struct {
	ReporterID          uuid.UUID   `json:"reporter_id"`
	MessageID           pgtype.UUID `json:"message_id"`
	MessageBodySnapshot string      `json:"message_body_snapshot"`
	Reason              string      `json:"reason"`
}

// Report a direct-message message (product-decisions.md §14; idempotent per
// reporter+message). The body snapshot preserves the reported text for the
// moderator even after the sender tombstones it. The caller has already verified
// the reporter is a participant of the message's conversation.
func (q *Queries) CreateMessageReport(ctx context.Context, arg CreateMessageReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createMessageReport,
		arg.ReporterID,
		arg.MessageID,
		arg.MessageBodySnapshot,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRemoteVideoReport = `-- name: CreateRemoteVideoReport :execrows
INSERT INTO reports (reporter_id, target_type, remote_video_id, reason)
VALUES ($1, 'remote_video', $2, $3)
ON CONFLICT (reporter_id, remote_video_id) WHERE remote_video_id IS NOT NULL DO NOTHING
`

type CreateRemoteVideoReportParams struct {
	ReporterID    uuid.UUID   `json:"reporter_id"`
	RemoteVideoID pgtype.UUID `json:"remote_video_id"`
	Reason        string      `json:"reason"`
}

// Report a federated remote video (remote-content §8; idempotent per
// reporter+remote video). A non-existent target raises a foreign-key
// violation, which the service maps to "invalid target".
func (q *Queries) CreateRemoteVideoReport(ctx context.Context, arg CreateRemoteVideoReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createRemoteVideoReport, arg.ReporterID, arg.RemoteVideoID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createVideoReport = `-- name: CreateVideoReport :execrows
INSERT INTO reports (reporter_id, target_type, video_id, reason)
VALUES ($1, 'video', $2, $3)
ON CONFLICT (reporter_id, video_id) WHERE video_id IS NOT NULL DO NOTHING
`

type CreateVideoReportParams struct {
	ReporterID uuid.UUID   `json:"reporter_id"`
	VideoID    pgtype.UUID `json:"video_id"`
	Reason     string      `json:"reason"`
}

// Report a video (idempotent per reporter+video). Returns rows inserted
// (1 = new, 0 = already reported).
func (q *Queries) CreateVideoReport(ctx context.Context, arg CreateVideoReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createVideoReport, arg.ReporterID, arg.VideoID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReport = `-- name: DeleteReport :execrows
DELETE FROM reports WHERE id = $1
`

// Hard-delete a report row (admin purge). Notifications referencing it cascade
// away (0042 FK). Returns rows deleted so the caller can log 0 vs 1; the
// endpoint is idempotent either way.
func (q *Queries) DeleteReport(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReport, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReports = `-- name: ListReports :many
SELECT r.id, r.target_type, r.video_id, r.comment_id, r.reported_user_id, r.remote_video_id,
       r.message_id, r.message_body_snapshot,
       r.reason, r.status,
       r.moderator_note, r.resolved_at, r.created_at,
       u.username AS reporter_username,
       v.title AS video_title,
       cm.body AS comment_body,
       ru.username AS reported_username,
       rv.title AS remote_video_title,
       ra.domain AS remote_video_domain
FROM reports r
JOIN users u ON u.id = r.reporter_id
LEFT JOIN videos v ON v.id = r.video_id
LEFT JOIN comments cm ON cm.id = r.comment_id
LEFT JOIN users ru ON ru.id = r.reported_user_id
LEFT JOIN remote_videos rv ON rv.id = r.remote_video_id
LEFT JOIN remote_actors ra ON ra.actor_url = rv.remote_actor_url
WHERE (NOT $1::bool OR r.status = 'open')
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3 OFFSET $2
`

type ListReportsParams struct {
	OpenOnly     bool  `json:"open_only"`
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type ListReportsRow struct {
	ID                  uuid.UUID          `json:"id"`
	TargetType          string             `json:"target_type"`
	VideoID             pgtype.UUID        `json:"video_id"`
	CommentID           pgtype.UUID        `json:"comment_id"`
	ReportedUserID      pgtype.UUID        `json:"reported_user_id"`
	RemoteVideoID       pgtype.UUID        `json:"remote_video_id"`
	MessageID           pgtype.UUID        `json:"message_id"`
	MessageBodySnapshot string             `json:"message_body_snapshot"`
	Reason              string             `json:"reason"`
	Status              string             `json:"status"`
	ModeratorNote       string             `json:"moderator_note"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt           time.Time          `json:"created_at"`
	ReporterUsername    string             `json:"reporter_username"`
	VideoTitle          *string            `json:"video_title"`
	CommentBody         *string            `json:"comment_body"`
	ReportedUsername    *string            `json:"reported_username"`
	RemoteVideoTitle    *string            `json:"remote_video_title"`
	RemoteVideoDomain   *string            `json:"remote_video_domain"`
}

// The moderation queue, newest first, with the reporter's username and the
// target context (video title / comment body / reported account username /
// remote video title+domain / message body snapshot). When open_only is true,
// only unresolved (status='open') reports are returned.
func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error) {
	rows, err := q.db.Query(ctx, listReports, arg.OpenOnly, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.VideoID,
			&i.CommentID,
			&i.ReportedUserID,
			&i.RemoteVideoID,
			&i.MessageID,
			&i.MessageBodySnapshot,
			&i.Reason,
			&i.Status,
			&i.ModeratorNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.ReporterUsername,
			&i.VideoTitle,
			&i.CommentBody,
			&i.ReportedUsername,
			&i.RemoteVideoTitle,
			&i.RemoteVideoDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :one
UPDATE reports
SET status         = $1,
    moderator_note = $2,
    resolved_by    = $3,
    resolved_at    = now(),
    updated_at     = now()
WHERE id = $4
RETURNING reporter_id
`

type ResolveReportParams struct {
	Status        string      `json:"status"`
	ModeratorNote string      `json:"moderator_note"`
	ResolvedBy    pgtype.UUID `json:"resolved_by"`
	ID            uuid.UUID   `json:"id"`
}

// Mark a report accepted/rejected with a moderator note. Returns the reporter
// so the caller can notify them (best-effort); an unknown id yields no rows,
// which the service maps to "not found".
func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveReport,
		arg.Status,
		arg.ModeratorNote,
		arg.ResolvedBy,
		arg.ID,
	)
	var reporter_id uuid.UUID
	err := row.Scan(&reporter_id)
	return reporter_id, err
}
