// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommentReport = `-- name: CreateCommentReport :execrows
INSERT INTO reports (reporter_id, target_type, comment_id, reason)
VALUES ($1, 'comment', $2, $3)
ON CONFLICT (reporter_id, comment_id) WHERE comment_id IS NOT NULL DO NOTHING
`

type CreateCommentReportParams struct {
	ReporterID uuid.UUID   `json:"reporter_id"`
	CommentID  pgtype.UUID `json:"comment_id"`
	Reason     string      `json:"reason"`
}

// Report a comment (idempotent per reporter+comment). A non-existent comment
// raises a foreign-key violation, which the service maps to "invalid target".
func (q *Queries) CreateCommentReport(ctx context.Context, arg CreateCommentReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCommentReport, arg.ReporterID, arg.CommentID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createVideoReport = `-- name: CreateVideoReport :execrows
INSERT INTO reports (reporter_id, target_type, video_id, reason)
VALUES ($1, 'video', $2, $3)
ON CONFLICT (reporter_id, video_id) WHERE video_id IS NOT NULL DO NOTHING
`

type CreateVideoReportParams struct {
	ReporterID uuid.UUID   `json:"reporter_id"`
	VideoID    pgtype.UUID `json:"video_id"`
	Reason     string      `json:"reason"`
}

// Report a video (idempotent per reporter+video). Returns rows inserted
// (1 = new, 0 = already reported).
func (q *Queries) CreateVideoReport(ctx context.Context, arg CreateVideoReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createVideoReport, arg.ReporterID, arg.VideoID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReports = `-- name: ListReports :many
SELECT r.id, r.target_type, r.video_id, r.comment_id, r.reason, r.status,
       r.moderator_note, r.resolved_at, r.created_at,
       u.username AS reporter_username,
       v.title AS video_title,
       cm.body AS comment_body
FROM reports r
JOIN users u ON u.id = r.reporter_id
LEFT JOIN videos v ON v.id = r.video_id
LEFT JOIN comments cm ON cm.id = r.comment_id
WHERE (NOT $1::bool OR r.status = 'open')
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3 OFFSET $2
`

type ListReportsParams struct {
	OpenOnly     bool  `json:"open_only"`
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type ListReportsRow struct {
	ID               uuid.UUID          `json:"id"`
	TargetType       string             `json:"target_type"`
	VideoID          pgtype.UUID        `json:"video_id"`
	CommentID        pgtype.UUID        `json:"comment_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	ModeratorNote    string             `json:"moderator_note"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt        time.Time          `json:"created_at"`
	ReporterUsername string             `json:"reporter_username"`
	VideoTitle       *string            `json:"video_title"`
	CommentBody      *string            `json:"comment_body"`
}

// The moderation queue, newest first, with the reporter's username and the
// target context (video title / comment body). When open_only is true, only
// unresolved (status='open') reports are returned.
func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error) {
	rows, err := q.db.Query(ctx, listReports, arg.OpenOnly, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.VideoID,
			&i.CommentID,
			&i.Reason,
			&i.Status,
			&i.ModeratorNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.ReporterUsername,
			&i.VideoTitle,
			&i.CommentBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :execrows
UPDATE reports
SET status         = $1,
    moderator_note = $2,
    resolved_by    = $3,
    resolved_at    = now(),
    updated_at     = now()
WHERE id = $4
`

type ResolveReportParams struct {
	Status        string      `json:"status"`
	ModeratorNote string      `json:"moderator_note"`
	ResolvedBy    pgtype.UUID `json:"resolved_by"`
	ID            uuid.UUID   `json:"id"`
}

// Mark a report accepted/rejected with a moderator note. Returns the number of
// rows matched so the caller can 404 on an unknown id.
func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveReport,
		arg.Status,
		arg.ModeratorNote,
		arg.ResolvedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
