// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_outbox.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueSearchEvents = `-- name: ClaimDueSearchEvents :many
WITH claimed AS (
    UPDATE search_outbox
    SET next_attempt_at = now() + ($1::int * interval '1 second')
    WHERE id IN (
        SELECT id FROM search_outbox
        WHERE state = 'pending' AND next_attempt_at <= now()
        ORDER BY id
        LIMIT $2
        FOR UPDATE SKIP LOCKED
    )
    RETURNING id, event_id, event_type, payload, attempts, created_at
)
SELECT id, event_id, event_type, payload, attempts, created_at
FROM claimed
ORDER BY id
`

type ClaimDueSearchEventsParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	BatchSize    int32 `json:"batch_size"`
}

type ClaimDueSearchEventsRow struct {
	ID        int64     `json:"id"`
	EventID   uuid.UUID `json:"event_id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
	Attempts  int32     `json:"attempts"`
	CreatedAt time.Time `json:"created_at"`
}

// LEASES due, still-pending events oldest first, building the batched
// /internal/v1/events envelope.
//
// Previously a bare SELECT: two nodes would build two envelopes from the same
// rows and both POST them. The search service dedupes on event_id so the index
// stays correct, which is why this is the least harmful of the three -- but it is
// still double the requests and double the payload for no benefit.
// The lease is next_attempt_at pushed forward: a claimed row stops being due for
// lease_seconds, so a second worker's claim skips it and a CRASHED worker's row
// becomes due again by itself. FOR UPDATE SKIP LOCKED makes concurrent claimers
// take disjoint rows without blocking each other.
// search_outbox has no updated_at column, so only the lease is written.
// The claim is wrapped in a CTE with an OUTER ORDER BY because UPDATE ...
// RETURNING does not preserve the order of the subquery that chose the rows --
// PostgreSQL returns them in whatever order it updated them. The "oldest first"
// contract is real: these rows carry ordered side effects (an index mutation
// applied out of order leaves the index stale; activities delivered out of order
// are visible to the remote server), so the ordering has to be restated here.
func (q *Queries) ClaimDueSearchEvents(ctx context.Context, arg ClaimDueSearchEventsParams) ([]ClaimDueSearchEventsRow, error) {
	rows, err := q.db.Query(ctx, claimDueSearchEvents, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueSearchEventsRow
	for rows.Next() {
		var i ClaimDueSearchEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deadLetterSearchEvent = `-- name: DeadLetterSearchEvent :exec
UPDATE search_outbox
SET state = 'dead', attempts = attempts + 1, last_error = $2
WHERE id = $1
`

type DeadLetterSearchEventParams struct {
	ID        int64  `json:"id"`
	LastError string `json:"last_error"`
}

func (q *Queries) DeadLetterSearchEvent(ctx context.Context, arg DeadLetterSearchEventParams) error {
	_, err := q.db.Exec(ctx, deadLetterSearchEvent, arg.ID, arg.LastError)
	return err
}

const enqueueSearchEvent = `-- name: EnqueueSearchEvent :exec

INSERT INTO search_outbox (event_type, payload)
VALUES ($1, $2)
`

type EnqueueSearchEventParams struct {
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

// Durable outbound queue + search-document sources for the vidra-search
// integration (migration 0092, search-service W4). Mirrors the federation
// delivery queue's claim/reschedule/dead-letter shape.
// Best-effort append of one event to the search outbox (single INSERT). The
// caller logs + metrics on failure and NEVER fails the request path — a search
// event is non-authoritative and the reconcile sweep is the backstop.
func (q *Queries) EnqueueSearchEvent(ctx context.Context, arg EnqueueSearchEventParams) error {
	_, err := q.db.Exec(ctx, enqueueSearchEvent, arg.EventType, arg.Payload)
	return err
}

const getVideoSearchDoc = `-- name: GetVideoSearchDoc :one
SELECT v.id, v.channel_id, v.title, v.description, v.privacy, v.state,
       v.category, v.language, v.license, v.is_sensitive,
       v.created_at, v.updated_at, v.publish_at,
       c.handle AS channel_handle, c.display_name AS channel_name,
       c.owner_id,
       au.display_name AS owner_display_name,
       au.unlisted AS owner_unlisted,
       vm.duration_seconds,
       COALESCE(vc.views, 0)::bigint AS views,
       (SELECT count(*) FROM video_ratings r WHERE r.video_id = v.id AND r.rating = 'like')::bigint AS likes,
       COALESCE(
           (SELECT array_agg(t.tag ORDER BY t.tag) FROM video_tags t WHERE t.video_id = v.id),
           '{}'
       )::text[] AS tags
FROM videos v
JOIN channels c ON c.id = v.channel_id
JOIN users au ON au.id = c.owner_id
LEFT JOIN video_metadata vm ON vm.video_id = v.id
LEFT JOIN video_view_counts vc ON vc.video_id = v.id
WHERE v.id = $1
`

type GetVideoSearchDocRow struct {
	ID               uuid.UUID          `json:"id"`
	ChannelID        uuid.UUID          `json:"channel_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Privacy          string             `json:"privacy"`
	State            string             `json:"state"`
	Category         *string            `json:"category"`
	Language         *string            `json:"language"`
	License          *string            `json:"license"`
	IsSensitive      bool               `json:"is_sensitive"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	PublishAt        pgtype.Timestamptz `json:"publish_at"`
	ChannelHandle    string             `json:"channel_handle"`
	ChannelName      string             `json:"channel_name"`
	OwnerID          uuid.UUID          `json:"owner_id"`
	OwnerDisplayName string             `json:"owner_display_name"`
	OwnerUnlisted    bool               `json:"owner_unlisted"`
	DurationSeconds  *int32             `json:"duration_seconds"`
	Views            int64              `json:"views"`
	Likes            int64              `json:"likes"`
	Tags             []string           `json:"tags"`
}

// Full search-document payload for one local video: the video, its owning
// channel + account, aggregate view/like counts, duration, and tag set. Drives
// the video.upsert event payload. Eligibility is DERIVED in the search service
// from privacy+state+owner_unlisted, so those raw fields ride along.
func (q *Queries) GetVideoSearchDoc(ctx context.Context, id uuid.UUID) (GetVideoSearchDocRow, error) {
	row := q.db.QueryRow(ctx, getVideoSearchDoc, id)
	var i GetVideoSearchDocRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Privacy,
		&i.State,
		&i.Category,
		&i.Language,
		&i.License,
		&i.IsSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.ChannelHandle,
		&i.ChannelName,
		&i.OwnerID,
		&i.OwnerDisplayName,
		&i.OwnerUnlisted,
		&i.DurationSeconds,
		&i.Views,
		&i.Likes,
		&i.Tags,
	)
	return i, err
}

const listVideoSearchDocsPage = `-- name: ListVideoSearchDocsPage :many
SELECT v.id, v.channel_id, v.title, v.description, v.privacy, v.state,
       v.category, v.language, v.license, v.is_sensitive,
       v.created_at, v.updated_at, v.publish_at,
       c.handle AS channel_handle, c.display_name AS channel_name,
       c.owner_id,
       au.display_name AS owner_display_name,
       au.unlisted AS owner_unlisted,
       vm.duration_seconds,
       COALESCE(vc.views, 0)::bigint AS views,
       (SELECT count(*) FROM video_ratings r WHERE r.video_id = v.id AND r.rating = 'like')::bigint AS likes,
       COALESCE(
           (SELECT array_agg(t.tag ORDER BY t.tag) FROM video_tags t WHERE t.video_id = v.id),
           '{}'
       )::text[] AS tags
FROM videos v
JOIN channels c ON c.id = v.channel_id
JOIN users au ON au.id = c.owner_id
LEFT JOIN video_metadata vm ON vm.video_id = v.id
LEFT JOIN video_view_counts vc ON vc.video_id = v.id
WHERE v.privacy = 'public' AND v.state = 'published'
  AND NOT au.unlisted
  AND NOT EXISTS (SELECT 1 FROM video_blocks b WHERE b.video_id = v.id)
  AND v.id > $1
ORDER BY v.id
LIMIT $2
`

type ListVideoSearchDocsPageParams struct {
	After    uuid.UUID `json:"after"`
	PageSize int32     `json:"page_size"`
}

type ListVideoSearchDocsPageRow struct {
	ID               uuid.UUID          `json:"id"`
	ChannelID        uuid.UUID          `json:"channel_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Privacy          string             `json:"privacy"`
	State            string             `json:"state"`
	Category         *string            `json:"category"`
	Language         *string            `json:"language"`
	License          *string            `json:"license"`
	IsSensitive      bool               `json:"is_sensitive"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	PublishAt        pgtype.Timestamptz `json:"publish_at"`
	ChannelHandle    string             `json:"channel_handle"`
	ChannelName      string             `json:"channel_name"`
	OwnerID          uuid.UUID          `json:"owner_id"`
	OwnerDisplayName string             `json:"owner_display_name"`
	OwnerUnlisted    bool               `json:"owner_unlisted"`
	DurationSeconds  *int32             `json:"duration_seconds"`
	Views            int64              `json:"views"`
	Likes            int64              `json:"likes"`
	Tags             []string           `json:"tags"`
}

// One keyset page of eligible (public, published, not blocked, owner not
// unlisted) local video search docs for the reconcile sweep, ordered by id for
// stable paging (id > after; pass the nil UUID for the first page). Same column
// projection as GetVideoSearchDoc so both build the identical doc payload.
func (q *Queries) ListVideoSearchDocsPage(ctx context.Context, arg ListVideoSearchDocsPageParams) ([]ListVideoSearchDocsPageRow, error) {
	rows, err := q.db.Query(ctx, listVideoSearchDocsPage, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVideoSearchDocsPageRow
	for rows.Next() {
		var i ListVideoSearchDocsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Privacy,
			&i.State,
			&i.Category,
			&i.Language,
			&i.License,
			&i.IsSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishAt,
			&i.ChannelHandle,
			&i.ChannelName,
			&i.OwnerID,
			&i.OwnerDisplayName,
			&i.OwnerUnlisted,
			&i.DurationSeconds,
			&i.Views,
			&i.Likes,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSearchEventDelivered = `-- name: MarkSearchEventDelivered :exec
UPDATE search_outbox SET state = 'delivered' WHERE id = $1
`

func (q *Queries) MarkSearchEventDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSearchEventDelivered, id)
	return err
}

const pruneSearchOutbox = `-- name: PruneSearchOutbox :execrows
DELETE FROM search_outbox
WHERE id IN (
    SELECT o.id FROM search_outbox o
    WHERE o.state = $1
      AND o.state <> 'pending'
      AND o.created_at < $2
    ORDER BY o.created_at, o.id
    LIMIT $3
)
`

type PruneSearchOutboxParams struct {
	State     string    `json:"state"`
	Cutoff    time.Time `json:"cutoff"`
	BatchSize int32     `json:"batch_size"`
}

// One batch of expired TERMINAL outbox rows, oldest first (migration 0122).
//
// Called once per prunable state so 'delivered' and 'dead' can carry different
// windows: a delivered row is finished work the search service already holds,
// while a dead row is the only surviving evidence of WHY a delivery failed.
//
// `state <> 'pending'` is a structural guard, not a redundancy. It is what makes
// an undelivered row undeletable by this query no matter what a caller passes:
// a pending row is an index mutation, or a privacy-critical user.history_deleted
// purge, that has NOT happened yet, and deleting one loses it silently -- there
// is no second copy and nothing would ever notice. The Go worker never asks for
// 'pending'; this is what happens if some future caller does.
//
// Batched like PruneQoEEvents, and ordered by (created_at, id) for the same
// reason the due claim restates its order: an unbounded DELETE would hold locks
// across the whole backlog while the drainer is trying to claim from the same
// table. Unlike qoe_events the id here is a BIGSERIAL, so it agrees with
// created_at rather than being random -- it is the tiebreaker, and the ordering
// rides search_outbox_prune_idx either way.
func (q *Queries) PruneSearchOutbox(ctx context.Context, arg PruneSearchOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSearchOutbox, arg.State, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleSearchEvent = `-- name: RescheduleSearchEvent :exec
UPDATE search_outbox
SET attempts = attempts + 1, next_attempt_at = $2, last_error = $3
WHERE id = $1
`

type RescheduleSearchEventParams struct {
	ID            int64     `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
}

func (q *Queries) RescheduleSearchEvent(ctx context.Context, arg RescheduleSearchEventParams) error {
	_, err := q.db.Exec(ctx, rescheduleSearchEvent, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const searchOutboxDepth = `-- name: SearchOutboxDepth :many
SELECT state, count(*)::bigint AS depth
FROM search_outbox
GROUP BY state
`

type SearchOutboxDepthRow struct {
	State string `json:"state"`
	Depth int64  `json:"depth"`
}

// Queue-depth gauge source (vidra_queue_depth{queue="search_outbox",state=...}).
func (q *Queries) SearchOutboxDepth(ctx context.Context) ([]SearchOutboxDepthRow, error) {
	rows, err := q.db.Query(ctx, searchOutboxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchOutboxDepthRow
	for rows.Next() {
		var i SearchOutboxDepthRow
		if err := rows.Scan(&i.State, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
