// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, refresh_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_hash, user_agent, revoked_at, expires_at, created_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID `json:"user_id"`
	RefreshHash string    `json:"refresh_hash"`
	UserAgent   string    `json:"user_agent"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type CreateSessionRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt   time.Time          `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

// Refresh-token sessions. The raw refresh token is never stored — only its
// SHA-256 hash — and rotation revokes the prior row. ip_address is intentionally
// left out of these queries (handled at a later slice) to keep the Go surface
// free of the INET type for now.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.UserAgent,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_hash, user_agent, revoked_at, expires_at, created_at
FROM sessions
WHERE refresh_hash = $1
`

type GetSessionByRefreshHashRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt   time.Time          `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshHash string) (GetSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshHash)
	var i GetSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.UserAgent,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
