// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings_version.sql

package sqlcgen

import (
	"context"
)

const bumpSettingsVersion = `-- name: BumpSettingsVersion :one
INSERT INTO settings_version (id, version, updated_at)
VALUES (1, 1, now())
ON CONFLICT (id) DO UPDATE
SET version = settings_version.version + 1, updated_at = now()
RETURNING version
`

// Advance the invalidation token by one and return the new value. Called after
// every write to an admin-editable store that is cached in memory; the returned
// value is what makes a bump observable to a test without a second read.
//
// Written as an upsert, not an UPDATE, so the counter self-heals if the
// singleton row is ever missing: an UPDATE would silently affect zero rows and
// leave the fleet stale with no error to notice.
func (q *Queries) BumpSettingsVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, bumpSettingsVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getSettingsVersion = `-- name: GetSettingsVersion :one
SELECT coalesce(max(version), 0)::BIGINT AS version
FROM settings_version
WHERE id = 1
`

// The current cross-replica invalidation token (migration 0121). Every api
// replica reads this on a short jittered ticker; when the number differs from
// the one it last acted on, the three boot-loaded caches (instance settings,
// instance documents, branding images) are reloaded. Aggregated rather than a
// bare SELECT so a database whose singleton row went missing reads 0 instead of
// raising pgx.ErrNoRows every tick — the poller's job is bounded staleness, not
// a per-interval error log.
func (q *Queries) GetSettingsVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSettingsVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}
