// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_migrations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const abortStorageMigrationWithCleanup = `-- name: AbortStorageMigrationWithCleanup :execrows
UPDATE storage_migrations
SET state = 'aborting', paused_reason = '', resume_state = '', last_error = $2, updated_at = now()
WHERE id = $1 AND state IN ('enumerating', 'copying', 'synced', 'paused')
`

type AbortStorageMigrationWithCleanupParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

// Cancel AND remove the partial copies this campaign put on the destination.
//
// It is a STATE rather than a synchronous delete because the work is unbounded:
// a campaign aborted at 90% has hundreds of thousands of objects to remove, and
// an admin request must not hold a connection open for them. The leader-gated
// sweep drains it in batches, exactly as the delete-source phase does at the
// other end of a successful move -- same reason, too: it is destructive, so
// exactly one process may do it.
//
// Guarded on the PRE-cutover phases. After cutover the destination is the store
// the api SERVES FROM, and "clean up the destination" would mean emptying the
// live library.
func (q *Queries) AbortStorageMigrationWithCleanup(ctx context.Context, arg AbortStorageMigrationWithCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, abortStorageMigrationWithCleanup, arg.ID, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelStorageMigration = `-- name: CancelStorageMigration :execrows
UPDATE storage_migrations
SET state = 'cancelled', paused_reason = '', resume_state = '', updated_at = now()
WHERE id = $1 AND state NOT IN ('done', 'cancelled', 'failed')
`

// Operator abort. Object rows stop being claimed immediately: the claim query
// joins the campaign and only takes rows from a 'copying'/'synced' one.
func (q *Queries) CancelStorageMigration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelStorageMigration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueStorageMigrationObjects = `-- name: ClaimDueStorageMigrationObjects :many
UPDATE storage_migration_objects
SET next_attempt_at = now() + interval '30 minutes',
    state = 'copying', updated_at = now()
WHERE object_key IN (
    SELECT o.object_key
    FROM storage_migration_objects o
    JOIN storage_migrations m ON m.id = o.campaign_id
    WHERE o.state = 'pending'
      AND o.next_attempt_at <= now()
      AND m.state IN ('copying', 'synced')
    ORDER BY o.next_attempt_at, o.object_key
    LIMIT $1
    FOR UPDATE OF o SKIP LOCKED
)
RETURNING object_key, campaign_id, attempts
`

type ClaimDueStorageMigrationObjectsRow struct {
	ObjectKey  string    `json:"object_key"`
	CampaignID uuid.UUID `json:"campaign_id"`
	Attempts   int32     `json:"attempts"`
}

// Atomically claim due objects for copying, oldest first, by flipping them to
// 'copying' and pushing the lease 30 minutes out.
//
// FOR UPDATE OF o SKIP LOCKED is what makes this safe on every instance at once:
// concurrent claimers take disjoint rows instead of racing to re-evaluate the
// subquery. Only the object rows are locked -- the campaign join is a read, and
// locking it would serialise every worker behind one row.
//
// The ORDER BY is TOTAL (next_attempt_at, object_key): a partial order lets
// Postgres return a different arbitrary tie-break per claimer, which turns
// "oldest first" into "whatever the plan felt like" under contention.
func (q *Queries) ClaimDueStorageMigrationObjects(ctx context.Context, limit int32) ([]ClaimDueStorageMigrationObjectsRow, error) {
	rows, err := q.db.Query(ctx, claimDueStorageMigrationObjects, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueStorageMigrationObjectsRow
	for rows.Next() {
		var i ClaimDueStorageMigrationObjectsRow
		if err := rows.Scan(&i.ObjectKey, &i.CampaignID, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStorageMigrationObjectFailuresByCategory = `-- name: CountStorageMigrationObjectFailuresByCategory :many
SELECT
    last_error AS category,
    count(*) FILTER (WHERE state = 'failed')::bigint AS terminal,
    count(*) FILTER (WHERE state <> 'failed')::bigint AS retrying
FROM storage_migration_objects
WHERE campaign_id = $1 AND last_error <> ''
GROUP BY last_error
ORDER BY last_error
`

type CountStorageMigrationObjectFailuresByCategoryRow struct {
	Category string `json:"category"`
	Terminal int64  `json:"terminal"`
	Retrying int64  `json:"retrying"`
}

// The failure breakdown a stalling campaign needs, and the reason it exists.
//
// objects_failed counts rows in state 'failed', and a row only reaches 'failed'
// once its whole five-attempt budget is spent -- so a campaign whose every
// object is being refused shows objects_failed 0 and last_error ” for as long
// as an hour of backoff takes. The operator sees progress stall and is told
// nothing. The short fixed categories exist precisely to be projected into an
// operator surface, and until now no surface projected them.
//
// RETRYING and TERMINAL are counted separately because they are different
// questions: "this is still being retried" and "this object has been given up
// on" call for different operator actions, and collapsing them would let a
// finished campaign's dead letters look like work in progress.
func (q *Queries) CountStorageMigrationObjectFailuresByCategory(ctx context.Context, campaignID uuid.UUID) ([]CountStorageMigrationObjectFailuresByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countStorageMigrationObjectFailuresByCategory, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountStorageMigrationObjectFailuresByCategoryRow
	for rows.Next() {
		var i CountStorageMigrationObjectFailuresByCategoryRow
		if err := rows.Scan(&i.Category, &i.Terminal, &i.Retrying); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStorageMigrationObjectsByState = `-- name: CountStorageMigrationObjectsByState :many
SELECT state, count(*)::bigint AS count
FROM storage_migration_objects
WHERE campaign_id = $1
GROUP BY state
ORDER BY state
`

type CountStorageMigrationObjectsByStateRow struct {
	State string `json:"state"`
	Count int64  `json:"count"`
}

// The per-state breakdown shown on one campaign.
func (q *Queries) CountStorageMigrationObjectsByState(ctx context.Context, campaignID uuid.UUID) ([]CountStorageMigrationObjectsByStateRow, error) {
	rows, err := q.db.Query(ctx, countStorageMigrationObjectsByState, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountStorageMigrationObjectsByStateRow
	for rows.Next() {
		var i CountStorageMigrationObjectsByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUncopiedStorageMigrationObjects = `-- name: CountUncopiedStorageMigrationObjects :one
SELECT count(*)::bigint AS count FROM storage_migration_objects
WHERE campaign_id = $1 AND state IN ('pending', 'copying')
`

// Objects not yet proven to be in the target. Zero is the precondition for
// declaring a campaign synced, and for ever deleting anything from the source.
func (q *Queries) CountUncopiedStorageMigrationObjects(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUncopiedStorageMigrationObjects, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnfinishedStorageMigrationObjects = `-- name: CountUnfinishedStorageMigrationObjects :one
SELECT count(*)::bigint AS count FROM storage_migration_objects
WHERE campaign_id = $1 AND state IN ('pending', 'copying', 'verified')
`

// Objects whose source copy still exists (or that never arrived). Zero ends a
// campaign; 'failed' rows deliberately do not count, because a dead-lettered
// object is a reported fact, not unfinished work.
func (q *Queries) CountUnfinishedStorageMigrationObjects(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnfinishedStorageMigrationObjects, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStorageMigration = `-- name: CreateStorageMigration :one

INSERT INTO storage_migrations (source_desc, target_desc, request_id, correlation_id)
VALUES ($1, $2, $3, $4)
RETURNING id, source_desc, target_desc, state, objects_total, objects_done, objects_failed, last_error, observed_cutover_at, created_at, updated_at, paused_reason, resume_state, request_id, correlation_id, worker_id
`

type CreateStorageMigrationParams struct {
	SourceDesc    string `json:"source_desc"`
	TargetDesc    string `json:"target_desc"`
	RequestID     string `json:"request_id"`
	CorrelationID string `json:"correlation_id"`
}

// Storage migration campaigns + the per-object location record (migration 0107,
// phase-2 storage work items 4 and 5).
//
// The object ledger is a durable queue born on the convention every NEW queue
// must use (interfaces.md section 7): FOR UPDATE SKIP LOCKED claims, a
// lease-shaped next_attempt_at that the worker renews while it copies, and
// terminal writes guarded on the state the claim put the row in. That is what
// makes the copy worker safe to run UNLEADERED on every instance -- more
// instances simply copy faster.
//
// Object keys are never rewritten by a move, so nothing here touches
// media_ipfs_pins (whose primary key IS a storage key) or video_files.storage_key.
// Start a campaign. The partial unique index storage_migrations_single_active_idx
// makes a second live campaign a constraint violation rather than a race.
//
// The identity columns (0145) are written HERE, by the admin request that starts
// the move, and the second trigger carries them onto the job_runs row the
// projection creates. A campaign is the one queue whose enqueue is always an
// operator act, so there is always a request to name.
func (q *Queries) CreateStorageMigration(ctx context.Context, arg CreateStorageMigrationParams) (StorageMigration, error) {
	row := q.db.QueryRow(ctx, createStorageMigration,
		arg.SourceDesc,
		arg.TargetDesc,
		arg.RequestID,
		arg.CorrelationID,
	)
	var i StorageMigration
	err := row.Scan(
		&i.ID,
		&i.SourceDesc,
		&i.TargetDesc,
		&i.State,
		&i.ObjectsTotal,
		&i.ObjectsDone,
		&i.ObjectsFailed,
		&i.LastError,
		&i.ObservedCutoverAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedReason,
		&i.ResumeState,
		&i.RequestID,
		&i.CorrelationID,
		&i.WorkerID,
	)
	return i, err
}

const deleteStorageMigrationObject = `-- name: DeleteStorageMigrationObject :exec
DELETE FROM storage_migration_objects WHERE object_key = $1
`

// Forget one object after its destination copy has been removed. The row is
// deleted rather than marked, because there is no honest state left for it: the
// bytes are on neither side of the ledger the row describes.
func (q *Queries) DeleteStorageMigrationObject(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, deleteStorageMigrationObject, objectKey)
	return err
}

const deleteTerminalStorageMigrationObjects = `-- name: DeleteTerminalStorageMigrationObjects :execrows
DELETE FROM storage_migration_objects o
USING storage_migrations m
WHERE m.id = o.campaign_id
  AND m.state IN ('done', 'cancelled', 'failed')
`

// Clear the object ledger of every campaign that is OVER, so the next campaign
// enumerates the source from scratch.
//
// It exists because storage_migration_objects is primary-keyed on the STORAGE
// KEY alone -- object keys are never rewritten by a move, so one row per key is
// the right shape while a campaign runs -- and those rows outlive the campaign
// that created them. Without this, the next campaign's enumeration (an ON
// CONFLICT DO NOTHING upsert whose rowcount IS the answer to "did anything
// appear since?") inserts NOTHING, the new campaign starts with an empty
// ledger, and an empty ledger reads as "nothing left to copy": one sweep later
// it announces that every object in the source is verified in the target with
// objects_total 0. That is the sentence an operator cuts over on. It bites a
// retry after a cancel AND the second move an instance ever makes, which re-uses
// the same keys.
//
// The predicate is on the CAMPAIGN's state, never on a row id, so it can never
// touch a live campaign's ledger however this races with a concurrent start.
// The campaign row keeps its own objects_total/done/failed counters, which are
// the durable record of what that move did.
func (q *Queries) DeleteTerminalStorageMigrationObjects(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTerminalStorageMigrationObjects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStorageMigrationObject = `-- name: FailStorageMigrationObject :exec
UPDATE storage_migration_objects
SET state = 'failed', attempts = attempts + 1, last_error = $2, updated_at = now()
WHERE object_key = $1 AND state = 'copying'
`

type FailStorageMigrationObjectParams struct {
	ObjectKey string `json:"object_key"`
	LastError string `json:"last_error"`
}

// Dead-letter: no further retries. last_error is a CATEGORY, never a key or a
// raw backend error -- it is projected into the admin jobs overview.
func (q *Queries) FailStorageMigrationObject(ctx context.Context, arg FailStorageMigrationObjectParams) error {
	_, err := q.db.Exec(ctx, failStorageMigrationObject, arg.ObjectKey, arg.LastError)
	return err
}

const getActiveStorageMigration = `-- name: GetActiveStorageMigration :one
SELECT id, source_desc, target_desc, state, objects_total, objects_done, objects_failed, last_error, observed_cutover_at, created_at, updated_at, paused_reason, resume_state, request_id, correlation_id, worker_id FROM storage_migrations
WHERE state NOT IN ('done', 'cancelled', 'failed')
ORDER BY created_at DESC, id
LIMIT 1
`

// The one live campaign, if there is one. LIMIT 1 is belt-and-braces: the
// partial unique index already guarantees at most one row matches.
func (q *Queries) GetActiveStorageMigration(ctx context.Context) (StorageMigration, error) {
	row := q.db.QueryRow(ctx, getActiveStorageMigration)
	var i StorageMigration
	err := row.Scan(
		&i.ID,
		&i.SourceDesc,
		&i.TargetDesc,
		&i.State,
		&i.ObjectsTotal,
		&i.ObjectsDone,
		&i.ObjectsFailed,
		&i.LastError,
		&i.ObservedCutoverAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedReason,
		&i.ResumeState,
		&i.RequestID,
		&i.CorrelationID,
		&i.WorkerID,
	)
	return i, err
}

const getStorageMigration = `-- name: GetStorageMigration :one
SELECT id, source_desc, target_desc, state, objects_total, objects_done, objects_failed, last_error, observed_cutover_at, created_at, updated_at, paused_reason, resume_state, request_id, correlation_id, worker_id FROM storage_migrations WHERE id = $1
`

func (q *Queries) GetStorageMigration(ctx context.Context, id uuid.UUID) (StorageMigration, error) {
	row := q.db.QueryRow(ctx, getStorageMigration, id)
	var i StorageMigration
	err := row.Scan(
		&i.ID,
		&i.SourceDesc,
		&i.TargetDesc,
		&i.State,
		&i.ObjectsTotal,
		&i.ObjectsDone,
		&i.ObjectsFailed,
		&i.LastError,
		&i.ObservedCutoverAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedReason,
		&i.ResumeState,
		&i.RequestID,
		&i.CorrelationID,
		&i.WorkerID,
	)
	return i, err
}

const hasActiveStorageMigration = `-- name: HasActiveStorageMigration :one
SELECT EXISTS (
    SELECT 1 FROM storage_migrations WHERE state NOT IN ('done', 'cancelled')
)
`

// The media-GC interlock. Deliberately WIDER than "live": a 'failed' campaign
// still counts, because a move that stopped half-way is exactly the state in
// which "no database row references this object" stops being evidence about
// either store. Only an operator resolving it (cancel, or a completed run) lets
// destructive sweeps resume.
func (q *Queries) HasActiveStorageMigration(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveStorageMigration)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDestinationCopiesToRemove = `-- name: ListDestinationCopiesToRemove :many
SELECT object_key FROM storage_migration_objects
WHERE campaign_id = $1 AND state = 'verified'
ORDER BY object_key
LIMIT $2
`

type ListDestinationCopiesToRemoveParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Limit      int32     `json:"limit"`
}

// The abort clean-up batch: objects this campaign PROVED it wrote to the
// destination. Only 'verified' rows qualify -- a row that never reached that
// state was never confirmed to be on the destination, and issuing a delete for
// a key that may be the SOURCE's is the one mistake this whole package is built
// to make impossible.
func (q *Queries) ListDestinationCopiesToRemove(ctx context.Context, arg ListDestinationCopiesToRemoveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDestinationCopiesToRemove, arg.CampaignID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageMigrations = `-- name: ListStorageMigrations :many
SELECT id, source_desc, target_desc, state, objects_total, objects_done, objects_failed, last_error, observed_cutover_at, created_at, updated_at, paused_reason, resume_state, request_id, correlation_id, worker_id FROM storage_migrations ORDER BY created_at DESC, id LIMIT $1
`

func (q *Queries) ListStorageMigrations(ctx context.Context, limit int32) ([]StorageMigration, error) {
	rows, err := q.db.Query(ctx, listStorageMigrations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageMigration
	for rows.Next() {
		var i StorageMigration
		if err := rows.Scan(
			&i.ID,
			&i.SourceDesc,
			&i.TargetDesc,
			&i.State,
			&i.ObjectsTotal,
			&i.ObjectsDone,
			&i.ObjectsFailed,
			&i.LastError,
			&i.ObservedCutoverAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedReason,
			&i.ResumeState,
			&i.RequestID,
			&i.CorrelationID,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedStorageMigrationObjects = `-- name: ListVerifiedStorageMigrationObjects :many
SELECT object_key FROM storage_migration_objects
WHERE campaign_id = $1 AND state = 'verified'
ORDER BY object_key
LIMIT $2
`

type ListVerifiedStorageMigrationObjectsParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Limit      int32     `json:"limit"`
}

// The delete-source batch: objects proven to be in the target whose source copy
// is still there.
func (q *Queries) ListVerifiedStorageMigrationObjects(ctx context.Context, arg ListVerifiedStorageMigrationObjectsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listVerifiedStorageMigrationObjects, arg.CampaignID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStorageMigrationCutover = `-- name: MarkStorageMigrationCutover :exec
UPDATE storage_migrations
SET state = 'cutover',
    observed_cutover_at = COALESCE(observed_cutover_at, now()),
    last_error = '',
    updated_at = now()
WHERE id = $1 AND state IN ('copying', 'synced')
`

// Record that the primary backend is now serving from the campaign's TARGET,
// i.e. the operator's env swap took effect. observed_cutover_at is written once
// and never moved: the grace period before the source is deleted is measured
// from the first observation, so a restart cannot silently restart the clock.
func (q *Queries) MarkStorageMigrationCutover(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markStorageMigrationCutover, id)
	return err
}

const markStorageMigrationObjectSourceDeleted = `-- name: MarkStorageMigrationObjectSourceDeleted :exec
UPDATE storage_migration_objects
SET state = 'source_deleted', updated_at = now()
WHERE object_key = $1 AND state = 'verified'
`

// The verified copy's SOURCE object has been removed. Guarded on 'verified' so
// nothing can record a source deletion for an object that was never proven to
// have arrived.
func (q *Queries) MarkStorageMigrationObjectSourceDeleted(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, markStorageMigrationObjectSourceDeleted, objectKey)
	return err
}

const markStorageMigrationObjectVerified = `-- name: MarkStorageMigrationObjectVerified :exec
UPDATE storage_migration_objects
SET state = 'verified', sha256 = $2, byte_size = $3, last_error = '', updated_at = now()
WHERE object_key = $1 AND state = 'copying'
`

type MarkStorageMigrationObjectVerifiedParams struct {
	ObjectKey string `json:"object_key"`
	Sha256    string `json:"sha256"`
	ByteSize  int64  `json:"byte_size"`
}

// The object is in the target AND was read back from it and re-hashed. This is
// the per-object location record flipping (interfaces.md section 3): from here
// on, dual-read and delete-source both treat the target as holding these bytes.
func (q *Queries) MarkStorageMigrationObjectVerified(ctx context.Context, arg MarkStorageMigrationObjectVerifiedParams) error {
	_, err := q.db.Exec(ctx, markStorageMigrationObjectVerified, arg.ObjectKey, arg.Sha256, arg.ByteSize)
	return err
}

const pauseStorageMigration = `-- name: PauseStorageMigration :execrows
UPDATE storage_migrations
SET state = 'paused', resume_state = state, paused_reason = $2, last_error = $3, updated_at = now()
WHERE id = $1 AND state IN ('enumerating', 'copying', 'synced')
`

type PauseStorageMigrationParams struct {
	ID           uuid.UUID `json:"id"`
	PausedReason string    `json:"paused_reason"`
	LastError    string    `json:"last_error"`
}

// Park a live campaign. resume_state remembers the phase it came out of, so a
// resume never has to guess: a campaign paused out of 'synced' is ready to cut
// over and one paused out of 'copying' is not.
//
// Only the PRE-cutover phases can be paused. Past cutover the api is already
// serving from the target and the only work left is deleting the old store's
// copies -- pausing that is what the grace window is for, and 'paused' there
// would mean "stop deleting", which STORAGE_MIGRATION_GRACE_HOURS already says
// better. The guard is also what makes pause idempotent: pausing a paused
// campaign matches nothing and reports zero rows.
func (q *Queries) PauseStorageMigration(ctx context.Context, arg PauseStorageMigrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, pauseStorageMigration, arg.ID, arg.PausedReason, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshStorageMigrationCounters = `-- name: RefreshStorageMigrationCounters :exec
UPDATE storage_migrations m
SET objects_total  = c.total,
    objects_done   = c.done,
    objects_failed = c.failed,
    updated_at     = now()
FROM (
    SELECT
        count(*)::bigint AS total,
        count(*) FILTER (WHERE state IN ('verified', 'source_deleted'))::bigint AS done,
        count(*) FILTER (WHERE state = 'failed')::bigint AS failed
    FROM storage_migration_objects
    WHERE campaign_id = $1
) c
WHERE m.id = $1
  AND (m.objects_total, m.objects_done, m.objects_failed)
      IS DISTINCT FROM (c.total, c.done, c.failed)
`

// Recompute the campaign counters FROM the object ledger. Derived rather than
// incremented on purpose: an optimistic counter drifts the moment a worker dies
// mid-batch, and this one feeds a progress percentage an operator makes a
// delete-the-source decision on. The IS DISTINCT FROM guard means a tick that
// found no change does not touch the row at all.
func (q *Queries) RefreshStorageMigrationCounters(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshStorageMigrationCounters, id)
	return err
}

const releaseStorageMigrationSource = `-- name: ReleaseStorageMigrationSource :execrows
UPDATE storage_migrations
SET state = 'deleting_source', last_error = '', updated_at = now()
WHERE id = $1 AND state = 'cutover'
`

// Open the delete-source phase NOW, without waiting out the grace window.
//
// The grace window is an undo window: while it runs, reverting the environment
// swap is a restart rather than a restore. Ending it early is therefore an
// operator decision and nothing else -- which is why it is a route and a
// confirmation rather than a timer an operator races. The precondition that
// CANNOT be waived is in the service: every object must be accounted for first.
func (q *Queries) ReleaseStorageMigrationSource(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseStorageMigrationSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewStorageMigrationObjectLease = `-- name: RenewStorageMigrationObjectLease :exec
UPDATE storage_migration_objects
SET next_attempt_at = now() + interval '30 minutes', updated_at = now()
WHERE object_key = $1 AND state = 'copying'
`

// Push a claimed object's lease forward while the copy is still streaming. A
// whole video original over a slow link can outlive one lease; without this the
// sweep would hand it to a second worker mid-copy. Guarded on 'copying' so a row
// that already finished cannot be revived.
//
// updated_at is bumped with the lease so a row that is being actively copied
// does not look untouched. This table has no operational-projection trigger of
// its own (only the campaign in storage_migrations does), so unlike
// RenewTranscodeJobLease the bump feeds no gauge — it keeps updated_at meaning
// what it says, which is what anyone eyeballing a stuck-looking campaign reads.
func (q *Queries) RenewStorageMigrationObjectLease(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, renewStorageMigrationObjectLease, objectKey)
	return err
}

const rescheduleStorageMigrationObject = `-- name: RescheduleStorageMigrationObject :exec
UPDATE storage_migration_objects
SET state = 'pending', attempts = attempts + 1, next_attempt_at = $2, last_error = $3, updated_at = now()
WHERE object_key = $1 AND state = 'copying'
`

type RescheduleStorageMigrationObjectParams struct {
	ObjectKey     string    `json:"object_key"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
}

// Transient failure: back to pending with backoff, one attempt spent.
func (q *Queries) RescheduleStorageMigrationObject(ctx context.Context, arg RescheduleStorageMigrationObjectParams) error {
	_, err := q.db.Exec(ctx, rescheduleStorageMigrationObject, arg.ObjectKey, arg.NextAttemptAt, arg.LastError)
	return err
}

const resumeStorageMigration = `-- name: ResumeStorageMigration :execrows
UPDATE storage_migrations
SET state = CASE WHEN resume_state <> '' THEN resume_state ELSE 'copying' END,
    resume_state = '', paused_reason = '', last_error = '', updated_at = now()
WHERE id = $1 AND state = 'paused'
`

// Put a paused campaign back in the phase it came out of. COALESCE-shaped
// fallback for a row written before 0145 or by hand: a campaign with work left
// in its ledger belongs in 'copying', and the next sweep re-derives the rest.
func (q *Queries) ResumeStorageMigration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resumeStorageMigration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStorageMigrationError = `-- name: SetStorageMigrationError :exec
UPDATE storage_migrations
SET last_error = $2, updated_at = now()
WHERE id = $1 AND state NOT IN ('done', 'cancelled', 'failed') AND last_error IS DISTINCT FROM $2
`

type SetStorageMigrationErrorParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

// Record a diagnostic WITHOUT changing state (the campaign is stuck, not over).
// The IS DISTINCT FROM guard keeps a repeating sweep from touching the row every
// tick, which would churn the job_runs projection for no new information.
func (q *Queries) SetStorageMigrationError(ctx context.Context, arg SetStorageMigrationErrorParams) error {
	_, err := q.db.Exec(ctx, setStorageMigrationError, arg.ID, arg.LastError)
	return err
}

const setStorageMigrationState = `-- name: SetStorageMigrationState :exec
UPDATE storage_migrations
SET state = $2, last_error = $3, updated_at = now()
WHERE id = $1 AND state NOT IN ('done', 'cancelled', 'failed')
`

type SetStorageMigrationStateParams struct {
	ID        uuid.UUID `json:"id"`
	State     string    `json:"state"`
	LastError string    `json:"last_error"`
}

// Advance a live campaign. Guarded on the terminal set so a cancel that lands
// between a sweep's read and its write is never overwritten.
func (q *Queries) SetStorageMigrationState(ctx context.Context, arg SetStorageMigrationStateParams) error {
	_, err := q.db.Exec(ctx, setStorageMigrationState, arg.ID, arg.State, arg.LastError)
	return err
}

const setStorageMigrationWorker = `-- name: SetStorageMigrationWorker :exec
UPDATE storage_migrations
SET worker_id = $2
WHERE id = $1 AND worker_id IS DISTINCT FROM $2
`

type SetStorageMigrationWorkerParams struct {
	ID       uuid.UUID `json:"id"`
	WorkerID string    `json:"worker_id"`
}

// Stamp the worker that is currently driving this campaign, so an operator
// reading the job run can tell WHICH process is copying. Written on every state
// advance a worker makes; the trigger only carries it onto the run if the run
// has none yet, so the first worker to touch a campaign is the one named.
func (q *Queries) SetStorageMigrationWorker(ctx context.Context, arg SetStorageMigrationWorkerParams) error {
	_, err := q.db.Exec(ctx, setStorageMigrationWorker, arg.ID, arg.WorkerID)
	return err
}

const storageMigrationRecentFailures = `-- name: StorageMigrationRecentFailures :many
SELECT campaign_id AS id, last_error AS error, attempts, updated_at
FROM storage_migration_objects
WHERE state = 'failed'
ORDER BY updated_at DESC, object_key
LIMIT $1
`

type StorageMigrationRecentFailuresRow struct {
	ID        uuid.UUID `json:"id"`
	Error     string    `json:"error"`
	Attempts  int32     `json:"attempts"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Dead-lettered objects for the merged failures list. It reports the CAMPAIGN id,
// never object_key: the overview contract forbids storage keys, and the campaign
// is the actionable handle anyway (the key is in the campaign's own detail view).
func (q *Queries) StorageMigrationRecentFailures(ctx context.Context, limit int32) ([]StorageMigrationRecentFailuresRow, error) {
	rows, err := q.db.Query(ctx, storageMigrationRecentFailures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageMigrationRecentFailuresRow
	for rows.Next() {
		var i StorageMigrationRecentFailuresRow
		if err := rows.Scan(
			&i.ID,
			&i.Error,
			&i.Attempts,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageMigrationStats = `-- name: StorageMigrationStats :one
SELECT
    count(*) FILTER (WHERE state = 'pending')::bigint AS pending,
    count(*) FILTER (WHERE state = 'copying')::bigint AS running,
    count(*) FILTER (WHERE state IN ('verified', 'source_deleted'))::bigint AS done,
    count(*) FILTER (WHERE state = 'failed')::bigint  AS failed,
    COALESCE(EXTRACT(EPOCH FROM (now() - min(created_at) FILTER (WHERE state = 'pending')))::bigint, 0)::bigint AS oldest_pending_age_seconds
FROM storage_migration_objects
`

type StorageMigrationStatsRow struct {
	Pending                 int64 `json:"pending"`
	Running                 int64 `json:"running"`
	Done                    int64 `json:"done"`
	Failed                  int64 `json:"failed"`
	OldestPendingAgeSeconds int64 `json:"oldest_pending_age_seconds"`
}

// Admin jobs overview card. The unit is the OBJECT, because that is the work:
// one campaign row would show a single job that is 'running' for a week.
func (q *Queries) StorageMigrationStats(ctx context.Context) (StorageMigrationStatsRow, error) {
	row := q.db.QueryRow(ctx, storageMigrationStats)
	var i StorageMigrationStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Running,
		&i.Done,
		&i.Failed,
		&i.OldestPendingAgeSeconds,
	)
	return i, err
}

const sweepExpiredStorageMigrationObjects = `-- name: SweepExpiredStorageMigrationObjects :execrows
UPDATE storage_migration_objects
SET state = 'pending', attempts = attempts + 1, updated_at = now()
WHERE object_key IN (
    SELECT object_key FROM storage_migration_objects
    WHERE state = 'copying' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT 1000
    FOR UPDATE SKIP LOCKED
)
`

// Return objects whose lease elapsed while they were 'copying' to the queue.
// attempts is incremented so an object that kills its worker every time walks
// its counter up and dead-letters through the normal path.
//
// Bounded FOR UPDATE SKIP LOCKED for the same reason the claim uses it: without
// it, concurrent sweepers take their row locks in table order and serialise on
// each other; with it they take disjoint rows. LIMIT bounds one tick's work
// (see SweepExpiredTranscodeJobs for the full rationale). This is the queue
// where it matters most: a campaign enumerates a whole library at once, so this
// table is the one that actually gets big.
func (q *Queries) SweepExpiredStorageMigrationObjects(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredStorageMigrationObjects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStorageMigrationObjects = `-- name: UpsertStorageMigrationObjects :execrows
INSERT INTO storage_migration_objects (object_key, campaign_id)
SELECT k, $1
FROM unnest($2::text[]) AS k
ON CONFLICT (object_key) DO NOTHING
`

type UpsertStorageMigrationObjectsParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	ObjectKeys []string  `json:"object_keys"`
}

// Record a batch of enumerated keys. DO NOTHING on conflict is what makes the
// delta pass cheap and idempotent: a re-enumeration re-offers every key it saw
// last time and only genuinely new objects become rows, so the rowcount IS the
// answer to "did anything appear since?".
func (q *Queries) UpsertStorageMigrationObjects(ctx context.Context, arg UpsertStorageMigrationObjectsParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertStorageMigrationObjects, arg.CampaignID, arg.ObjectKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
