// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveUploadSessionsForUser = `-- name: CountActiveUploadSessionsForUser :one
SELECT count(*)::bigint FROM upload_sessions
WHERE user_id = $1
  AND state = 'active'
  AND expires_at > now()
`

// The number of the caller's ACTIVE (not completed/cancelled, not yet expired)
// upload sessions — the batch-upload guard input (UPLOAD-10, W2.C3).
// createUploadSession refuses to open a new session once this reaches
// UPLOAD_MAX_ACTIVE_SESSIONS_PER_USER, so a client's batch orchestration queues
// rather than opening unbounded concurrent sessions. A cancel or complete frees
// a slot; the 24h-expiry sweeper is the backstop for abandoned ones.
func (q *Queries) CountActiveUploadSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUploadSessionsForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUploadSession = `-- name: CreateUploadSession :one

INSERT INTO upload_sessions (video_id, user_id, filename, total_size, chunk_size, expires_at, file_fingerprint, purpose)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, video_id, user_id, filename, total_size, chunk_size, state, expires_at, created_at, updated_at, file_fingerprint, purpose, failure_reason
`

type CreateUploadSessionParams struct {
	VideoID         uuid.UUID `json:"video_id"`
	UserID          uuid.UUID `json:"user_id"`
	Filename        string    `json:"filename"`
	TotalSize       int64     `json:"total_size"`
	ChunkSize       int32     `json:"chunk_size"`
	ExpiresAt       time.Time `json:"expires_at"`
	FileFingerprint string    `json:"file_fingerprint"`
	Purpose         string    `json:"purpose"`
}

// Resumable upload sessions + received-chunk ledger (migration 0059, fix_plan
// P6.1). The chunk bytes live in the blob backend at uploads/<session>/<n>;
// these rows are the resume contract + sweeper input.
func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, createUploadSession,
		arg.VideoID,
		arg.UserID,
		arg.Filename,
		arg.TotalSize,
		arg.ChunkSize,
		arg.ExpiresAt,
		arg.FileFingerprint,
		arg.Purpose,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Filename,
		&i.TotalSize,
		&i.ChunkSize,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileFingerprint,
		&i.Purpose,
		&i.FailureReason,
	)
	return i, err
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM upload_sessions WHERE id = $1
`

// Cascades to upload_chunks. The caller removes the chunk blobs first.
func (q *Queries) DeleteUploadSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUploadSession, id)
	return err
}

const failUploadSession = `-- name: FailUploadSession :exec
UPDATE upload_sessions
SET state = 'failed', failure_reason = $2, updated_at = now()
WHERE id = $1
`

type FailUploadSessionParams struct {
	ID            uuid.UUID `json:"id"`
	FailureReason string    `json:"failure_reason"`
}

// Terminal failure of the asynchronous completion (migration 0120): the finalize
// job dead-lettered. reason is a SAFE, client-visible sentence — the poller on
// GET /api/v1/uploads/{upload_id} reads it verbatim, so it must never carry an
// internal error, a storage key, or process output.
func (q *Queries) FailUploadSession(ctx context.Context, arg FailUploadSessionParams) error {
	_, err := q.db.Exec(ctx, failUploadSession, arg.ID, arg.FailureReason)
	return err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, video_id, user_id, filename, total_size, chunk_size, state, expires_at, created_at, updated_at, file_fingerprint, purpose, failure_reason FROM upload_sessions WHERE id = $1
`

func (q *Queries) GetUploadSession(ctx context.Context, id uuid.UUID) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSession, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Filename,
		&i.TotalSize,
		&i.ChunkSize,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileFingerprint,
		&i.Purpose,
		&i.FailureReason,
	)
	return i, err
}

const hasActiveReplaceSessionForVideo = `-- name: HasActiveReplaceSessionForVideo :one
SELECT EXISTS (
    SELECT 1 FROM upload_sessions
    WHERE video_id = $1
      AND purpose = 'replace'
      AND state IN ('active', 'queued', 'processing')
      AND expires_at > now()
)
`

// Whether a replace-purpose session is already open for the video (config-
// parity W14): at most one replacement may be in flight per video, so the
// replace-session create answers 409 replace_conflict while one exists.
//
// 'queued'/'processing' count as in flight (migration 0120): completion is now
// asynchronous, so between the accepted POST and the worker's swap there is a
// window in which the session is no longer 'active' but the replacement has
// very much not finished. Admitting a second one there would race two
// ReplaceSource runs onto the same video.
func (q *Queries) HasActiveReplaceSessionForVideo(ctx context.Context, videoID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveReplaceSessionForVideo, videoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveUploadSessionsForUser = `-- name: ListActiveUploadSessionsForUser :many
SELECT s.id, s.video_id, s.filename, s.total_size, s.chunk_size,
       s.file_fingerprint, s.expires_at,
       (SELECT count(*) FROM upload_chunks c WHERE c.upload_id = s.id)::bigint AS received_chunks
FROM upload_sessions s
WHERE s.user_id = $1
  AND s.state = 'active'
  AND s.expires_at > now()
  AND ($2::text IS NULL OR s.file_fingerprint = $2::text)
ORDER BY s.created_at DESC
`

type ListActiveUploadSessionsForUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Fingerprint *string   `json:"fingerprint"`
}

type ListActiveUploadSessionsForUserRow struct {
	ID              uuid.UUID `json:"id"`
	VideoID         uuid.UUID `json:"video_id"`
	Filename        string    `json:"filename"`
	TotalSize       int64     `json:"total_size"`
	ChunkSize       int32     `json:"chunk_size"`
	FileFingerprint string    `json:"file_fingerprint"`
	ExpiresAt       time.Time `json:"expires_at"`
	ReceivedChunks  int64     `json:"received_chunks"`
}

// The caller's ACTIVE (not completed/cancelled, not yet expired) upload sessions
// with the number of chunks received so far — the cross-refresh / cross-device
// resume contract (UPLOAD-03, GET /api/v1/me/uploads). When @fingerprint is
// supplied the list narrows to sessions with that file_fingerprint (the partial
// index from migration 0080 serves this lookup), so a client can ask "am I
// already uploading this exact file?". localStorage becomes a cache, not the
// source of truth.
func (q *Queries) ListActiveUploadSessionsForUser(ctx context.Context, arg ListActiveUploadSessionsForUserParams) ([]ListActiveUploadSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveUploadSessionsForUser, arg.UserID, arg.Fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUploadSessionsForUserRow
	for rows.Next() {
		var i ListActiveUploadSessionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Filename,
			&i.TotalSize,
			&i.ChunkSize,
			&i.FileFingerprint,
			&i.ExpiresAt,
			&i.ReceivedChunks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepableUploadSessions = `-- name: ListSweepableUploadSessions :many
SELECT s.id FROM upload_sessions s
WHERE (s.state = 'cancelled' OR s.expires_at <= now())
  AND NOT EXISTS (
      SELECT 1 FROM upload_finalize_jobs j
      WHERE j.upload_id = s.id AND j.state IN ('pending', 'running')
  )
ORDER BY s.expires_at
LIMIT $1
`

// Cancelled sessions and any session past its 24h expiry, for the cleanup
// sweeper (which deletes the chunk blobs then the row).
//
// A session with a LIVE finalize job (migration 0120) is never swept, however
// long it has been open: its chunk blobs are the worker's input, and deleting
// them mid-assembly would fail a completion the client has already been told was
// accepted. Once the job reaches done/failed the ordinary rules apply again —
// and the lease sweep guarantees a job stranded by a dead worker reaches one of
// those states rather than pinning the row forever.
func (q *Queries) ListSweepableUploadSessions(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSweepableUploadSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadChunks = `-- name: ListUploadChunks :many
SELECT n, size_bytes FROM upload_chunks WHERE upload_id = $1 ORDER BY n
`

type ListUploadChunksRow struct {
	N         int32 `json:"n"`
	SizeBytes int64 `json:"size_bytes"`
}

// The received-chunk ledger for a session, ascending by index (the resume /
// progress contract).
func (q *Queries) ListUploadChunks(ctx context.Context, uploadID uuid.UUID) ([]ListUploadChunksRow, error) {
	rows, err := q.db.Query(ctx, listUploadChunks, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUploadChunksRow
	for rows.Next() {
		var i ListUploadChunksRow
		if err := rows.Scan(&i.N, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadSessionQueued = `-- name: MarkUploadSessionQueued :execrows
UPDATE upload_sessions
SET state = 'queued', failure_reason = '', updated_at = now()
WHERE id = $1 AND state = 'active'
`

// Accept a completion: active → queued (migration 0120).
//
// The state guard is the whole point, and it is a CAS rather than a plain
// UPDATE. Completion validates the session, then enqueues a finalize job, and a
// DELETE /uploads/{id} can land in between: Cancel flips the row to 'cancelled'
// and deletes the chunk BLOBS, but leaves the upload_chunks ledger intact — so
// an unguarded write would flip the row back to 'queued', silently undoing the
// user's cancel and handing the worker a job whose bytes are gone (five attempts
// and ~15 minutes of backoff before it dead-letters).
//
// Zero rows therefore means "the session stopped being active underneath us",
// and the caller drops the job it just enqueued and answers 409.
func (q *Queries) MarkUploadSessionQueued(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadSessionQueued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUploadSessionState = `-- name: SetUploadSessionState :exec
UPDATE upload_sessions
SET state = $2, failure_reason = '', updated_at = now()
WHERE id = $1
`

type SetUploadSessionStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

// Advances the session's lifecycle state, clearing any stale failure reason: a
// session that moves on from 'failed' (only via a re-queued finalize job) must
// not keep answering the poll with the reason it failed last time.
func (q *Queries) SetUploadSessionState(ctx context.Context, arg SetUploadSessionStateParams) error {
	_, err := q.db.Exec(ctx, setUploadSessionState, arg.ID, arg.State)
	return err
}

const upsertUploadChunk = `-- name: UpsertUploadChunk :exec
INSERT INTO upload_chunks (upload_id, n, size_bytes)
VALUES ($1, $2, $3)
ON CONFLICT (upload_id, n) DO UPDATE
SET size_bytes = EXCLUDED.size_bytes, updated_at = now()
`

type UpsertUploadChunkParams struct {
	UploadID  uuid.UUID `json:"upload_id"`
	N         int32     `json:"n"`
	SizeBytes int64     `json:"size_bytes"`
}

// Idempotent re-PUT: a chunk index that has already landed just updates its
// recorded size (the blob at uploads/<session>/<n> is overwritten in place).
func (q *Queries) UpsertUploadChunk(ctx context.Context, arg UpsertUploadChunkParams) error {
	_, err := q.db.Exec(ctx, upsertUploadChunk, arg.UploadID, arg.N, arg.SizeBytes)
	return err
}
