// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_rejections.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVideoRejectionNote = `-- name: GetVideoRejectionNote :one
SELECT COALESCE((SELECT note FROM video_rejections WHERE video_id = $1), '')::text AS note
`

// The stored rejection note for one video, or ” when it was never rejected.
func (q *Queries) GetVideoRejectionNote(ctx context.Context, videoID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getVideoRejectionNote, videoID)
	var note string
	err := row.Scan(&note)
	return note, err
}

const recordVideoRejection = `-- name: RecordVideoRejection :exec
INSERT INTO video_rejections (video_id, note, rejected_by)
VALUES ($1, $2, $3)
ON CONFLICT (video_id) DO UPDATE
    SET note = EXCLUDED.note, rejected_by = EXCLUDED.rejected_by, created_at = now()
`

type RecordVideoRejectionParams struct {
	VideoID    uuid.UUID   `json:"video_id"`
	Note       string      `json:"note"`
	RejectedBy pgtype.UUID `json:"rejected_by"`
}

// Store the moderator's rejection note for a video (migration 0130). Idempotent
// on the video: a second rejection would replace the note and the acting
// moderator, matching BlockVideo's re-block semantics. The note may be empty —
// the row still records who rejected the upload and when.
func (q *Queries) RecordVideoRejection(ctx context.Context, arg RecordVideoRejectionParams) error {
	_, err := q.db.Exec(ctx, recordVideoRejection, arg.VideoID, arg.Note, arg.RejectedBy)
	return err
}
