// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (channel_id, title, description, privacy)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, title, description, privacy, state, created_at, updated_at
`

type CreateVideoParams struct {
	ChannelID   uuid.UUID `json:"channel_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Privacy     string    `json:"privacy"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.Privacy,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Privacy,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT v.id, v.channel_id, v.title, v.description, v.privacy, v.state, v.created_at, v.updated_at,
       c.owner_id
FROM videos v
JOIN channels c ON c.id = v.channel_id
WHERE v.id = $1
`

type GetVideoByIDRow struct {
	ID          uuid.UUID `json:"id"`
	ChannelID   uuid.UUID `json:"channel_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Privacy     string    `json:"privacy"`
	State       string    `json:"state"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	OwnerID     uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (GetVideoByIDRow, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i GetVideoByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Privacy,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listVideosByChannel = `-- name: ListVideosByChannel :many
SELECT id, channel_id, title, description, privacy, state, created_at, updated_at
FROM videos
WHERE channel_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVideosByChannel(ctx context.Context, channelID uuid.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Privacy,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
