// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_metadata.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getVideoMetadata = `-- name: GetVideoMetadata :one
SELECT video_id, duration_seconds, width, height, updated_at
FROM video_metadata
WHERE video_id = $1
`

func (q *Queries) GetVideoMetadata(ctx context.Context, videoID uuid.UUID) (VideoMetadatum, error) {
	row := q.db.QueryRow(ctx, getVideoMetadata, videoID)
	var i VideoMetadatum
	err := row.Scan(
		&i.VideoID,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVideoMetadata = `-- name: UpsertVideoMetadata :one
INSERT INTO video_metadata (video_id, duration_seconds, width, height, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (video_id) DO UPDATE
SET duration_seconds = EXCLUDED.duration_seconds,
    width            = EXCLUDED.width,
    height           = EXCLUDED.height,
    updated_at       = now()
RETURNING video_id, duration_seconds, width, height, updated_at
`

type UpsertVideoMetadataParams struct {
	VideoID         uuid.UUID `json:"video_id"`
	DurationSeconds *int32    `json:"duration_seconds"`
	Width           *int32    `json:"width"`
	Height          *int32    `json:"height"`
}

func (q *Queries) UpsertVideoMetadata(ctx context.Context, arg UpsertVideoMetadataParams) (VideoMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertVideoMetadata,
		arg.VideoID,
		arg.DurationSeconds,
		arg.Width,
		arg.Height,
	)
	var i VideoMetadatum
	err := row.Scan(
		&i.VideoID,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.UpdatedAt,
	)
	return i, err
}
