// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_tags.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteVideoTags = `-- name: DeleteVideoTags :exec
DELETE FROM video_tags WHERE video_id = $1
`

// Clears a video's tags (the first half of a replace; tags are always written
// as a full set).
func (q *Queries) DeleteVideoTags(ctx context.Context, videoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVideoTags, videoID)
	return err
}

const insertVideoTags = `-- name: InsertVideoTags :exec
INSERT INTO video_tags (video_id, tag)
SELECT $1, unnest($2::text[])
ON CONFLICT DO NOTHING
`

type InsertVideoTagsParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Tags    []string  `json:"tags"`
}

// Inserts a set of (already normalized: lowercased, trimmed, deduped) tags for
// a video. ON CONFLICT keeps the write idempotent should a duplicate slip in.
func (q *Queries) InsertVideoTags(ctx context.Context, arg InsertVideoTagsParams) error {
	_, err := q.db.Exec(ctx, insertVideoTags, arg.VideoID, arg.Tags)
	return err
}

const listVideoTags = `-- name: ListVideoTags :many
SELECT tag FROM video_tags WHERE video_id = $1 ORDER BY tag
`

func (q *Queries) ListVideoTags(ctx context.Context, videoID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listVideoTags, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
