// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_ratings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countVideoRatings = `-- name: CountVideoRatings :one
SELECT
    COUNT(*) FILTER (WHERE rating = 'like')    AS likes,
    COUNT(*) FILTER (WHERE rating = 'dislike') AS dislikes
FROM video_ratings
WHERE video_id = $1
`

type CountVideoRatingsRow struct {
	Likes    int64 `json:"likes"`
	Dislikes int64 `json:"dislikes"`
}

func (q *Queries) CountVideoRatings(ctx context.Context, videoID uuid.UUID) (CountVideoRatingsRow, error) {
	row := q.db.QueryRow(ctx, countVideoRatings, videoID)
	var i CountVideoRatingsRow
	err := row.Scan(&i.Likes, &i.Dislikes)
	return i, err
}

const deleteVideoRating = `-- name: DeleteVideoRating :exec
DELETE FROM video_ratings
WHERE user_id = $1 AND video_id = $2
`

type DeleteVideoRatingParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

func (q *Queries) DeleteVideoRating(ctx context.Context, arg DeleteVideoRatingParams) error {
	_, err := q.db.Exec(ctx, deleteVideoRating, arg.UserID, arg.VideoID)
	return err
}

const getVideoRating = `-- name: GetVideoRating :one
SELECT rating
FROM video_ratings
WHERE user_id = $1 AND video_id = $2
`

type GetVideoRatingParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

func (q *Queries) GetVideoRating(ctx context.Context, arg GetVideoRatingParams) (string, error) {
	row := q.db.QueryRow(ctx, getVideoRating, arg.UserID, arg.VideoID)
	var rating string
	err := row.Scan(&rating)
	return rating, err
}

const upsertVideoRating = `-- name: UpsertVideoRating :exec
INSERT INTO video_ratings (video_id, user_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, video_id)
DO UPDATE SET rating = EXCLUDED.rating, updated_at = now()
`

type UpsertVideoRatingParams struct {
	VideoID uuid.UUID `json:"video_id"`
	UserID  uuid.UUID `json:"user_id"`
	Rating  string    `json:"rating"`
}

// Set or change a user's rating for a video.
func (q *Queries) UpsertVideoRating(ctx context.Context, arg UpsertVideoRatingParams) error {
	_, err := q.db.Exec(ctx, upsertVideoRating, arg.VideoID, arg.UserID, arg.Rating)
	return err
}
