// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_blocks.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockVideo = `-- name: BlockVideo :execrows
INSERT INTO video_blocks (video_id, reason, blocked_by)
VALUES ($1, $2, $3)
ON CONFLICT (video_id) DO UPDATE
    SET reason = EXCLUDED.reason, blocked_by = EXCLUDED.blocked_by, created_at = now()
`

type BlockVideoParams struct {
	VideoID   uuid.UUID   `json:"video_id"`
	Reason    string      `json:"reason"`
	BlockedBy pgtype.UUID `json:"blocked_by"`
}

// Block a video (idempotent: re-blocking updates the reason + acting moderator).
// A non-existent video raises a foreign-key violation (SQLSTATE 23503), which the
// service maps to "video not found".
func (q *Queries) BlockVideo(ctx context.Context, arg BlockVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, blockVideo, arg.VideoID, arg.Reason, arg.BlockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isVideoBlocked = `-- name: IsVideoBlocked :one
SELECT EXISTS (SELECT 1 FROM video_blocks WHERE video_id = $1) AS blocked
`

// Whether a video is currently blocked.
func (q *Queries) IsVideoBlocked(ctx context.Context, videoID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isVideoBlocked, videoID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listBlockedVideos = `-- name: ListBlockedVideos :many
SELECT
    b.video_id,
    v.title,
    v.privacy,
    v.state,
    c.handle       AS channel_handle,
    c.display_name AS channel_display_name,
    b.reason,
    u.username     AS blocked_by_username,
    b.created_at   AS blocked_at
FROM video_blocks b
JOIN videos v   ON v.id = b.video_id
JOIN channels c ON c.id = v.channel_id
LEFT JOIN users u ON u.id = b.blocked_by
ORDER BY b.created_at DESC, b.video_id
LIMIT $2 OFFSET $1
`

type ListBlockedVideosParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type ListBlockedVideosRow struct {
	VideoID            uuid.UUID `json:"video_id"`
	Title              string    `json:"title"`
	Privacy            string    `json:"privacy"`
	State              string    `json:"state"`
	ChannelHandle      string    `json:"channel_handle"`
	ChannelDisplayName string    `json:"channel_display_name"`
	Reason             string    `json:"reason"`
	BlockedByUsername  *string   `json:"blocked_by_username"`
	BlockedAt          time.Time `json:"blocked_at"`
}

// Currently-blocked videos for the moderation block-list: newest block first,
// with the video title + current privacy/state, the owning channel, the block
// reason, who blocked it (NULL if that moderator's account was deleted), and when.
func (q *Queries) ListBlockedVideos(ctx context.Context, arg ListBlockedVideosParams) ([]ListBlockedVideosRow, error) {
	rows, err := q.db.Query(ctx, listBlockedVideos, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedVideosRow
	for rows.Next() {
		var i ListBlockedVideosRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Privacy,
			&i.State,
			&i.ChannelHandle,
			&i.ChannelDisplayName,
			&i.Reason,
			&i.BlockedByUsername,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockVideo = `-- name: UnblockVideo :execrows
DELETE FROM video_blocks WHERE video_id = $1
`

// Unblock a video (idempotent). Returns rows deleted (0 = it was not blocked).
func (q *Queries) UnblockVideo(ctx context.Context, videoID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unblockVideo, videoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
