package caption

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"athena/internal/config"
	"athena/internal/domain"
	"athena/internal/port"
	"athena/internal/storage"

	"github.com/google/uuid"
)

// Service handles business logic for video captions
type Service struct {
	captionRepo port.CaptionRepository
	videoRepo   port.VideoRepository
	paths       storage.Paths
	cfg         *config.Config
}

// NewService creates a new caption service
func NewService(
	captionRepo port.CaptionRepository,
	videoRepo port.VideoRepository,
	cfg *config.Config,
) *Service {
	return &Service{
		captionRepo: captionRepo,
		videoRepo:   videoRepo,
		paths:       storage.NewPaths(cfg.StorageDir),
		cfg:         cfg,
	}
}

// CreateCaption creates a new caption for a video
func (s *Service) CreateCaption(ctx context.Context, videoID uuid.UUID, req *domain.CreateCaptionRequest, file io.Reader) (*domain.Caption, error) {
	// Verify video exists
	video, err := s.videoRepo.GetByID(ctx, videoID.String())
	if err != nil {
		if err == domain.ErrNotFound {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("failed to verify video: %w", err)
	}

	// Validate format
	if !req.FileFormat.IsValid() {
		return nil, domain.NewDomainError("INVALID_FORMAT", "Invalid caption format")
	}

	// Validate language code (basic check)
	if len(req.LanguageCode) < 2 || len(req.LanguageCode) > 10 {
		return nil, domain.NewDomainError("INVALID_LANGUAGE", "Invalid language code")
	}

	// Create caption directory for the video
	captionDir := s.paths.VideoCaptionsDir(videoID.String())
	if err := os.MkdirAll(captionDir, 0750); err != nil {
		return nil, fmt.Errorf("failed to create caption directory: %w", err)
	}

	// Generate file path
	fileName := fmt.Sprintf("%s.%s", req.LanguageCode, req.FileFormat)
	filePath := filepath.Join(captionDir, fileName)

	// Save caption file
	fileSize, err := s.saveCaption(file, filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to save caption file: %w", err)
	}

	// Create caption record
	caption := &domain.Caption{
		ID:              uuid.New(),
		VideoID:         videoID,
		LanguageCode:    req.LanguageCode,
		Label:           req.Label,
		FilePath:        &filePath,
		FileFormat:      req.FileFormat,
		FileSizeBytes:   &fileSize,
		IsAutoGenerated: req.IsAutoGenerated,
	}

	if err := s.captionRepo.Create(ctx, caption); err != nil {
		// Cleanup file on DB error
		_ = os.Remove(filePath)
		return nil, fmt.Errorf("failed to create caption record: %w", err)
	}

	// Generate public URL for the caption
	caption.URL = s.generateCaptionURL(video, caption)

	return caption, nil
}

// GetCaptionByID gets a caption by ID
func (s *Service) GetCaptionByID(ctx context.Context, captionID uuid.UUID) (*domain.Caption, error) {
	caption, err := s.captionRepo.GetByID(ctx, captionID)
	if err != nil {
		return nil, err
	}

	// Get video for URL generation
	video, err := s.videoRepo.GetByID(ctx, caption.VideoID.String())
	if err == nil {
		caption.URL = s.generateCaptionURL(video, caption)
	}

	return caption, nil
}

// GetCaptionsByVideoID gets all captions for a video
func (s *Service) GetCaptionsByVideoID(ctx context.Context, videoID uuid.UUID) (*domain.CaptionListResponse, error) {
	// Verify video exists
	video, err := s.videoRepo.GetByID(ctx, videoID.String())
	if err != nil {
		if err == domain.ErrNotFound {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("failed to verify video: %w", err)
	}

	captions, err := s.captionRepo.GetByVideoID(ctx, videoID)
	if err != nil {
		return nil, fmt.Errorf("failed to get captions: %w", err)
	}

	// Generate URLs for all captions
	for i := range captions {
		captions[i].URL = s.generateCaptionURL(video, &captions[i])
	}

	return &domain.CaptionListResponse{
		Captions: captions,
		Count:    len(captions),
	}, nil
}

// UpdateCaption updates a caption (mainly label and language code)
func (s *Service) UpdateCaption(ctx context.Context, captionID uuid.UUID, req *domain.UpdateCaptionRequest) (*domain.Caption, error) {
	// Get existing caption
	caption, err := s.captionRepo.GetByID(ctx, captionID)
	if err != nil {
		return nil, err
	}

	// Update fields if provided
	if req.Label != nil && *req.Label != "" {
		caption.Label = *req.Label
	}

	if req.LanguageCode != nil && *req.LanguageCode != "" {
		// Check if language code is changing and if it conflicts
		if caption.LanguageCode != *req.LanguageCode {
			// Check for existing caption with same language
			existing, err := s.captionRepo.GetByVideoAndLanguage(ctx, caption.VideoID, *req.LanguageCode)
			if err == nil && existing != nil && existing.ID != captionID {
				return nil, domain.NewDomainError("LANGUAGE_EXISTS", "Caption with this language already exists for the video")
			}

			// Update file path if language changes
			if caption.FilePath != nil {
				oldPath := *caption.FilePath
				dir := filepath.Dir(oldPath)
				newFileName := fmt.Sprintf("%s.%s", *req.LanguageCode, caption.FileFormat)
				newPath := filepath.Join(dir, newFileName)

				// Rename file
				if err := os.Rename(oldPath, newPath); err != nil {
					return nil, fmt.Errorf("failed to rename caption file: %w", err)
				}
				caption.FilePath = &newPath
			}

			caption.LanguageCode = *req.LanguageCode
		}
	}

	if err := s.captionRepo.Update(ctx, caption); err != nil {
		return nil, fmt.Errorf("failed to update caption: %w", err)
	}

	// Get video for URL generation
	video, err := s.videoRepo.GetByID(ctx, caption.VideoID.String())
	if err == nil {
		caption.URL = s.generateCaptionURL(video, caption)
	}

	return caption, nil
}

// DeleteCaption deletes a caption
func (s *Service) DeleteCaption(ctx context.Context, captionID uuid.UUID) error {
	// Get caption to find file path
	caption, err := s.captionRepo.GetByID(ctx, captionID)
	if err != nil {
		return err
	}

	// Delete from database
	if err := s.captionRepo.Delete(ctx, captionID); err != nil {
		return fmt.Errorf("failed to delete caption: %w", err)
	}

	// Delete file if it exists
	if caption.FilePath != nil {
		_ = os.Remove(*caption.FilePath) // Ignore error if file doesn't exist
	}

	return nil
}

// GetCaptionContent reads the content of a caption file
func (s *Service) GetCaptionContent(ctx context.Context, captionID uuid.UUID) (io.ReadCloser, string, error) {
	caption, err := s.captionRepo.GetByID(ctx, captionID)
	if err != nil {
		return nil, "", err
	}

	if caption.FilePath == nil || *caption.FilePath == "" {
		return nil, "", domain.NewDomainError("NO_FILE", "Caption file not found")
	}

	file, err := os.Open(*caption.FilePath)
	if err != nil {
		return nil, "", fmt.Errorf("failed to open caption file: %w", err)
	}

	return file, caption.FileFormat.GetContentType(), nil
}

// saveCaption saves caption content to a file
func (s *Service) saveCaption(reader io.Reader, filePath string) (int64, error) {
	// Create or truncate file
	file, err := os.Create(filePath) // #nosec G304: filePath is constructed within storage dir
	if err != nil {
		return 0, fmt.Errorf("failed to create caption file: %w", err)
	}
	defer func() { _ = file.Close() }()

	// Copy content and count bytes
	written, err := io.Copy(file, reader)
	if err != nil {
		_ = os.Remove(filePath) // Clean up on error
		return 0, fmt.Errorf("failed to write caption file: %w", err)
	}

	// Validate caption file (basic check for non-empty)
	if written == 0 {
		_ = os.Remove(filePath)
		return 0, domain.NewDomainError("EMPTY_FILE", "Caption file is empty")
	}

	if err := s.validateCaptionFormat(filePath); err != nil {
		_ = os.Remove(filePath)
		return 0, err
	}

	return written, nil
}

// validateCaptionFormat performs basic validation of caption format
func (s *Service) validateCaptionFormat(filePath string) error {
	file, err := os.Open(filePath) // #nosec G304: filePath is constructed within storage dir
	if err != nil {
		return fmt.Errorf("failed to open file for validation: %w", err)
	}
	defer func() { _ = file.Close() }()

	// Read first few bytes to check format
	header := make([]byte, 100)
	n, err := file.Read(header)
	if err != nil && err != io.EOF {
		return fmt.Errorf("failed to read file header: %w", err)
	}

	if n == 0 {
		return domain.NewDomainError("EMPTY_FILE", "Caption file is empty")
	}

	headerStr := string(header[:n])
	ext := strings.ToLower(filepath.Ext(filePath))

	// Check for VTT format
	if ext == ".vtt" {
		if !strings.HasPrefix(headerStr, "WEBVTT") {
			return domain.NewDomainError("INVALID_VTT", "Invalid WebVTT file format")
		}
	}

	// SRT files don't have a specific header, but usually start with timing
	// We'll just ensure it's not obviously wrong (like binary data)
	if ext == ".srt" {
		// Check for common SRT patterns (number followed by timing)
		if strings.Contains(headerStr, "\x00") {
			return domain.NewDomainError("INVALID_SRT", "Invalid SubRip file format")
		}
	}

	return nil
}

// generateCaptionURL generates a public URL for accessing a caption
func (s *Service) generateCaptionURL(video *domain.Video, caption *domain.Caption) string {
	// If we have IPFS CID, prefer that (when IPFS is implemented)
	// For now, always use direct HTTP endpoint

	// Otherwise, use direct HTTP endpoint
	return fmt.Sprintf("/api/v1/videos/%s/captions/%s/content", video.ID, caption.ID.String())
}
