package repository

import (
	"context"
	"database/sql"
	"fmt"
	"time"
	"vidra-core/internal/domain"
	"vidra-core/internal/usecase"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"
)

type captionRepository struct {
	db *sqlx.DB
}

func NewCaptionRepository(db *sqlx.DB) usecase.CaptionRepository {
	return &captionRepository{db: db}
}

// Create creates a new caption record
func (r *captionRepository) Create(ctx context.Context, caption *domain.Caption) error {
	query := `
		INSERT INTO captions (
			id, video_id, language_code, label, file_path, ipfs_cid,
			file_format, file_size_bytes, is_auto_generated, created_at, updated_at
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
		ON CONFLICT (video_id, language_code)
		DO UPDATE SET
			label = EXCLUDED.label,
			file_path = EXCLUDED.file_path,
			ipfs_cid = EXCLUDED.ipfs_cid,
			file_format = EXCLUDED.file_format,
			file_size_bytes = EXCLUDED.file_size_bytes,
			is_auto_generated = EXCLUDED.is_auto_generated,
			updated_at = EXCLUDED.updated_at
		RETURNING id`

	if caption.ID == uuid.Nil {
		caption.ID = uuid.New()
	}

	now := time.Now()
	caption.CreatedAt = now
	caption.UpdatedAt = now

	err := r.db.QueryRowContext(
		ctx, query,
		caption.ID, caption.VideoID, caption.LanguageCode, caption.Label,
		caption.FilePath, caption.IPFSCID, caption.FileFormat, caption.FileSizeBytes,
		caption.IsAutoGenerated, caption.CreatedAt,
	).Scan(&caption.ID)

	if err != nil {
		return fmt.Errorf("failed to create caption: %w", err)
	}

	return nil
}

// GetByID retrieves a caption by ID
func (r *captionRepository) GetByID(ctx context.Context, captionID uuid.UUID) (*domain.Caption, error) {
	var caption domain.Caption
	query := `
		SELECT id, video_id, language_code, label, file_path, ipfs_cid,
			   file_format, file_size_bytes, is_auto_generated, created_at, updated_at
		FROM captions
		WHERE id = $1`

	err := r.db.GetContext(ctx, &caption, query, captionID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("failed to get caption: %w", err)
	}

	return &caption, nil
}

// GetByVideoAndLanguage retrieves a caption by video ID and language code
func (r *captionRepository) GetByVideoAndLanguage(ctx context.Context, videoID uuid.UUID, languageCode string) (*domain.Caption, error) {
	var caption domain.Caption
	query := `
		SELECT id, video_id, language_code, label, file_path, ipfs_cid,
			   file_format, file_size_bytes, is_auto_generated, created_at, updated_at
		FROM captions
		WHERE video_id = $1 AND language_code = $2`

	err := r.db.GetContext(ctx, &caption, query, videoID, languageCode)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("failed to get caption: %w", err)
	}

	return &caption, nil
}

// GetByVideoID retrieves all captions for a video
func (r *captionRepository) GetByVideoID(ctx context.Context, videoID uuid.UUID) ([]domain.Caption, error) {
	var captions []domain.Caption
	query := `
		SELECT id, video_id, language_code, label, file_path, ipfs_cid,
			   file_format, file_size_bytes, is_auto_generated, created_at, updated_at
		FROM captions
		WHERE video_id = $1
		ORDER BY language_code`

	err := r.db.SelectContext(ctx, &captions, query, videoID)
	if err != nil {
		return nil, fmt.Errorf("failed to get captions: %w", err)
	}

	if captions == nil {
		captions = []domain.Caption{}
	}

	return captions, nil
}

// Update updates a caption record
func (r *captionRepository) Update(ctx context.Context, caption *domain.Caption) error {
	query := `
		UPDATE captions
		SET label = $1, file_path = $2, ipfs_cid = $3, file_format = $4,
			file_size_bytes = $5, is_auto_generated = $6, updated_at = $7,
			language_code = $8
		WHERE id = $9`

	caption.UpdatedAt = time.Now()

	result, err := r.db.ExecContext(
		ctx, query,
		caption.Label, caption.FilePath, caption.IPFSCID, caption.FileFormat,
		caption.FileSizeBytes, caption.IsAutoGenerated, caption.UpdatedAt,
		caption.LanguageCode, caption.ID,
	)

	if err != nil {
		return fmt.Errorf("failed to update caption: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to get rows affected: %w", err)
	}

	if rowsAffected == 0 {
		return domain.ErrNotFound
	}

	return nil
}

// Delete deletes a caption by ID
func (r *captionRepository) Delete(ctx context.Context, captionID uuid.UUID) error {
	query := `DELETE FROM captions WHERE id = $1`

	result, err := r.db.ExecContext(ctx, query, captionID)
	if err != nil {
		return fmt.Errorf("failed to delete caption: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to get rows affected: %w", err)
	}

	if rowsAffected == 0 {
		return domain.ErrNotFound
	}

	return nil
}

// DeleteByVideoID deletes all captions for a video
func (r *captionRepository) DeleteByVideoID(ctx context.Context, videoID uuid.UUID) error {
	query := `DELETE FROM captions WHERE video_id = $1`

	_, err := r.db.ExecContext(ctx, query, videoID)
	if err != nil {
		return fmt.Errorf("failed to delete captions: %w", err)
	}

	return nil
}

// CountByVideoID counts captions for a video
func (r *captionRepository) CountByVideoID(ctx context.Context, videoID uuid.UUID) (int, error) {
	var count int
	query := `SELECT COUNT(*) FROM captions WHERE video_id = $1`

	err := r.db.GetContext(ctx, &count, query, videoID)
	if err != nil {
		return 0, fmt.Errorf("failed to count captions: %w", err)
	}

	return count, nil
}
