package social

import (
	"athena/internal/domain"
	"athena/internal/httpapi/shared"
	"athena/internal/middleware"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
)

type CaptionHandlers struct {
	captionService CaptionServiceInterface
	videoRepo      CaptionVideoRepository
}

func NewCaptionHandlers(captionService CaptionServiceInterface, videoRepo CaptionVideoRepository) *CaptionHandlers {
	return &CaptionHandlers{
		captionService: captionService,
		videoRepo:      videoRepo,
	}
}

func (h *CaptionHandlers) CreateCaption(w http.ResponseWriter, r *http.Request) {
	userID, ok := middleware.GetUserIDFromContext(r.Context())
	if !ok {
		shared.WriteError(w, http.StatusUnauthorized, fmt.Errorf("Unauthorized"))
		return
	}

	videoIDStr := chi.URLParam(r, "id")
	videoID, err := uuid.Parse(videoIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid video ID"))
		return
	}

	video, err := h.videoRepo.GetByID(r.Context(), videoIDStr)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("video not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if video.UserID != userID.String() {
		shared.WriteError(w, http.StatusForbidden, fmt.Errorf("you don't have permission to add captions to this video"))
		return
	}

	if err := r.ParseMultipartForm(10 << 20); err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("failed to parse form data"))
		return
	}

	languageCode := r.FormValue("language_code")
	label := r.FormValue("label")
	fileFormat := r.FormValue("file_format")
	isAutoGenerated := r.FormValue("is_auto_generated") == "true"

	if languageCode == "" || label == "" {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("language_code and label are required"))
		return
	}

	file, header, err := r.FormFile("caption_file")
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("caption_file is required"))
		return
	}
	defer func() { _ = file.Close() }()

	if fileFormat == "" {
		ext := strings.ToLower(strings.TrimPrefix(header.Filename[strings.LastIndex(header.Filename, "."):], "."))
		if ext == "vtt" || ext == "srt" {
			fileFormat = ext
		} else {
			shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("unsupported file format, must be vtt or srt"))
			return
		}
	}

	req := &domain.CreateCaptionRequest{
		LanguageCode:    languageCode,
		Label:           label,
		FileFormat:      domain.CaptionFormat(fileFormat),
		IsAutoGenerated: isAutoGenerated,
	}

	caption, err := h.captionService.CreateCaption(r.Context(), videoID, req, file)
	if err != nil {
		if domainErr, ok := err.(*domain.DomainError); ok {
			shared.WriteError(w, http.StatusBadRequest, domainErr)
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	shared.WriteJSON(w, http.StatusCreated, caption)
}

func (h *CaptionHandlers) GetCaptions(w http.ResponseWriter, r *http.Request) {
	videoIDStr := chi.URLParam(r, "id")
	videoID, err := uuid.Parse(videoIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid video ID"))
		return
	}

	video, err := h.videoRepo.GetByID(r.Context(), videoIDStr)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("video not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if video.Privacy == domain.PrivacyPrivate {
		userID, authenticated := middleware.GetUserIDFromContext(r.Context())
		if !authenticated || video.UserID != userID.String() {
			shared.WriteError(w, http.StatusForbidden, fmt.Errorf("video is private"))
			return
		}
	}

	response, err := h.captionService.GetCaptionsByVideoID(r.Context(), videoID)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("video not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	shared.WriteJSON(w, http.StatusOK, response)
}

func (h *CaptionHandlers) GetCaptionContent(w http.ResponseWriter, r *http.Request) {
	videoIDStr := chi.URLParam(r, "id")
	videoID, err := uuid.Parse(videoIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid video ID"))
		return
	}

	captionIDStr := chi.URLParam(r, "captionId")
	captionID, err := uuid.Parse(captionIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid caption ID"))
		return
	}

	video, err := h.videoRepo.GetByID(r.Context(), videoIDStr)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("video not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if video.Privacy == domain.PrivacyPrivate {
		userID, authenticated := middleware.GetUserIDFromContext(r.Context())
		if !authenticated || video.UserID != userID.String() {
			shared.WriteError(w, http.StatusForbidden, fmt.Errorf("video is private"))
			return
		}
	}

	caption, err := h.captionService.GetCaptionByID(r.Context(), captionID)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if caption.VideoID != videoID {
		shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found for this video"))
		return
	}

	content, contentType, err := h.captionService.GetCaptionContent(r.Context(), captionID)
	if err != nil {
		if domainErr, ok := err.(*domain.DomainError); ok {
			shared.WriteError(w, http.StatusNotFound, domainErr)
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}
	defer func() { _ = content.Close() }()

	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Cache-Control", "public, max-age=3600")

	if _, err := io.Copy(w, content); err != nil {
		fmt.Printf("Error streaming caption content: %v\n", err)
	}
}

func (h *CaptionHandlers) UpdateCaption(w http.ResponseWriter, r *http.Request) {
	userID, ok := middleware.GetUserIDFromContext(r.Context())
	if !ok {
		shared.WriteError(w, http.StatusUnauthorized, fmt.Errorf("Unauthorized"))
		return
	}

	videoIDStr := chi.URLParam(r, "id")
	videoID, err := uuid.Parse(videoIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid video ID"))
		return
	}

	captionIDStr := chi.URLParam(r, "captionId")
	captionID, err := uuid.Parse(captionIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid caption ID"))
		return
	}

	video, err := h.videoRepo.GetByID(r.Context(), videoIDStr)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("video not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if video.UserID != userID.String() {
		shared.WriteError(w, http.StatusForbidden, fmt.Errorf("you don't have permission to edit captions for this video"))
		return
	}

	existingCaption, err := h.captionService.GetCaptionByID(r.Context(), captionID)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if existingCaption.VideoID != videoID {
		shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found for this video"))
		return
	}

	var req domain.UpdateCaptionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid request body"))
		return
	}

	caption, err := h.captionService.UpdateCaption(r.Context(), captionID, &req)
	if err != nil {
		if domainErr, ok := err.(*domain.DomainError); ok {
			shared.WriteError(w, http.StatusBadRequest, domainErr)
			return
		}
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	shared.WriteJSON(w, http.StatusOK, caption)
}

func (h *CaptionHandlers) DeleteCaption(w http.ResponseWriter, r *http.Request) {
	userID, ok := middleware.GetUserIDFromContext(r.Context())
	if !ok {
		shared.WriteError(w, http.StatusUnauthorized, fmt.Errorf("Unauthorized"))
		return
	}

	videoIDStr := chi.URLParam(r, "id")
	videoID, err := uuid.Parse(videoIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid video ID"))
		return
	}

	captionIDStr := chi.URLParam(r, "captionId")
	captionID, err := uuid.Parse(captionIDStr)
	if err != nil {
		shared.WriteError(w, http.StatusBadRequest, fmt.Errorf("invalid caption ID"))
		return
	}

	video, err := h.videoRepo.GetByID(r.Context(), videoIDStr)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("video not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if video.UserID != userID.String() {
		shared.WriteError(w, http.StatusForbidden, fmt.Errorf("you don't have permission to delete captions for this video"))
		return
	}

	caption, err := h.captionService.GetCaptionByID(r.Context(), captionID)
	if err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	if caption.VideoID != videoID {
		shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found for this video"))
		return
	}

	if err := h.captionService.DeleteCaption(r.Context(), captionID); err != nil {
		if err == domain.ErrNotFound {
			shared.WriteError(w, http.StatusNotFound, fmt.Errorf("caption not found"))
			return
		}
		shared.WriteError(w, http.StatusInternalServerError, err)
		return
	}

	shared.WriteJSON(w, http.StatusOK, map[string]string{
		"status": "deleted",
	})
}
