package setup

import (
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// The managed reverse proxy (phase-1 item 11).
//
// deploy/Caddyfile in the meta repo is a WORKING Caddyfile, not a Go template:
// it parses, `caddy validate` accepts it, and an operator can copy it, replace
// example.com by hand and deploy. That is deliberate — a reverse proxy config
// nobody can read without running the generator is a config nobody reviews — and
// it is what shapes everything below. The engine makes exactly three edits to it:
//
//  1. `example.com` -> the instance's host, on every NON-COMMENT line. The
//     comments keep the example (they are prose about example.com), which is
//     also the rule deploy/deploy.sh enforces from the other side: it refuses to
//     deploy while any non-comment line still names example.com.
//  2. the TLS issuer at `# vidra:global-options` — the ACME contact address when
//     there is one, and the staging directory when this is a rehearsal.
//  3. `tls internal` at `# vidra:tls` for the pre-TLS/loopback bring-up mode.
//
// Everything else — the single-origin routing decision, the /metrics 404, the
// dial-time retry budgets — is carried through byte for byte. The rendered file
// is deploy/Caddyfile.local, which the prod compose file bind-mounts.
//
// THE MARKERS ARE THE DRIFT DETECTOR, and a missing one is a hard failure rather
// than a silent skip. Injecting nothing where the TLS issuer should go produces a
// file that looks right and deploys: Caddy simply orders a certificate from the
// production CA with no contact address (or, worse, a rehearsal that was supposed
// to hit the staging CA hits the real one and spends the instance's Let's Encrypt
// rate limit). A template someone edited without keeping the markers has to stop
// the run, not quietly change what TLS the deployment gets.
const (
	// caddyGlobalMarker sits inside the global options block, next to the
	// commented `email` line, and receives the ACME issuer settings.
	caddyGlobalMarker = "# vidra:global-options"
	// caddyTLSMarker sits near the top of the site block and receives the
	// site-level `tls` directive.
	caddyTLSMarker = "# vidra:tls"
	// caddyDomainToken is the template's placeholder site address.
	caddyDomainToken = "example.com"
	// CaddyTemplatePath and CaddyOutputPath are the deployment's conventional
	// paths, spelled here so the CLI, the installer and the web wizard cannot
	// disagree about which file is the template and which one compose mounts.
	CaddyTemplatePath = "deploy/Caddyfile"
	CaddyOutputPath   = "deploy/Caddyfile.local"

	acmeStagingCA = "https://acme-staging-v02.api.letsencrypt.org/directory"
)

// The TLS modes. acme is the production answer; the other two are rehearsal and
// bring-up modes, and neither produces a certificate any browser trusts.
const (
	// TLSModeACME orders a real certificate from Let's Encrypt.
	TLSModeACME = "acme"
	// TLSModeACMEStaging orders from the Let's Encrypt STAGING directory: an
	// untrusted certificate, but a full rehearsal of the ACME order against a CA
	// with far higher rate limits. It is how a domain's DNS/port-80 reachability
	// gets proven without spending the five-per-week production limit.
	TLSModeACMEStaging = "acme-staging"
	// TLSModeInternal issues from Caddy's own local CA: no ACME order at all, so
	// the stack comes up on a host whose DNS does not point at it yet.
	TLSModeInternal = "internal"
)

var tlsModes = []string{TLSModeACME, TLSModeACMEStaging, TLSModeInternal}

// caddyMarkers is every marker the template must carry, with the location an
// operator needs told when one has gone missing.
var caddyMarkers = []struct {
	marker string
	where  string
}{
	{caddyGlobalMarker, "inside the global options block at the top of the file, next to the commented `email` line"},
	{caddyTLSMarker, "inside the site block, just below its opening brace"},
}

// caddyHeader is prepended to every rendered file. It is the first thing an
// operator opening deploy/Caddyfile.local reads, so it says where the content
// came from and where an edit belongs — a hand-edited generated file is lost at
// the next `vidra setup`, and the loss is silent.
const caddyHeader = "# ------------------------------------------------------------------------------\n" +
	"# GENERATED by `vidra setup` from " + CaddyTemplatePath + " — do not hand-edit.\n" +
	"# ------------------------------------------------------------------------------\n" +
	"# Re-run `vidra setup` to regenerate it; anything written here is lost when that\n" +
	"# happens. Hand edits belong in " + CaddyTemplatePath + ", the template this was\n" +
	"# rendered from — everything below except the site address and the TLS settings\n" +
	"# is that file, byte for byte.\n" +
	"#\n" +
	"# The `caddy` service in docker-compose.prod.yml bind-mounts THIS file at\n" +
	"# /etc/caddy/Caddyfile, so a change takes effect on a `caddy reload`.\n" +
	"\n"

// RenderCaddyfile renders the deployment's Caddyfile from the marked template.
// It is pure — bytes in, bytes out, no filesystem — so the CLI, the installer and
// the web wizard render the same file, and so a caller can show it before writing
// anything. Given the same template and the same answers it returns the same
// bytes.
//
// Three answers are consulted: Answers.Domain (the site address), Answers.TLSMode
// and Answers.AcmeEmail. Everything else about the proxy lives in the template.
func RenderCaddyfile(template []byte, a Answers) ([]byte, error) {
	mode, err := tlsMode(a.TLSMode)
	if err != nil {
		return nil, err
	}
	if mode == "" {
		mode = TLSModeACME
	}
	// A blank contact address is a legitimate answer, and the ONE thing this
	// renderer must not do with it is refuse: the shipped template ships
	// VIDRA_ACME_EMAIL blank ("Optional but strongly recommended"), so a refusal
	// here would stop every unattended install and every upgrade on a file the
	// engine itself wrote. It costs a warning (see tlsWarnings) and nothing else —
	// Caddy orders certificates perfectly well from an account with no contact
	// address, it just cannot be told when a renewal starts failing.
	email := strings.TrimSpace(a.AcmeEmail)
	if email != "" {
		if err := checkAcmeEmailShape(email); err != nil {
			return nil, err
		}
	}
	host, err := caddyHost(a.Domain)
	if err != nil {
		return nil, err
	}
	global, site := caddyInjections(mode, email)

	var buf bytes.Buffer
	buf.WriteString(caddyHeader)
	substitutions := 0
	seen := map[string]int{}
	for _, raw := range splitLines(template) {
		trimmed := strings.TrimSpace(raw)
		if trimmed == caddyGlobalMarker || trimmed == caddyTLSMarker {
			seen[trimmed]++
			buf.WriteString(raw)
			buf.WriteByte('\n')
			inject := global
			if trimmed == caddyTLSMarker {
				inject = site
			}
			// The marker's own indentation: a directive at column zero inside a
			// block still parses, but the file is read by people.
			indent := raw[:len(raw)-len(strings.TrimLeft(raw, " \t"))]
			for _, directive := range inject {
				buf.WriteString(indent)
				buf.WriteString(directive)
				buf.WriteByte('\n')
			}
			continue
		}
		// Comment lines keep the example: they are prose ABOUT example.com, and
		// rewriting them would produce sentences about the operator's own domain
		// that were never true of it. deploy.sh greps the non-comment lines only.
		if !strings.HasPrefix(trimmed, "#") {
			if n := strings.Count(raw, caddyDomainToken); n > 0 {
				substitutions += n
				raw = strings.ReplaceAll(raw, caddyDomainToken, host)
			}
		}
		buf.WriteString(raw)
		buf.WriteByte('\n')
	}
	if err := checkCaddyMarkers(seen); err != nil {
		return nil, err
	}
	if substitutions == 0 {
		return nil, fmt.Errorf("setup: no non-comment line of the Caddyfile template names %s, so there is no site address to fill in — the template's site block must keep %s as its placeholder address (it is also what deploy/deploy.sh greps for to refuse a half-configured deploy)", caddyDomainToken, caddyDomainToken)
	}
	return buf.Bytes(), nil
}

// checkCaddyMarkers turns a marker that has gone missing (or been duplicated by a
// copy-paste) into a refusal naming the marker and where it belongs. See the
// package comment above: a silent skip here changes what TLS a deployment gets.
func checkCaddyMarkers(seen map[string]int) error {
	var problems []string
	for _, m := range caddyMarkers {
		switch n := seen[m.marker]; {
		case n == 0:
			problems = append(problems, fmt.Sprintf("%q is missing (it belongs %s)", m.marker, m.where))
		case n > 1:
			problems = append(problems, fmt.Sprintf("%q appears %d times (it must appear exactly once, %s) — the directives would be injected at every one", m.marker, n, m.where))
		}
	}
	if len(problems) == 0 {
		return nil
	}
	sort.Strings(problems)
	return fmt.Errorf("setup: the Caddyfile template has drifted: %s. `vidra setup` injects the TLS configuration at those markers, so a template without them would deploy whatever TLS the template itself hard-codes — restore them in %s, or pass --no-caddy to manage the reverse proxy by hand", strings.Join(problems, "; "), CaddyTemplatePath)
}

// caddyInjections is the whole mapping from a TLS mode to the directives it
// contributes, in one place so the two markers cannot disagree.
//
//	acme          global: email <contact>, when there is one
//	acme-staging  global: email <contact> when there is one, acme_ca <staging>
//	internal      site:   tls internal
//
// A BLANK contact address injects no `email` line at all rather than an empty
// one: `email` with no argument is a Caddyfile that does not parse, so the
// deployment would come up with no reverse proxy — a far worse answer to "the
// operator did not give us an address" than the warning tlsWarnings prints.
//
// Nothing is injected at the OTHER marker in each case, deliberately: `tls
// internal` beside an `email` would be a site that ignores the ACME settings
// above it, which is exactly the kind of half-applied mode this whole file exists
// to make impossible.
func caddyInjections(mode, email string) (global, site []string) {
	switch mode {
	case TLSModeACME:
		if email != "" {
			global = []string{"email " + email}
		}
	case TLSModeACMEStaging:
		if email != "" {
			global = append(global, "email "+email)
		}
		global = append(global, "acme_ca "+acmeStagingCA)
	case TLSModeInternal:
		site = []string{"tls internal"}
	}
	return global, site
}

// caddyHost is the site address the template's placeholder becomes: the HOST of
// the instance's origin. It goes through normalizeOrigin so the Caddyfile and
// PUBLIC_BASE_URL cannot name different hosts — the certificate Caddy provisions
// has to cover the origin the api mints links for.
func caddyHost(domain string) (string, error) {
	if strings.TrimSpace(domain) == "" {
		return "", errors.New("setup: the instance domain is required to render the Caddyfile — the site address is the one hostname Caddy provisions a certificate for (pass --domain video.example.org)")
	}
	origin, err := normalizeOrigin(domain)
	if err != nil {
		return "", err
	}
	return strings.TrimPrefix(origin, "https://"), nil
}

// NormalizeTLSMode is the TLS answer's validator, exported for the same reason
// as NormalizeOrigin: a prompt that can reject a typo where it was typed. "" is
// unanswered and therefore valid — the caller decides what unanswered means.
func NormalizeTLSMode(v string) (string, error) { return tlsMode(v) }

// CheckAcmeEmail is the contact address's validator, exported alongside the two
// above. An EMPTY address is valid here: the contact is optional (the template
// ships it blank and calls it recommended), and refusing it at a prompt would be
// refusing what the file itself allows.
func CheckAcmeEmail(email string) error {
	if strings.TrimSpace(email) == "" {
		return nil
	}
	return checkAcmeEmailShape(email)
}

// tlsMode validates the answer. "" is "unanswered" like every other answer in
// this package, and the caller decides what that means: RenderCaddyfile treats it
// as acme, the env-file path leaves the existing value alone.
func tlsMode(v string) (string, error) {
	switch mode := strings.TrimSpace(v); mode {
	case "":
		return "", nil
	case TLSModeACME, TLSModeACMEStaging, TLSModeInternal:
		return mode, nil
	default:
		return "", fmt.Errorf("setup: unsupported TLS mode %q (want %s)", mode, strings.Join(tlsModes, "|"))
	}
}

// PlaceholderDomainPattern is the placeholder-domain test, spelled as the exact
// POSIX extended regular expression deploy/deploy.sh's require_real_domain greps
// deploy/Caddyfile.local with. It is a CROSS-REPO CONTRACT: the shell refuses to
// deploy a file that matches it and `vidra doctor` reports one, so the two have
// to be the same test — a doctor that is stricter fails a valid install, and one
// that is laxer stays green right up to the deploy that refuses.
//
// Both boundaries are load-bearing, and both exist for a real hostname:
//
//	myexample.com          NOT a placeholder — the left boundary rejects a match
//	                       whose preceding character is a hostname character
//	video.example.company  NOT a placeholder — the right boundary does the same
//	                       for the character after it
//	sub.example.com        IS a placeholder — '.' is deliberately absent from the
//	                       boundary class, so a subdomain OF the example still
//	                       matches
//
// '.' is what makes the two rules different from a plain word boundary, and it
// is the whole reason the class is written out rather than spelled \b.
const PlaceholderDomainPattern = `(^|[^A-Za-z0-9-])(example\.(com|org|net)|your-domain|yourdomain|YOUR_DOMAIN)([^A-Za-z0-9-]|$)`

var placeholderDomainRE = regexp.MustCompile(PlaceholderDomainPattern)

// PlaceholderDomain reports the placeholder domain s names, and which one it is
// so a finding can quote it. It is the ONE implementation of
// PlaceholderDomainPattern in this module: a second `strings.Contains` spelling
// of the same idea is what made `myexample.com` an install doctor refused and
// `tube.example.org` one it waved through.
//
// Call it on a NON-COMMENT line: the Caddyfile template's comments are prose
// about example.com and are meant to keep it, which is the same line deploy.sh
// filters out before it greps.
func PlaceholderDomain(s string) (string, bool) {
	m := placeholderDomainRE.FindStringSubmatch(s)
	if m == nil {
		return "", false
	}
	return m[2], true
}

// checkAcmeEmailShape rejects a value that would not survive being written as a
// bare Caddyfile token. This is not address validation — nobody should be
// rejected for a legal address a regexp had not heard of — it is the shape the
// FILE needs: `email` takes one argument, so a space makes the rest a second
// argument Caddy rejects, and a brace or a quote reshapes the surrounding block.
func checkAcmeEmailShape(email string) error {
	bad := func(why string) error {
		return fmt.Errorf("setup: %q is not usable as the ACME contact address (%s) — it is written as the argument of Caddy's `email` directive, which takes one bare token", email, why)
	}
	switch {
	case strings.ContainsAny(email, " \t\r\n"):
		return bad("it contains whitespace, so Caddy would read the remainder as a second argument")
	case strings.ContainsAny(email, `"'{}`):
		return bad("it contains a quote or a brace, which would reshape the block around it")
	case strings.ContainsFunc(email, func(r rune) bool { return r < 0x20 || r == 0x7f }):
		return bad("it contains a control character")
	case !strings.Contains(email, "@"), strings.HasPrefix(email, "@"), strings.HasSuffix(email, "@"):
		return bad("it is not an email address")
	}
	return nil
}

// splitLines splits a file into lines, normalising CRLF and dropping the trailing
// empty element after a final newline — Render puts that newline back.
func splitLines(b []byte) []string {
	text := strings.TrimSuffix(string(b), "\n")
	if text == "" {
		return nil
	}
	lines := strings.Split(text, "\n")
	for i, ln := range lines {
		lines[i] = strings.TrimSuffix(ln, "\r")
	}
	return lines
}
