package setup

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// caddyTemplate is the marked template the renderer consumes. It is a COPY of
// the meta repo's deploy/Caddyfile with the two markers added, kept here so a
// drift between the two repos shows up as a failing test in this one rather than
// as a deploy that quietly gets the wrong TLS.
func caddyTemplate(t *testing.T) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "Caddyfile.template"))
	if err != nil {
		t.Fatalf("read Caddyfile fixture: %v", err)
	}
	return b
}

func caddyAnswers() Answers {
	return Answers{Domain: "video.example.org", TLSMode: TLSModeACME, AcmeEmail: "ops@example.org"}
}

func renderCaddy(t *testing.T, a Answers) string {
	t.Helper()
	out, err := RenderCaddyfile(caddyTemplate(t), a)
	if err != nil {
		t.Fatalf("RenderCaddyfile: %v", err)
	}
	return string(out)
}

// The whole contract in three artifacts, one per mode. Review a diff here like
// source code: it is the reverse proxy configuration every deployment runs.
// UPDATE_GOLDEN=1 rewrites them.
func TestRenderCaddyfileGolden(t *testing.T) {
	for _, tc := range []struct {
		mode   string
		golden string
	}{
		{TLSModeACME, "Caddyfile.acme.golden"},
		{TLSModeACMEStaging, "Caddyfile.acme-staging.golden"},
		{TLSModeInternal, "Caddyfile.internal.golden"},
	} {
		t.Run(tc.mode, func(t *testing.T) {
			a := caddyAnswers()
			a.TLSMode = tc.mode
			got := renderCaddy(t, a)

			path := filepath.Join("testdata", tc.golden)
			if os.Getenv("UPDATE_GOLDEN") == "1" {
				if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
					t.Fatalf("update golden: %v", err)
				}
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("missing golden — regenerate with UPDATE_GOLDEN=1 go test ./internal/setup -run RenderCaddyfileGolden: %v", err)
			}
			if got != string(want) {
				t.Errorf("rendered Caddyfile drifted from golden\n--- got ---\n%s--- want ---\n%s", got, want)
			}
		})
	}
}

// The rule deploy/deploy.sh enforces from the other side: it refuses to deploy
// while any NON-comment line still names example.com. Every one of them must
// therefore be substituted — and the comments, which are prose about example.com,
// must not be, or the generated file would explain the operator's own domain with
// sentences that were never true of it.
func TestRenderCaddyfileSubstitutesEveryNonCommentSiteAddress(t *testing.T) {
	got := renderCaddy(t, caddyAnswers())

	comments := 0
	for _, line := range strings.Split(got, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "#") {
			if strings.Contains(line, caddyDomainToken) {
				comments++
			}
			continue
		}
		if strings.Contains(line, caddyDomainToken) {
			t.Errorf("a non-comment line still names %s, which deploy.sh refuses to deploy: %q", caddyDomainToken, line)
		}
	}
	if comments == 0 {
		t.Errorf("no comment kept its %s: the substitution is rewriting prose too\n%s", caddyDomainToken, got)
	}
	if !strings.Contains(got, "\nvideo.example.org {\n") {
		t.Errorf("the site address is not the answered host:\n%s", got)
	}
	// The header is the first thing an operator reads, and it has to say the file
	// is generated before they edit it.
	if !strings.HasPrefix(got, "# ---") || !strings.Contains(got, "GENERATED by `vidra setup`") || !strings.Contains(got, "do not hand-edit") {
		t.Errorf("the generated file does not announce itself:\n%s", firstLines(got, 12))
	}
	if !strings.Contains(got, CaddyTemplatePath) {
		t.Errorf("the header does not name the source template %s:\n%s", CaddyTemplatePath, firstLines(got, 12))
	}
}

// An origin answer is the same answer as a bare host: the Caddyfile's site
// address and PUBLIC_BASE_URL have to name the same host, or the certificate does
// not cover the origin the api mints links for.
func TestRenderCaddyfileTakesTheHostFromAnyDomainSpelling(t *testing.T) {
	for _, in := range []string{"video.example.org", "https://video.example.org", "https://VIDEO.Example.ORG/", "video.example.org/"} {
		a := caddyAnswers()
		a.Domain = in
		got := renderCaddy(t, a)
		if !strings.Contains(got, "\nvideo.example.org {\n") {
			t.Errorf("--domain %q did not render video.example.org as the site address", in)
		}
	}
}

// The injections, per mode. `email` and `acme_ca` are global-options directives;
// `tls internal` is a site directive — putting either in the other's block is a
// Caddyfile that does not parse, which is why the mapping lives in one function.
func TestRenderCaddyfileInjectsThePerModeTLSDirectives(t *testing.T) {
	for _, tc := range []struct {
		mode        string
		want, unwan []string
	}{
		{
			mode:  TLSModeACME,
			want:  []string{"\temail ops@example.org\n"},
			unwan: []string{"acme_ca", "tls internal"},
		},
		{
			mode:  TLSModeACMEStaging,
			want:  []string{"\temail ops@example.org\n", "\tacme_ca " + acmeStagingCA + "\n"},
			unwan: []string{"tls internal"},
		},
		{
			mode:  TLSModeInternal,
			want:  []string{"\ttls internal\n"},
			unwan: []string{"email ops@example.org", "acme_ca"},
		},
	} {
		t.Run(tc.mode, func(t *testing.T) {
			a := caddyAnswers()
			a.TLSMode = tc.mode
			got := renderCaddy(t, a)
			for _, w := range tc.want {
				if !strings.Contains(got, w) {
					t.Errorf("%q was not injected (indentation must match the marker's):\n%s", w, got)
				}
			}
			for _, u := range tc.unwan {
				if strings.Contains(got, u) {
					t.Errorf("%q was injected in %s mode", u, tc.mode)
				}
			}
			// Each directive lands in the block its marker is in, which is the
			// only reason the file still parses.
			global, site := splitAtSiteBlock(t, got)
			if strings.Contains(site, "acme_ca") || strings.Contains(site, "\temail ") {
				t.Errorf("an ACME issuer directive landed in the site block:\n%s", site)
			}
			if strings.Contains(global, "tls internal") {
				t.Errorf("`tls internal` landed in the global options block:\n%s", global)
			}
		})
	}
}

// internal mode is the bring-up answer for a host whose DNS does not point at it
// yet: there is no ACME order, so there is nobody to send expiry notices to.
func TestRenderCaddyfileInternalNeedsNoAcmeEmail(t *testing.T) {
	got := renderCaddy(t, Answers{Domain: "video.example.org", TLSMode: TLSModeInternal})
	if !strings.Contains(got, "tls internal") {
		t.Errorf("internal mode did not inject its issuer:\n%s", got)
	}
}

// An unanswered mode is acme: it is what the deploy scripts assume for an env
// file that predates the key, and the two must not disagree.
func TestRenderCaddyfileDefaultsToACME(t *testing.T) {
	got := renderCaddy(t, Answers{Domain: "video.example.org", AcmeEmail: "ops@example.org"})
	if !strings.Contains(got, "email ops@example.org") {
		t.Errorf("a blank TLS mode did not render as acme:\n%s", got)
	}
}

// Template drift has to be LOUD. A marker that has gone missing would otherwise
// render a file that looks right and deploys with whatever TLS the template
// hard-codes — including, in a rehearsal, a real Let's Encrypt order that spends
// the instance's rate limit.
func TestRenderCaddyfileRefusesTemplateDrift(t *testing.T) {
	tmpl := string(caddyTemplate(t))
	for _, tc := range []struct {
		name     string
		template string
		want     []string
	}{
		{
			name:     "no global options marker",
			template: strings.Replace(tmpl, "\t"+caddyGlobalMarker+"\n", "", 1),
			want:     []string{caddyGlobalMarker, "missing", "drifted"},
		},
		{
			name:     "no tls marker",
			template: strings.Replace(tmpl, "\t"+caddyTLSMarker+"\n", "", 1),
			want:     []string{caddyTLSMarker, "missing"},
		},
		{
			name:     "both markers gone",
			template: strings.NewReplacer("\t"+caddyGlobalMarker+"\n", "", "\t"+caddyTLSMarker+"\n", "").Replace(tmpl),
			want:     []string{caddyGlobalMarker, caddyTLSMarker},
		},
		{
			name:     "a marker duplicated by a copy-paste",
			template: strings.Replace(tmpl, "\t"+caddyTLSMarker+"\n", "\t"+caddyTLSMarker+"\n\t"+caddyTLSMarker+"\n", 1),
			want:     []string{caddyTLSMarker, "exactly once"},
		},
		{
			name:     "the placeholder site address was already replaced",
			template: strings.Replace(tmpl, "\nexample.com {", "\nvideo.example.org {", 1),
			want:     []string{"no non-comment line", caddyDomainToken},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := RenderCaddyfile([]byte(tc.template), caddyAnswers())
			if err == nil {
				t.Fatal("drifted template rendered without complaint")
			}
			for _, w := range tc.want {
				if !strings.Contains(err.Error(), w) {
					t.Errorf("error does not mention %q: %v", w, err)
				}
			}
		})
	}
}

// The answers the renderer refuses. Each one would produce a file that parses
// (or nearly does) and is wrong in a way nobody notices until a certificate is
// not there.
func TestRenderCaddyfileRefusesBadAnswers(t *testing.T) {
	for _, tc := range []struct {
		name    string
		answers Answers
		want    string
	}{
		{
			name:    "unknown mode",
			answers: Answers{Domain: "video.example.org", TLSMode: "letsencrypt", AcmeEmail: "ops@example.org"},
			want:    "unsupported TLS mode",
		},
		{
			name:    "acme with no contact address",
			answers: Answers{Domain: "video.example.org", TLSMode: TLSModeACME},
			want:    "--acme-email",
		},
		{
			name:    "acme-staging with no contact address",
			answers: Answers{Domain: "video.example.org", TLSMode: TLSModeACMEStaging},
			want:    "--acme-email",
		},
		{
			name:    "a contact address with a space in it",
			answers: Answers{Domain: "video.example.org", TLSMode: TLSModeACME, AcmeEmail: "ops@example.org please"},
			want:    "whitespace",
		},
		{
			name:    "a contact address that would reshape the block",
			answers: Answers{Domain: "video.example.org", TLSMode: TLSModeACME, AcmeEmail: "ops@example.org}"},
			want:    "brace",
		},
		{
			name:    "a contact address that is not one",
			answers: Answers{Domain: "video.example.org", TLSMode: TLSModeACME, AcmeEmail: "ops"},
			want:    "not an email address",
		},
		{
			name:    "no domain",
			answers: Answers{TLSMode: TLSModeInternal},
			want:    "the instance domain is required",
		},
		{
			name:    "a wildcard domain",
			answers: Answers{Domain: "*.example.org", TLSMode: TLSModeInternal},
			want:    "wildcards are not a host",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := RenderCaddyfile(caddyTemplate(t), tc.answers)
			if err == nil {
				t.Fatal("bad answers rendered without complaint")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error does not mention %q: %v", tc.want, err)
			}
		})
	}
}

// The same answers must produce the same bytes: the file is bind-mounted, and a
// re-run that rewrote it differently would ask for a reload that changes nothing.
func TestRenderCaddyfileIsDeterministic(t *testing.T) {
	for _, mode := range tlsModes {
		a := caddyAnswers()
		a.TLSMode = mode
		if first, second := renderCaddy(t, a), renderCaddy(t, a); first != second {
			t.Errorf("%s mode rendered differently twice", mode)
		}
	}
}

// splitAtSiteBlock cuts a rendered file at the site address so a test can say
// which BLOCK a directive landed in.
func splitAtSiteBlock(t *testing.T, rendered string) (global, site string) {
	t.Helper()
	i := strings.Index(rendered, "\nvideo.example.org {\n")
	if i < 0 {
		t.Fatalf("no site block in the rendered file:\n%s", rendered)
	}
	return rendered[:i], rendered[i:]
}

func firstLines(s string, n int) string {
	lines := strings.Split(s, "\n")
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}
