package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func computePublicBaseURL(domain string, port int, protocol string) string {
	// Build PUBLIC_BASE_URL: {protocol}://{domain}[:{port}]
	baseURL := fmt.Sprintf("%s://%s", protocol, domain)

	if (protocol == "http" && port != 80) || (protocol == "https" && port != 443) {
		baseURL = fmt.Sprintf("%s:%d", baseURL, port)
	}

	return baseURL
}

func WriteEnvFile(path string, config *WizardConfig) error {
	var lines []string

	lines = append(lines, "# Athena Configuration")
	lines = append(lines, "# Generated by setup wizard")
	lines = append(lines, "")

	lines = append(lines, "# Database Configuration")
	lines = append(lines, fmt.Sprintf("POSTGRES_MODE=%s", config.PostgresMode))
	if config.PostgresMode == "external" && config.DatabaseURL != "" {
		lines = append(lines, fmt.Sprintf("DATABASE_URL=%s", config.DatabaseURL))
	}
	lines = append(lines, "")

	lines = append(lines, "# Redis Configuration")
	lines = append(lines, fmt.Sprintf("REDIS_MODE=%s", config.RedisMode))
	if config.RedisMode == "external" && config.RedisURL != "" {
		lines = append(lines, fmt.Sprintf("REDIS_URL=%s", config.RedisURL))
	}
	lines = append(lines, "")

	lines = append(lines, "# IPFS Configuration")
	lines = append(lines, fmt.Sprintf("ENABLE_IPFS=%t", config.EnableIPFS))
	if config.EnableIPFS {
		lines = append(lines, fmt.Sprintf("IPFS_MODE=%s", config.IPFSMode))
		if config.IPFSMode == "external" && config.IPFSAPIUrl != "" {
			lines = append(lines, fmt.Sprintf("IPFS_API_URL=%s", config.IPFSAPIUrl))
		}
	}
	lines = append(lines, "")

	lines = append(lines, "# Optional Services")
	lines = append(lines, fmt.Sprintf("ENABLE_CLAMAV=%t", config.EnableClamAV))
	lines = append(lines, fmt.Sprintf("ENABLE_WHISPER=%t", config.EnableWhisper))
	lines = append(lines, "")

	lines = append(lines, "# Storage Configuration")
	lines = append(lines, fmt.Sprintf("STORAGE_PATH=%s", config.StoragePath))
	lines = append(lines, "")

	if config.BackupEnabled {
		lines = append(lines, "# Backup Configuration")
		lines = append(lines, fmt.Sprintf("BACKUP_ENABLED=%t", config.BackupEnabled))
		lines = append(lines, fmt.Sprintf("BACKUP_TARGET=%s", config.BackupTarget))
		lines = append(lines, fmt.Sprintf("BACKUP_SCHEDULE=%s", config.BackupSchedule))
		lines = append(lines, fmt.Sprintf("BACKUP_RETENTION=%s", config.BackupRetention))
		lines = append(lines, fmt.Sprintf("BACKUP_LOCAL_PATH=%s", config.BackupLocalPath))
		lines = append(lines, "")
	}

	lines = append(lines, "# Nginx Configuration")
	lines = append(lines, "NGINX_ENABLED=true")
	lines = append(lines, fmt.Sprintf("NGINX_DOMAIN=%s", config.NginxDomain))
	lines = append(lines, fmt.Sprintf("NGINX_PORT=%d", config.NginxPort))
	lines = append(lines, fmt.Sprintf("NGINX_PROTOCOL=%s", config.NginxProtocol))
	lines = append(lines, fmt.Sprintf("NGINX_TLS_MODE=%s", config.NginxTLSMode))
	if config.NginxEmail != "" {
		lines = append(lines, fmt.Sprintf("NGINX_LETSENCRYPT_EMAIL=%s", config.NginxEmail))
	}
	lines = append(lines, "")

	lines = append(lines, "# Public URL")
	publicURL := computePublicBaseURL(config.NginxDomain, config.NginxPort, config.NginxProtocol)
	lines = append(lines, fmt.Sprintf("PUBLIC_BASE_URL=%s", publicURL))
	lines = append(lines, "")

	lines = append(lines, "# Security Configuration")
	lines = append(lines, fmt.Sprintf("JWT_SECRET=%s", config.JWTSecret))
	lines = append(lines, "")

	lines = append(lines, "# Setup Status")
	lines = append(lines, "SETUP_COMPLETED=true")
	lines = append(lines, "")

	content := strings.Join(lines, "\n")

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}

	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("writing temp file: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("renaming file: %w", err)
	}

	return nil
}
