package setup

import (
	cryptoRand "crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func computePublicBaseURL(domain string, port int, protocol string) string {
	// Build PUBLIC_BASE_URL: {protocol}://{domain}[:{port}]
	baseURL := fmt.Sprintf("%s://%s", protocol, domain)

	if (protocol == "http" && port != 80) || (protocol == "https" && port != 443) {
		baseURL = fmt.Sprintf("%s:%d", baseURL, port)
	}

	return baseURL
}

func WriteEnvFile(path string, config *WizardConfig) error { //nolint:gocyclo // large config serializer, complexity is inherent
	var lines []string

	lines = append(lines, "# Vidra Core Configuration")
	lines = append(lines, "# Generated by setup wizard")
	lines = append(lines, "")

	lines = append(lines, "# Database Configuration")
	lines = append(lines, fmt.Sprintf("POSTGRES_MODE=%s", config.PostgresMode))
	if config.PostgresMode == "external" && config.DatabaseURL != "" {
		// Write DATABASE_URL (required by internal/config/config.go)
		lines = append(lines, fmt.Sprintf("DATABASE_URL=%s", config.DatabaseURL))
		// Also write individual fields for reference
		lines = append(lines, fmt.Sprintf("POSTGRES_HOST=%s", config.PostgresHost))
		lines = append(lines, fmt.Sprintf("POSTGRES_PORT=%d", config.PostgresPort))
		lines = append(lines, fmt.Sprintf("POSTGRES_USER=%s", config.PostgresUser))
		lines = append(lines, fmt.Sprintf("POSTGRES_PASSWORD=%s", config.PostgresPassword))
		lines = append(lines, fmt.Sprintf("POSTGRES_DB=%s", config.PostgresDB))
		lines = append(lines, fmt.Sprintf("POSTGRES_SSLMODE=%s", config.PostgresSSLMode))
	}
	lines = append(lines, "")

	lines = append(lines, "# Redis Configuration")
	lines = append(lines, fmt.Sprintf("REDIS_MODE=%s", config.RedisMode))
	if config.RedisMode == "external" && config.RedisURL != "" {
		lines = append(lines, fmt.Sprintf("REDIS_URL=%s", config.RedisURL))
	}
	lines = append(lines, "")

	lines = append(lines, "# IPFS Configuration")
	lines = append(lines, fmt.Sprintf("ENABLE_IPFS=%t", config.EnableIPFS))
	if config.EnableIPFS {
		lines = append(lines, fmt.Sprintf("IPFS_MODE=%s", config.IPFSMode))
		if config.IPFSMode == "external" && config.IPFSAPIUrl != "" {
			lines = append(lines, fmt.Sprintf("IPFS_API_URL=%s", config.IPFSAPIUrl))
		}
	}
	lines = append(lines, "")

	lines = append(lines, "# IOTA Payments Configuration")
	lines = append(lines, fmt.Sprintf("ENABLE_IOTA=%t", config.EnableIOTA))
	if config.EnableIOTA {
		iotaMode := config.IOTAMode
		if iotaMode == "" {
			iotaMode = "docker"
		}
		lines = append(lines, fmt.Sprintf("IOTA_MODE=%s", iotaMode))
		iotaNetwork := config.IOTANetwork
		if iotaNetwork == "" {
			iotaNetwork = "testnet"
		}
		lines = append(lines, fmt.Sprintf("IOTA_NETWORK=%s", iotaNetwork))
		if iotaMode == "external" && config.IOTANodeURL != "" {
			lines = append(lines, fmt.Sprintf("IOTA_NODE_URL=%s", config.IOTANodeURL))
		} else {
			lines = append(lines, "IOTA_NODE_URL=http://iota-node:9000")
		}
		walletKey := make([]byte, 32)
		if _, err := cryptoRand.Read(walletKey); err != nil {
			return fmt.Errorf("generating IOTA wallet encryption key: %w", err)
		}
		lines = append(lines, fmt.Sprintf("IOTA_WALLET_ENCRYPTION_KEY=%s", hex.EncodeToString(walletKey)))
	}
	lines = append(lines, "")

	lines = append(lines, "# Optional Services")
	lines = append(lines, fmt.Sprintf("ENABLE_CLAMAV=%t", config.EnableClamAV))
	lines = append(lines, fmt.Sprintf("ENABLE_WHISPER=%t", config.EnableWhisper))
	lines = append(lines, "")

	lines = append(lines, "# Email Configuration")
	lines = append(lines, fmt.Sprintf("ENABLE_EMAIL=%t", config.EnableEmail))
	if config.EnableEmail {
		lines = append(lines, "SMTP_TRANSPORT=smtp")
		lines = append(lines, fmt.Sprintf("SMTP_HOST=%s", config.SMTPHost))
		lines = append(lines, fmt.Sprintf("SMTP_PORT=%d", config.SMTPPort))
		if config.SMTPUsername != "" {
			lines = append(lines, fmt.Sprintf("SMTP_USERNAME=%s", config.SMTPUsername))
		}
		if config.SMTPPassword != "" {
			lines = append(lines, fmt.Sprintf("SMTP_PASSWORD=%s", config.SMTPPassword))
		}
		lines = append(lines, fmt.Sprintf("SMTP_TLS=%t", config.SMTPTLS))
		lines = append(lines, fmt.Sprintf("SMTP_DISABLE_STARTTLS=%t", config.SMTPDisableSTARTTLS))
		lines = append(lines, fmt.Sprintf("SMTP_FROM=%s", config.SMTPFromAddress))
		lines = append(lines, fmt.Sprintf("SMTP_FROM_NAME=%s", config.SMTPFromName))
	}
	lines = append(lines, "")

	lines = append(lines, "# Storage Configuration")
	lines = append(lines, fmt.Sprintf("STORAGE_PATH=%s", config.StoragePath))
	lines = append(lines, "")

	if config.BackupEnabled {
		lines = append(lines, "# Backup Configuration")
		lines = append(lines, fmt.Sprintf("BACKUP_ENABLED=%t", config.BackupEnabled))
		lines = append(lines, fmt.Sprintf("BACKUP_TARGET=%s", config.BackupTarget))
		lines = append(lines, fmt.Sprintf("BACKUP_SCHEDULE=%s", config.BackupSchedule))
		lines = append(lines, fmt.Sprintf("BACKUP_RETENTION=%s", config.BackupRetention))
		lines = append(lines, fmt.Sprintf("BACKUP_LOCAL_PATH=%s", config.BackupLocalPath))
		lines = append(lines, "")
	}

	lines = append(lines, "# Nginx Configuration")
	lines = append(lines, fmt.Sprintf("NGINX_ENABLED=%t", config.NginxEnabled))
	if config.NginxEnabled {
		lines = append(lines, fmt.Sprintf("NGINX_DOMAIN=%s", config.NginxDomain))
		lines = append(lines, fmt.Sprintf("NGINX_PORT=%d", config.NginxPort))
		lines = append(lines, fmt.Sprintf("NGINX_PROTOCOL=%s", config.NginxProtocol))
		lines = append(lines, fmt.Sprintf("NGINX_TLS_MODE=%s", config.NginxTLSMode))
		if config.NginxEmail != "" {
			lines = append(lines, fmt.Sprintf("NGINX_LETSENCRYPT_EMAIL=%s", config.NginxEmail))
		}
	}
	lines = append(lines, "")

	lines = append(lines, "# Public URL")
	if config.NginxEnabled {
		publicURL := computePublicBaseURL(config.NginxDomain, config.NginxPort, config.NginxProtocol)
		lines = append(lines, fmt.Sprintf("PUBLIC_BASE_URL=%s", publicURL))
	} else {
		lines = append(lines, "PUBLIC_BASE_URL=http://localhost:8080")
	}
	lines = append(lines, "")

	lines = append(lines, "# Security Configuration")
	lines = append(lines, fmt.Sprintf("JWT_SECRET=%s", config.JWTSecret))
	lines = append(lines, "")

	if config.AdminUsername != "" || config.AdminEmail != "" {
		lines = append(lines, "# Admin Account (created on first startup)")
		if config.AdminUsername != "" {
			lines = append(lines, fmt.Sprintf("ADMIN_USERNAME=%s", config.AdminUsername))
		}
		if config.AdminEmail != "" {
			lines = append(lines, fmt.Sprintf("ADMIN_EMAIL=%s", config.AdminEmail))
		}
		if config.AdminPassword != "" {
			lines = append(lines, fmt.Sprintf("ADMIN_PASSWORD=%s", config.AdminPassword))
		}
		lines = append(lines, "")
	}

	// Docker Compose Profiles Configuration
	// Build list of profiles to activate based on enabled Docker services
	profiles := make(map[string]bool)

	if config.EnableIPFS && config.IPFSMode == "docker" {
		profiles["ipfs"] = true
	}

	if config.EnableIOTA && config.IOTAMode == "docker" {
		profiles["iota"] = true
	}

	if config.EnableClamAV {
		profiles["media"] = true // ClamAV uses "media" profile
	}

	if config.EnableWhisper {
		profiles["media"] = true // Whisper uses "media" profile (deduplicated by map)
	}

	if config.EnableEmail && config.SMTPMode == "docker" {
		profiles["mail"] = true // Mailpit uses "mail" profile
	}

	if config.NginxTLSMode == "letsencrypt" {
		profiles["letsencrypt"] = true
	}

	// Convert map to sorted comma-separated list for reproducibility
	var profileList []string
	for profile := range profiles {
		profileList = append(profileList, profile)
	}

	lines = append(lines, "# Docker Compose Profiles (managed by setup wizard)")
	if len(profileList) > 0 {
		sort.Strings(profileList)
		lines = append(lines, fmt.Sprintf("COMPOSE_PROFILES=%s", strings.Join(profileList, ",")))
	} else {
		lines = append(lines, "COMPOSE_PROFILES=")
	}
	lines = append(lines, "")

	lines = append(lines, "# Setup Status")
	lines = append(lines, "SETUP_COMPLETED=true")
	lines = append(lines, "")

	content := strings.Join(lines, "\n")

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}

	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("writing temp file: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("renaming file: %w", err)
	}

	return nil
}
