package messaging

import (
	"context"
	"time"

	"athena/internal/domain"
	"athena/internal/httpapi/shared"
	"athena/internal/middleware"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

// Response is an alias for shared.Response for tests
type Response = shared.Response

// ErrorInfo is an alias for shared.ErrorInfo for tests
type ErrorInfo = shared.ErrorInfo

// Meta is an alias for shared.Meta for tests
type Meta = shared.Meta

// MockLiveStreamRepository is a mock implementation for tests using testify
type MockLiveStreamRepository struct {
	mock.Mock
}

// Placeholder methods for MockLiveStreamRepository
func (m *MockLiveStreamRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.LiveStream, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.LiveStream), args.Error(1)
}

func (m *MockLiveStreamRepository) Create(ctx context.Context, stream *domain.LiveStream) error {
	args := m.Called(ctx, stream)
	return args.Error(0)
}

func (m *MockLiveStreamRepository) GetByStreamKey(ctx context.Context, streamKey string) (*domain.LiveStream, error) {
	args := m.Called(ctx, streamKey)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.LiveStream), args.Error(1)
}

func (m *MockLiveStreamRepository) GetByChannelID(ctx context.Context, channelID uuid.UUID, limit, offset int) ([]*domain.LiveStream, error) {
	args := m.Called(ctx, channelID, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*domain.LiveStream), args.Error(1)
}

func (m *MockLiveStreamRepository) GetByUserID(ctx context.Context, userID uuid.UUID, limit, offset int) ([]*domain.LiveStream, error) {
	args := m.Called(ctx, userID, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*domain.LiveStream), args.Error(1)
}

func (m *MockLiveStreamRepository) GetActiveStreams(ctx context.Context, limit, offset int) ([]*domain.LiveStream, error) {
	args := m.Called(ctx, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*domain.LiveStream), args.Error(1)
}

func (m *MockLiveStreamRepository) CountByChannelID(ctx context.Context, channelID uuid.UUID) (int, error) {
	args := m.Called(ctx, channelID)
	return args.Int(0), args.Error(1)
}

func (m *MockLiveStreamRepository) Update(ctx context.Context, stream *domain.LiveStream) error {
	args := m.Called(ctx, stream)
	return args.Error(0)
}

func (m *MockLiveStreamRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	args := m.Called(ctx, id, status)
	return args.Error(0)
}

func (m *MockLiveStreamRepository) UpdateViewerCount(ctx context.Context, id uuid.UUID, count int) error {
	args := m.Called(ctx, id, count)
	return args.Error(0)
}

func (m *MockLiveStreamRepository) Delete(ctx context.Context, id uuid.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockLiveStreamRepository) EndStream(ctx context.Context, id uuid.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// createTestUser is a helper to create test users (stub version)
// This is a simplified version for tests that need to create users in the database
//
//nolint:unused // used in test files
func createTestUser(t interface{}, userRepo interface{}, ctx context.Context, username, email string) *domain.User {
	user := &domain.User{
		ID:        "", // Will be generated by repository
		Username:  username,
		Email:     email,
		Role:      domain.RoleUser,
		IsActive:  true,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	// This is a stub - real implementation would create user in DB
	// For now, just return the user object
	return user
}

// withUserID adds a user ID to the context (test helper)
//
//nolint:unused // used in test files
func withUserID(ctx context.Context, id string) context.Context {
	return context.WithValue(ctx, middleware.UserIDKey, id)
}
