#!/bin/bash
set -e

# setup-production-env.sh
# Verifies and prepares the production environment file generated by rotate-credentials.sh.
# Usage: ./scripts/setup-production-env.sh

NEW_ENV_FILE=".env.production.new"
TARGET_ENV_FILE=".env"

echo "Checking for new credentials file: $NEW_ENV_FILE..."

if [ ! -f "$NEW_ENV_FILE" ]; then
    echo "Error: $NEW_ENV_FILE not found."
    echo "Please run './scripts/rotate-credentials.sh' first."
    exit 1
fi

echo "Verifying content..."

# Check for critical variables
REQUIRED_VARS=("JWT_SECRET" "DATABASE_URL" "REDIS_URL" "ACTIVITYPUB_KEY_ENCRYPTION_KEY")
MISSING=0

for VAR in "${REQUIRED_VARS[@]}"; do
    if ! grep -q "^$VAR=" "$NEW_ENV_FILE"; then
        echo "Error: Missing $VAR in $NEW_ENV_FILE"
        MISSING=1
    fi
done

if [ "$MISSING" -eq 1 ]; then
    echo "Validation failed. The generated file is incomplete."
    exit 1
fi

echo "Validation successful!"
echo ""
echo "NEXT STEPS:"
echo "1. Review the file: cat $NEW_ENV_FILE"
echo "2. If satisfied, replace your current .env (backup first!):"
echo "   cp .env .env.backup"
echo "   cp $NEW_ENV_FILE .env"
echo "3. Restart your services to apply changes."
echo ""
