-- Boot-time job recovery has been REPLACED by lease-expiry sweeps.
--
-- The queries that used to live here requeued every row in 'running' once at
-- start-up. That was safe only under two assumptions -- the process doing it was
-- the deployment's only worker, and it had not started that worker yet -- and
-- neither survives a second instance: a node booting would requeue jobs the other
-- node was actively running, and both would then do the work.
--
-- Each queue now leases on claim, renews while the worker is alive, and has its
-- own SweepExpired* query beside its other statements (see transcoding.sql,
-- import_jobs.sql, caption_jobs.sql, account_exports.sql, peertube_import.sql
-- and channel_syncs.sql). A sweep only touches rows nobody is renewing, so it is
-- correct with any number of instances and can run periodically instead of only
-- at start-up.
--
-- This file is kept as the signpost: it is where someone looks for "how does a
-- crashed job come back".
