apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-storage
  labels:
    app: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-staging
  labels:
    app: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
