apiVersion: v1
kind: Service
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  ports:
  - port: 5001
    targetPort: 5001
    name: api
  - port: 8080
    targetPort: 8080
    name: gateway
  selector:
    app: ipfs
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster
  labels:
    app: ipfs-cluster
spec:
  ports:
  - port: 9094
    targetPort: 9094
    name: api
  - port: 9096
    targetPort: 9096
    name: proxy
  selector:
    app: ipfs-cluster
